// Question bank. c = category, q = question, a = 30-second answer, p = points to add when they dig, f = likely follow-up, s = senior marker
window.QB = [
// ---------------- Networking
{c:"Networking",q:"What happens when you type a URL into the browser and press Enter? Point out the security controls along the way.",
 a:"The browser checks HSTS and caches, resolves DNS, opens a TCP connection, does a TLS handshake and validates the certificate, sends the HTTP request with cookies, the server processes it, and the browser renders the response and applies policies like CSP and SameSite.",
 p:["DNS: cache poisoning and hijacking; DoH/DoT and DNSSEC as defences","TLS: certificate chain, hostname check, HSTS preload stops SSL stripping","HTTP: cookies with Secure/HttpOnly/SameSite; CORS and SOP decide what script can read","Rendering: CSP, X-Content-Type-Options, frame-ancestors"],
 f:"Where exactly could an attacker on the same Wi-Fi interfere, and what stops them?"},
{c:"Networking",q:"TCP vs UDP, and how does a SYN flood work?",
 a:"TCP is connection-oriented with a three-way handshake (SYN, SYN-ACK, ACK), ordering and retransmission; UDP is connectionless and fire-and-forget. A SYN flood sends many SYNs without completing the handshake to fill the server's half-open connection table.",
 p:["Defences: SYN cookies, rate limiting, upstream DDoS scrubbing (Shield, Cloudflare)","UDP is abused for amplification (DNS, NTP, memcached) because source IPs can be spoofed","QUIC/HTTP3 runs over UDP with its own handshake"],
 f:"Why does UDP make reflection attacks easier?"},
{c:"Networking",q:"Explain DNS record types and the main DNS attacks.",
 a:"A/AAAA map names to IPs, CNAME aliases, MX mail, TXT holds SPF/DKIM/DMARC and verification, NS delegates, PTR is reverse lookup, CAA limits which CAs may issue. Key attacks are cache poisoning, hijacking at the registrar, DNS tunnelling for exfiltration, and subdomain takeover through dangling CNAMEs.",
 p:["DNS uses UDP 53, TCP 53 for large responses and zone transfers","Subdomain takeover: CNAME points to a deprovisioned S3 bucket or Heroku app the attacker can claim","Defences: DNSSEC, registrar lock, monitoring dangling records, CAA"],
 f:"How would you find dangling DNS records across 2,000 subdomains?"},
{c:"Networking",q:"Firewall vs WAF vs IDS/IPS?",
 a:"A firewall filters on network attributes (IP, port, protocol), statefully or not. A WAF inspects HTTP at layer 7 for attack patterns. An IDS detects and alerts; an IPS sits inline and blocks. They are complementary layers.",
 p:["Security groups are stateful; NACLs are stateless","WAF cannot fix authorization bugs such as IDOR","Signature vs anomaly-based detection trade-offs: precision vs novel attacks"],
 f:"A team wants to fix an IDOR with a WAF rule. What do you say?"},
{c:"Networking",q:"What is ARP spoofing and how do you defend against it?",
 a:"ARP maps IPs to MAC addresses on a LAN and has no authentication, so an attacker can send forged replies and put themselves between a victim and the gateway.",
 p:["Defences: dynamic ARP inspection, port security, static entries for critical hosts","Real protection is end-to-end encryption (TLS, SSH) so a MITM sees nothing useful","CAM table overflow forces a switch to flood traffic like a hub"],
 f:"Why is this mostly irrelevant inside a cloud VPC?"},
{c:"Networking",q:"Does NAT provide security?",
 a:"Only incidentally. NAT hides internal addresses and drops unsolicited inbound traffic, but it is not an access control. Outbound connections, reverse shells and IPv6 bypass it.",
 p:["Use real firewalls and egress control","In AWS, a NAT gateway gives private subnets internet egress; restrict it with Network Firewall or proxies"],
 f:"How would you restrict egress from private subnets?"},
{c:"Networking",q:"Walk through the OSI model and name an attack at each layer.",
 a:"Physical (tapping, jamming), Data link (ARP spoofing, MAC flooding), Network (IP spoofing, ICMP floods), Transport (SYN floods, port scans), Session (session hijacking), Presentation (TLS downgrade, encoding tricks), Application (SQLi, XSS, SSRF).",
 p:["In practice people use the TCP/IP model; know both","Most AppSec work is layer 7, but cloud network controls work at 3 and 4"],
 f:"Where does TLS sit, and why is that debated?"},

// ---------------- Web
{c:"Web",q:"Explain the Same-Origin Policy and CORS. When is a CORS misconfiguration exploitable?",
 a:"SOP stops script from one origin (scheme, host, port) reading responses from another. CORS lets a server relax that with Access-Control-Allow-Origin. It is exploitable when the server reflects an arbitrary or attacker-controllable Origin and also sends Access-Control-Allow-Credentials: true, so an attacker page can read authenticated responses.",
 p:["Wildcard * cannot be combined with credentials, so developers reflect the Origin instead, which is the bug","Weak regex (endsWith example.com matches evil-example.com), allowing null origin (sandboxed iframes)","CORS is not CSRF protection: simple requests are still sent","Fix: exact allow-list, no credentials unless needed, Vary: Origin"],
 f:"Does a CORS misconfiguration matter if the API uses Bearer tokens in a header?"},
{c:"Web",q:"Explain the three types of XSS and how you prevent them at scale.",
 a:"Reflected (payload in the request, echoed back), stored (saved and shown to others), and DOM-based (client-side JS writes untrusted data into a dangerous sink). Prevention is context-aware output encoding by default in the framework, avoiding dangerous sinks, and a strict CSP as defence in depth.",
 p:["React/Angular escape by default; risk is dangerouslySetInnerHTML, innerHTML, href=javascript:, template bypasses","Nonce- or hash-based CSP with strict-dynamic; avoid unsafe-inline","Trusted Types to lock DOM sinks; HttpOnly cookies limit token theft but not actions","Sanitise HTML with DOMPurify when rich text is required"],
 f:"Why doesn't HttpOnly stop XSS from being dangerous?"},
{c:"Web",q:"How does CSRF work, what are its prerequisites, and how do you prevent it?",
 a:"The browser automatically attaches cookies, so a malicious site can make the victim's browser send a state-changing request. It needs cookie-based auth, a state-changing action, and no unpredictable parameter. Defences are SameSite cookies, anti-CSRF tokens, and checking the Origin header.",
 p:["SameSite=Lax is the browser default for cookies without the attribute in Chromium, but not universally","JSON APIs are safe only if they reject text/plain and form encodings and require custom headers","Bearer tokens in Authorization headers are not sent automatically, so CSRF does not apply","Bypasses: token not tied to session, method override, Lax allows top-level GET"],
 f:"The API uses JSON. Is it immune to CSRF?"},
{c:"Web",q:"Types of SQL injection and the real fix?",
 a:"In-band (union-based and error-based), blind (boolean and time-based), and out-of-band (DNS or HTTP callback). The fix is parameterised queries or safe ORM use so data can never change the query structure. Validation and WAFs are only extra layers.",
 p:["Second-order SQLi: stored input later concatenated into a query","Dynamic identifiers (ORDER BY column) cannot be parameterised; use an allow-list","Least-privilege DB user limits impact","sqlmap for testing; Semgrep or CodeQL to find concatenation"],
 f:"How do you safely let users choose the sort column?"},
{c:"Web",q:"Explain SSRF, its impact in the cloud, and how you defend against it.",
 a:"SSRF makes the server send requests to a destination the attacker picks. In the cloud the classic impact is reading the instance metadata service to steal IAM credentials, then pivoting into internal services.",
 p:["Bypasses: redirects, DNS rebinding, decimal or IPv6 IP encodings, alternate schemes like gopher or file","Defence: allow-list destinations; resolve the hostname, validate the IP and connect to that IP; block private ranges and link-local","Route outbound fetches through an egress proxy; enforce IMDSv2 with hop limit 1","Least privilege on the instance role limits the blast radius"],
 f:"Why does checking the URL string before fetching not work?"},
{c:"Web",q:"Why do scanners miss IDOR/BOLA, and how do you prevent it across many teams?",
 a:"The request is syntactically valid; the bug is a missing ownership check, and the tool doesn't know who should own what. Prevention is architectural: a central authorization layer, tenant and user IDs taken from the verified token, and automated two-user tests.",
 p:["Unguessable IDs (UUIDs) reduce enumeration but are not authorization","Return 404 for both not-found and not-yours","Policy engines (OPA, Cedar) or a shared authZ library; deny by default","Bug bounty data usually shows authZ as the top category"],
 f:"How would you find every endpoint missing an ownership check in a large codebase?"},
{c:"Web",q:"What is insecure deserialisation and how do you fix it?",
 a:"Deserialising attacker-controlled data with a native format (Java ObjectInputStream, Python pickle, .NET BinaryFormatter, PHP unserialize) can instantiate classes whose methods chain into code execution (gadget chains).",
 p:["Fix: don't deserialise untrusted native objects; use JSON with strict schemas","If unavoidable: class allow-lists (ObjectInputFilter), signing data","Jackson polymorphic typing and YAML loaders (yaml.load vs safe_load) are common variants"],
 f:"What makes a gadget chain possible even if your own code is safe?"},
{c:"Web",q:"Explain XXE and its prevention.",
 a:"XML External Entity injection abuses parsers that resolve external entities, letting an attacker read local files, perform SSRF or cause denial of service (billion laughs).",
 p:["Fix: disable DTDs and external entities in the parser configuration","Older Java DocumentBuilderFactory and many libraries are unsafe by default","Watch indirect XML: SVG, DOCX, SAML, SOAP"],
 f:"Where might XML appear in an app that 'doesn't use XML'?"},
{c:"Web",q:"What is server-side template injection (SSTI)?",
 a:"User input is placed into the template source rather than passed as data, so the template engine evaluates it, often leading to RCE. Example: render_template_string('Hello ' + name) in Flask/Jinja2.",
 p:["Test with {{7*7}} and engine-specific payloads","Fix: never build templates from user input; pass data as variables; sandboxed engines for user-authored templates"],
 f:"How does this differ from XSS?"},
{c:"Web",q:"Explain race conditions in web apps with an example and the fix.",
 a:"Two requests interleave between a check and an update (TOCTOU). Example: redeeming a single-use coupon from 20 parallel requests, each seeing it as unused before any marks it used.",
 p:["Fix: atomic database operations (UPDATE ... WHERE used = false), row locks, unique constraints, idempotency keys","Test with parallel requests (Burp single-packet attack)","Common in payments, gift cards, likes, limits and invitations"],
 f:"How would you fix it in a distributed system with multiple instances?"},
{c:"Web",q:"Which security headers matter and why?",
 a:"Strict-Transport-Security (forces HTTPS), Content-Security-Policy (limits script sources), X-Content-Type-Options: nosniff, frame-ancestors or X-Frame-Options (clickjacking), Referrer-Policy, and secure cookie attributes. Permissions-Policy limits browser features.",
 p:["Missing headers on a static marketing page is usually informational","X-XSS-Protection is obsolete","Set them centrally at the edge or framework, not per endpoint"],
 f:"A bug bounty report says X-Frame-Options is missing. How do you triage it?"},
{c:"Web",q:"How do you secure file uploads?",
 a:"Validate type by content and extension against an allow-list, limit size, rename files, store outside the web root (for example private S3), serve from a separate domain with Content-Disposition: attachment, and scan for malware.",
 p:["SVG and HTML uploads cause stored XSS if served inline on your origin","Image libraries are attack surface: process in a sandbox and keep them patched","Zip slip, decompression bombs, polyglot files","Pre-signed URLs with short expiry"],
 f:"Why serve user content from a separate domain?"},
{c:"Web",q:"What are the main GraphQL security issues?",
 a:"Authorization must be enforced per resolver and field, not only at the endpoint. Other issues: introspection exposing the schema, deep or recursive queries and batching causing DoS or brute-force bypass, and verbose errors.",
 p:["Query depth and cost limits, persisted queries","Disable introspection in production (it is not a security boundary, though)","Rate limit by query cost, not request count"],
 f:"How can batching bypass login rate limits?"},
{c:"Web",q:"Explain HTTP request smuggling at a high level.",
 a:"The front-end proxy and back-end server disagree on where one request ends (Content-Length vs Transfer-Encoding), so an attacker can prepend content to the next user's request.",
 p:["Variants: CL.TE, TE.CL, TE.TE, HTTP/2 downgrade","Impact: bypass front-end controls, hijack other users' requests, cache poisoning","Fix: consistent parsing, HTTP/2 end to end, reject ambiguous requests (ALB desync mitigation)"],
 f:"Why does this mostly matter at the load balancer layer?"},
{c:"Web",q:"What changed in the OWASP Top 10 recently, and how do you use it?",
 a:"The 2021 list put Broken Access Control first and added Insecure Design, Software and Data Integrity Failures and SSRF. The 2025 edition puts more weight on the software supply chain and on mishandling exceptional conditions. Check the final published list before your interview. It is an awareness document, not a standard to test against.",
 p:["For requirements and testing use OWASP ASVS","Also know the OWASP API Security Top 10 and the LLM Top 10","Use it to explain classes, and map your findings to CWE"],
 f:"Pick one category and explain how you'd eliminate it company-wide."},

// ---------------- Auth
{c:"AuthN & AuthZ",q:"OAuth 2.0 vs OpenID Connect vs SAML?",
 a:"OAuth 2.0 is delegated authorization: it issues access tokens to call APIs. OIDC adds authentication on top of OAuth with an ID token (a JWT about the user). SAML is an older XML-based standard for browser SSO, common with enterprise IdPs.",
 p:["Use OIDC for login, OAuth access tokens for APIs, SAML when an enterprise requires it","An access token should not be used as proof of identity in a different app","SAML assertions are signed XML, which makes XML Signature Wrapping attacks possible"],
 f:"Why is using an OAuth access token for login dangerous?"},
{c:"AuthN & AuthZ",q:"Walk through the authorization code flow with PKCE.",
 a:"The client creates a random code_verifier and sends its SHA-256 hash (code_challenge) with the authorization request. After the user signs in, the IdP redirects back with a short-lived code. The client exchanges the code plus the verifier for tokens. PKCE stops someone who intercepts the code from redeeming it.",
 p:["Validate state to stop login CSRF; exact-match redirect URIs","PKCE is now recommended for all clients; the implicit flow is deprecated","Refresh tokens: rotate and detect reuse"],
 f:"What attack does the state parameter prevent?"},
{c:"AuthN & AuthZ",q:"What are the common JWT attacks and how do you validate a JWT correctly?",
 a:"Attacks: alg:none, RS256-to-HS256 key confusion, missing signature verification, weak HMAC secrets, kid or jku injection, and accepting tokens meant for another audience. Validate the signature with a pinned algorithm and verify exp, nbf, iss and aud on every request.",
 p:["Use asymmetric keys from the IdP's JWKS; services verify but cannot mint tokens","JWTs are encoded, not encrypted: no sensitive data in the payload","Revocation: short lifetimes, refresh token revocation, jti deny-list"],
 f:"How do you revoke a JWT before it expires?"},
{c:"AuthN & AuthZ",q:"Where should a single-page app store tokens?",
 a:"Ideally not in the browser at all: a backend-for-frontend holds the tokens and gives the browser an HttpOnly, Secure, SameSite session cookie. If tokens must be in the browser, keep a short-lived access token in memory and the refresh token in an HttpOnly cookie. Avoid localStorage because any XSS can read it.",
 p:["HttpOnly stops theft but not actions performed by XSS while the page is open","__Host- cookie prefix stops subdomains from overwriting the cookie","Mobile: Keychain or Keystore"],
 f:"What does the BFF pattern cost you?"},
{c:"AuthN & AuthZ",q:"What makes session management secure?",
 a:"Random session IDs from a CSPRNG (128+ bits), regenerated at login and privilege change, stored server side, sent in secure cookies, with idle and absolute timeouts and real server-side logout.",
 p:["Session fixation: the attacker sets a known ID before login; regenerating at login fixes it","Bind sensitive actions to re-authentication (step-up)","Show active sessions and allow 'log out everywhere'"],
 f:"How is session fixation different from session hijacking?"},
{c:"AuthN & AuthZ",q:"How should passwords be stored?",
 a:"With a slow, salted, memory-hard password hashing function: Argon2id preferred, or bcrypt or scrypt. Never plain hashes like SHA-256, and never reversible encryption.",
 p:["Salt per user defeats rainbow tables; a pepper in a KMS or HSM adds protection if the database leaks","Tune cost so hashing takes a measurable time on your hardware","Check new passwords against breached-password lists; don't force periodic rotation (NIST 800-63B)"],
 f:"Why is a fast hash bad for passwords but fine for file integrity?"},
{c:"AuthN & AuthZ",q:"Compare MFA methods. Why are passkeys phishing-resistant?",
 a:"SMS is weakest (SIM swap, interception), then TOTP apps, then push (vulnerable to fatigue attacks unless number-matched), then FIDO2/WebAuthn security keys and passkeys. Passkeys are phishing-resistant because the browser binds the signature to the real origin, so a look-alike site gets nothing usable.",
 p:["Account recovery is often the weakest link","Push fatigue was used in real breaches; use number matching","Enforce phishing-resistant MFA for admins and production access"],
 f:"An attacker has an adversary-in-the-middle phishing proxy. Which MFA still stops them?"},
{c:"AuthN & AuthZ",q:"RBAC vs ABAC vs ReBAC — and how do you design multi-tenant authorization?",
 a:"RBAC grants permissions by role; ABAC decides on attributes of user, resource and context; ReBAC decides on relationships (Google Zanzibar style). For multi-tenancy the tenant comes only from the verified token, every query is scoped by tenant, and a central policy layer enforces it with a database-level backstop.",
 p:["Policy engines: OPA, Cedar, OpenFGA/SpiceDB for ReBAC","Backstops: PostgreSQL row-level security, DynamoDB LeadingKeys","Test with two tenants in CI"],
 f:"Where would you enforce tenant isolation in a microservices system?"},
{c:"AuthN & AuthZ",q:"Design a secure password reset flow.",
 a:"Generate a single-use, high-entropy random token, store only its hash with a short expiry, email a link, require it to be used once, invalidate other sessions after reset, and respond identically whether or not the email exists.",
 p:["Never derive tokens from time or user ID","Host header injection can poison reset links: build URLs from config, not the request","Rate limit and notify the user of the change"],
 f:"What is host header poisoning in this context?"},
{c:"AuthN & AuthZ",q:"How do services authenticate to each other?",
 a:"With a workload identity rather than a network location: mTLS with certificates per service (often via a service mesh and SPIFFE IDs), or signed short-lived tokens, or cloud IAM (SigV4, VPC Lattice). Each service then authorizes both the calling service and the end user it acts for.",
 p:["Propagate the user context with token exchange or a gateway-signed internal token","Never trust a user ID in a plain header from 'inside'","Rotate certificates automatically"],
 f:"How do you prevent a compromised service from impersonating users to others?"},
{c:"AuthN & AuthZ",q:"What are the classic SAML attacks?",
 a:"XML Signature Wrapping (the signed element is moved and an unsigned malicious one is processed), comment injection in NameID that truncates the username, accepting unsigned assertions, and missing audience, recipient or expiry checks.",
 p:["Use well-maintained SAML libraries and validate exactly which element is signed","Replay protection with assertion IDs"],
 f:"Why is SAML easier to get wrong than OIDC?"},
{c:"AuthN & AuthZ",q:"Explain Kerberos at a high level and pass-the-hash.",
 a:"Kerberos authenticates with tickets: the client gets a ticket-granting ticket from the KDC, then service tickets, without sending passwords over the network. Pass-the-hash uses a stolen NTLM hash directly instead of the password; Kerberoasting cracks service-account tickets offline; golden tickets forge TGTs using the krbtgt key.",
 p:["Mitigations: strong service-account passwords or gMSA, tiered admin model, LAPS, Credential Guard","Mostly asked for breadth in AppSec loops"],
 f:"Why are service accounts with SPNs a target?"},

// ---------------- Crypto
{c:"Cryptography",q:"Encoding vs hashing vs encryption vs signing vs obfuscation?",
 a:"Encoding changes representation with no secret (Base64). Hashing is one-way and fixed-length (SHA-256). Encryption is reversible with a key and provides confidentiality. Signing proves who created data and that it wasn't changed. Obfuscation only makes things harder to read.",
 p:["JWT payloads are Base64url-encoded, not encrypted","MAC = symmetric integrity; signature = asymmetric integrity plus non-repudiation"],
 f:"Which of these gives integrity, and which gives confidentiality?"},
{c:"Cryptography",q:"Symmetric vs asymmetric encryption, and how they are used together.",
 a:"Symmetric uses one shared key and is fast (AES, ChaCha20). Asymmetric uses a key pair and solves key distribution but is slow (RSA, ECC). Real systems combine them: asymmetric to agree or exchange a key, symmetric to encrypt the data (TLS, envelope encryption).",
 p:["Key sizes: AES-256, RSA 3072+, P-256/Ed25519","Post-quantum: ML-KEM for key exchange is being rolled out in TLS"],
 f:"Why don't we encrypt bulk data with RSA?"},
{c:"Cryptography",q:"Walk through the TLS 1.3 handshake and what changed from 1.2.",
 a:"The client sends ClientHello with supported ciphers and key shares; the server replies with ServerHello and its key share, then encrypted certificate, CertificateVerify and Finished. Keys come from ephemeral (EC)DHE, so it is one round trip with forward secrecy always on.",
 p:["Removed: RSA key exchange, static DH, CBC, RC4, SHA-1, renegotiation, compression","Encrypted certificate; 0-RTT resumption risks replay","Downgrade protection with a sentinel value in ServerHello.random"],
 f:"What is the replay risk of 0-RTT and how do you limit it?"},
{c:"Cryptography",q:"What is forward secrecy and why does it matter?",
 a:"Each session uses ephemeral keys, so stealing the server's long-term private key later does not decrypt past recorded traffic.",
 p:["Achieved with ephemeral Diffie-Hellman (DHE/ECDHE)","TLS 1.3 makes it mandatory"],
 f:"What happens to recorded TLS 1.2 RSA-key-exchange traffic if the key leaks?"},
{c:"Cryptography",q:"Block cipher modes: ECB, CBC, GCM — what goes wrong with each?",
 a:"ECB encrypts identical blocks identically and leaks patterns. CBC needs a random IV and, without integrity, is open to padding-oracle attacks. GCM gives confidentiality and integrity (AEAD) but reusing a nonce with the same key is catastrophic.",
 p:["Prefer AEAD: AES-GCM or ChaCha20-Poly1305","Use libraries (Tink, libsodium) that handle nonces for you"],
 f:"Why is nonce reuse in GCM so bad?"},
{c:"Cryptography",q:"Why use HMAC instead of hash(secret + message)?",
 a:"Many hashes (SHA-256, SHA-1, MD5) are vulnerable to length-extension attacks, so an attacker can append data and compute a valid hash without the secret. HMAC's nested construction prevents this.",
 p:["Compare MACs in constant time to avoid timing attacks","Webhook signatures are usually HMAC-SHA256 with a timestamp"],
 f:"How would you design a webhook signature scheme?"},
{c:"Cryptography",q:"How does Diffie-Hellman work, and what does it not protect against?",
 a:"Two parties combine their private values with each other's public values to derive the same shared secret, without ever sending it. On its own it is unauthenticated, so a man-in-the-middle can run two exchanges. Certificates or signatures authenticate it.",
 p:["Elliptic-curve DH (ECDH, X25519) is the common form today"],
 f:"How does TLS stop a MITM during the DH exchange?"},
{c:"Cryptography",q:"How is a certificate validated, and should a mobile app pin certificates?",
 a:"The client builds a chain to a trusted root, checks signatures, validity dates, hostname (SAN), key usage and revocation. Certificate Transparency logs make mis-issuance visible. Pinning adds protection against rogue CAs but can break the app during rotations; pin to public keys with backups, or rely on CT and platform defaults.",
 p:["DigiNotar is the classic CA compromise example","HPKP was deprecated in browsers because of lockout risk"],
 f:"How do you rotate a pinned key without bricking old app versions?"},
{c:"Cryptography",q:"Explain envelope encryption and key rotation with KMS.",
 a:"Data is encrypted with a data key; the data key is encrypted by a master key in KMS. You store the encrypted data key next to the data. Rotating the master key doesn't require re-encrypting all data, and access to decrypt is controlled by KMS key policies and logged.",
 p:["Separate key administrators from key users","Rotate certificates without downtime: overlap old and new, deploy new first, then revoke old"],
 f:"How would you rotate a TLS certificate across 200 services without downtime?"},
{c:"Cryptography",q:"Why must security tokens use a CSPRNG?",
 a:"General random functions (Math.random, Python's random) are predictable from observed output. Security tokens, session IDs and keys must come from a cryptographically secure source (crypto.randomBytes, secrets module, SecureRandom).",
 p:["Low entropy at boot on VMs and containers was a historical issue","Never derive tokens from timestamps or user IDs"],
 f:"What would you look for in code that generates reset tokens?"},

// ---------------- Cloud
{c:"Cloud",q:"Explain the shared responsibility model.",
 a:"The cloud provider secures the infrastructure (hardware, hypervisor, physical facilities); the customer secures what they put in it: identity, configuration, data, network rules and application code. The split moves with the service type: more on you with EC2, less with Lambda or SaaS.",
 p:["Most cloud breaches are customer-side misconfiguration or identity issues"],
 f:"Who patches the OS for Lambda vs EC2?"},
{c:"Cloud",q:"How does AWS evaluate an IAM request?",
 a:"Everything is denied by default. An explicit Deny anywhere wins. Otherwise the request must be allowed by every applicable layer: SCPs and RCPs, permission boundaries and session policies must permit it, and an identity or resource policy must grant it.",
 p:["Cross-account: both the caller's identity policy and the resource policy or trust policy must allow it","Use IAM Access Analyzer and the policy simulator to check","Conditions: aws:SourceVpce, aws:PrincipalOrgID, aws:ResourceTag"],
 f:"A cross-account request fails even though the bucket policy allows it. Why?"},
{c:"Cloud",q:"What is the risk of iam:PassRole, and what is the confused-deputy problem?",
 a:"PassRole lets a principal hand a role to a service (EC2, Lambda). Combined with permission to create that resource, a user can run code as a more privileged role: privilege escalation. Confused deputy is when a service is tricked into using its own permissions on behalf of the wrong party.",
 p:["Scope PassRole to specific role ARNs and use iam:PassedToService","For third parties assuming your roles: sts:ExternalId","For AWS services: aws:SourceArn and aws:SourceAccount conditions"],
 f:"Write a condition that stops a Lambda's role being passed to EC2."},
{c:"Cloud",q:"How do you scope down a role with Action * and Resource * without breaking the app?",
 a:"Look at what it actually uses first: CloudTrail history or IAM Access Analyzer policy generation over a representative period. Write a policy with those actions on specific ARNs, test it in staging, deploy it with monitoring for AccessDenied, and keep a quick rollback.",
 p:["Check 'last accessed' data for services","Watch for rare paths: monthly jobs, error handling, DR scripts","Add permission boundaries so teams cannot re-widen it"],
 f:"What if the job only runs once a quarter?"},
{c:"Cloud",q:"How does SSRF lead to cloud compromise, and what does IMDSv2 change?",
 a:"Through SSRF an attacker can request the instance metadata endpoint and receive the role's temporary credentials. IMDSv2 requires a PUT to get a session token and a header on later requests, which most SSRF bugs can't send. A hop limit of 1 stops containers from reaching it.",
 p:["Enforce HttpTokens=required by policy and SCP","GuardDuty detects instance credentials used from outside AWS","Least privilege on the instance role limits damage"],
 f:"GuardDuty fires InstanceCredentialExfiltration. What do you do?"},
{c:"Cloud",q:"How do you prevent S3 data exposure across a large organisation?",
 a:"Turn on account-level Block Public Access and protect it with an SCP, restrict bucket policies to specific roles and VPC endpoints, encrypt with KMS, and detect drift with AWS Config, Access Analyzer and CSPM.",
 p:["Object ownership enforced (ACLs disabled)","Pre-signed URLs for sharing","Macie to find sensitive data"],
 f:"A team needs a public bucket for a website. How do you allow it safely?"},
{c:"Cloud",q:"Why use multiple AWS accounts, and what guardrails go with them?",
 a:"Accounts are the strongest isolation boundary in AWS: separate prod, non-prod, security tooling, logging and sandbox accounts limit blast radius. Guardrails: SCPs, centralised CloudTrail to a locked log-archive account, delegated GuardDuty and Security Hub, and SSO instead of IAM users.",
 p:["Control Tower or a custom landing zone","Example SCPs: deny leaving the org, deny disabling CloudTrail/GuardDuty, region restriction"],
 f:"What SCPs would you put on production accounts?"},
{c:"Cloud",q:"How do you secure service-to-service traffic across multiple accounts and regions?",
 a:"Give each workload an IAM identity, use private connectivity (PrivateLink, VPC Lattice or Transit Gateway) instead of the internet, authenticate with SigV4 or mTLS, restrict resource policies with aws:PrincipalOrgID and specific roles, and log everything centrally.",
 p:["Avoid shared credentials between accounts; use role assumption with conditions","Encrypt in transit even on private links"],
 f:"How would you detect abuse of a cross-account role?"},
{c:"Cloud",q:"How do attackers move laterally and escalate in a cloud account?",
 a:"Steal credentials (metadata service, environment variables, CI secrets), enumerate permissions, then abuse escalation paths: PassRole with compute creation, CreatePolicyVersion, AttachRolePolicy, UpdateAssumeRolePolicy, or Lambda/SSM to run code as other roles.",
 p:["Tools: Pacu, PMapper, Cloudsplaining (in authorised tests)","Detection: GuardDuty, unusual AssumeRole chains, new access keys"],
 f:"Which single permission would you remove first from developer roles?"},
{c:"Cloud",q:"What is zero trust, practically?",
 a:"No implicit trust from network location. Every request is authenticated and authorised using user identity, device posture and context, with least privilege and continuous verification. Google's BeyondCorp replaced the corporate VPN with an identity-aware proxy.",
 p:["Between microservices: mTLS with workload identity, per-call authorization","For employees: SSO, device trust, access proxy"],
 f:"How do you enforce zero trust between two microservices?"},
{c:"Cloud",q:"CloudTrail management vs data events, and how do you protect logs?",
 a:"Management events record control-plane calls (CreateUser, PutBucketPolicy). Data events record data-plane access (S3 GetObject, Lambda Invoke) and cost more, so enable them for sensitive resources. Protect logs with an organisation trail into a separate log-archive account, Object Lock, log file validation and SCPs against tampering.",
 p:["Send to a SIEM; alert on StopLogging, DeleteTrail"],
 f:"How would you prove whether data in a bucket was actually read?"},
{c:"Cloud",q:"CSPM vs CWPP vs CIEM vs CNAPP?",
 a:"CSPM finds cloud misconfigurations; CWPP protects workloads (VMs, containers, serverless) with vulnerability and runtime scanning; CIEM analyses identities and excessive permissions; CNAPP combines them with attack-path analysis (Wiz, Prisma Cloud, Defender for Cloud).",
 p:["Value comes from toxic combinations: public + vulnerable + over-privileged","Route fixes back to IaC so they don't return"],
 f:"How do you stop the CNAPP becoming a list of 20,000 alerts nobody fixes?"},

// ---------------- Containers
{c:"Containers & K8s",q:"How do container escapes happen?",
 a:"Containers share the host kernel, so isolation depends on configuration. Common escapes: privileged containers, mounted docker.sock, hostPath mounts of sensitive paths, dangerous capabilities like CAP_SYS_ADMIN, host PID/network namespaces, and kernel vulnerabilities.",
 p:["Defence: Pod Security Standards (restricted), non-root, read-only rootfs, drop capabilities, seccomp/AppArmor","Stronger isolation: gVisor, Kata, Firecracker for untrusted workloads"],
 f:"Why is mounting docker.sock equivalent to root on the host?"},
{c:"Containers & K8s",q:"What is your Kubernetes security baseline?",
 a:"Private API endpoint with audit logs; RBAC least privilege; per-workload service accounts and cloud identities (IRSA/Pod Identity); Pod Security Standards; default-deny NetworkPolicies; admission control enforcing signed images and policies; secrets encrypted with KMS; runtime monitoring.",
 p:["Block pod access to the node metadata service","Patch nodes; CIS benchmark with kube-bench","Separate namespaces or clusters for different trust levels"],
 f:"A pod is compromised. What can it reach in your design?"},
{c:"Containers & K8s",q:"How are Kubernetes service accounts and RBAC abused?",
 a:"Pods get a service account token; if that account has broad RBAC rights (create pods, read secrets, bind roles), a compromised pod can escalate to cluster admin.",
 p:["Disable token automount where not needed; use bound, short-lived tokens","Dangerous verbs: create pods, escalate, bind, impersonate, get secrets cluster-wide"],
 f:"Which RBAC permission lets you become cluster admin indirectly?"},
{c:"Containers & K8s",q:"How do you secure the container image supply chain?",
 a:"Minimal pinned base images, scan in CI and continuously in the registry, generate an SBOM, sign images, and enforce at admission that only signed images from your registry run.",
 p:["Rebuild regularly to pick up base-image patches","Don't bake secrets into layers"],
 f:"How do you enforce 'only signed images' in EKS?"},
{c:"Containers & K8s",q:"Are Kubernetes Secrets secure?",
 a:"By default they are only Base64-encoded in etcd and readable by anyone with get secrets rights. Enable encryption at rest with a KMS provider, restrict RBAC, or keep secrets in an external manager and mount them through the Secrets Store CSI driver.",
 p:["Avoid putting secrets in environment variables when files are possible","Audit who can read secrets"],
 f:"Why are env-var secrets riskier than mounted files?"},
{c:"Containers & K8s",q:"How does runtime detection work in containers?",
 a:"eBPF or kernel-level sensors watch process, file and network activity and compare it to expected behaviour, for example a Java process spawning a shell or a container writing to /etc. Tools: Falco, KubeArmor, Cilium Tetragon, GuardDuty Runtime Monitoring.",
 p:["KubeArmor can enforce, not just alert, using LSMs","Tune per workload to avoid noise"],
 f:"What would you alert on for a typical web service pod?"},

// ---------------- OS
{c:"OS & Systems",q:"Common Linux privilege escalation paths?",
 a:"Misconfigured sudo rules, SUID binaries, writable cron jobs or scripts run as root, weak file permissions, PATH hijacking, Linux capabilities, kernel exploits, and credentials left in files or history.",
 p:["Tools: linpeas for enumeration","Defence: least privilege, patching, auditing SUID and sudoers"],
 f:"How would you detect someone abusing a SUID binary?"},
{c:"OS & Systems",q:"Explain buffer overflows and the modern mitigations.",
 a:"Writing past a buffer's bounds overwrites adjacent memory such as the return address. Mitigations: stack canaries, DEP/NX (non-executable memory), ASLR, control-flow integrity, and memory-safe languages. Attackers respond with ROP chains and info leaks.",
 p:["CISA and others now push memory-safe languages (Rust, Go)"],
 f:"Why does ASLR need an info leak to bypass?"},
{c:"OS & Systems",q:"DAC vs MAC — what do SELinux and AppArmor add?",
 a:"Discretionary access control lets owners set permissions (Unix rwx). Mandatory access control enforces a system-wide policy that even root processes cannot override. SELinux uses labels; AppArmor uses path-based profiles.",
 p:["Containers use seccomp and AppArmor/SELinux profiles to limit syscalls and files"],
 f:"Why does MAC limit damage from a compromised root process?"},
{c:"OS & Systems",q:"Reverse shell vs bind shell?",
 a:"A bind shell listens on the victim for the attacker to connect; a reverse shell makes the victim connect out to the attacker, which usually passes firewalls that allow outbound traffic.",
 p:["Egress filtering and runtime detection of unexpected outbound connections defeat reverse shells"],
 f:"How would you detect a reverse shell from a container?"},
{c:"OS & Systems",q:"What's in /etc/shadow and /proc, and why do attackers care?",
 a:"/etc/shadow stores password hashes, readable only by root. /proc exposes process information: command lines, environment variables (sometimes with secrets), memory maps and file descriptors.",
 p:["/proc/self/environ via LFI can leak secrets","Never pass secrets on the command line"],
 f:"How could an LFI become credential theft?"},
{c:"OS & Systems",q:"Give a breadth overview of Active Directory attacks.",
 a:"Kerberoasting (crack service tickets), AS-REP roasting, pass-the-hash and pass-the-ticket, DCSync, golden and silver tickets, and abuse of ACL misconfigurations found with BloodHound.",
 p:["Defence: tiered admin, gMSA, LAPS, monitoring for DCSync and anomalous TGS requests"],
 f:"Which detection would you add first?"},

// ---------------- Detection & IR
{c:"Detection & IR",q:"Walk through the incident response lifecycle.",
 a:"Preparation, detection and analysis, containment, eradication, recovery, and post-incident lessons (NIST 800-61; SANS calls it PICERL). Contain early, preserve evidence, communicate on a schedule, and fix the root cause.",
 p:["Assign roles: incident commander, comms, technical leads, scribe","Escalate to legal and privacy when personal data may be involved"],
 f:"What's the difference between a security incident and a privacy incident?"},
{c:"Detection & IR",q:"An account has 400 failed logins, then a success from an unfamiliar country. What do you do?",
 a:"Treat it as a likely account takeover. Contain first: revoke sessions and refresh tokens, force re-authentication and a password reset. Then scope: what the session did, data accessed, other accounts hit from the same IPs. Preserve evidence, then find the root cause (credential stuffing, no MFA, missing rate limits).",
 p:["Check if it's part of a wider stuffing campaign","Add rate limits, breached-password checks, MFA, anomaly alerts","Notify the user and follow notification obligations"],
 f:"How do you tell credential stuffing from targeted brute force?"},
{c:"Detection & IR",q:"An AWS access key is found in a public GitHub repo. Walk through your response.",
 a:"Deactivate the key immediately (and rotate anything else in that repo). Then use CloudTrail to see every action made with that key since it was exposed, look for persistence (new users, keys, roles, Lambdas, EC2), clean up, remove the secret from history, and fix the cause with secret scanning and short-lived credentials.",
 p:["AWS may quarantine the key automatically (AWSCompromisedKeyQuarantine policy)","Attackers often launch crypto-mining in many regions within minutes","Prefer OIDC federation and roles so there is no long-lived key"],
 f:"What persistence would an attacker create in the first five minutes?"},
{c:"Detection & IR",q:"How would you detect DNS exfiltration?",
 a:"Look for unusually long or high-entropy subdomains, high query volume to one domain, many unique subdomains, TXT record use, and queries to newly registered domains. Force DNS through controlled resolvers so you can log and filter it.",
 p:["Route 53 Resolver query logs, Zeek, SIEM analytics","Block direct outbound DNS from workloads"],
 f:"Why is DNS such a common exfiltration channel?"},
{c:"Detection & IR",q:"What should an application log for security, and what must it never log?",
 a:"Log authentication successes and failures, authorization denials, admin and sensitive actions, input validation failures and security-relevant errors, each with user, tenant, IP, request ID and timestamp. Never log passwords, tokens, session IDs, full card numbers or unnecessary PII.",
 p:["Structured JSON logs to a central SIEM","Tamper-resistant storage; time sync"],
 f:"How would you detect an IDOR enumeration from logs?"},
{c:"Detection & IR",q:"IOCs vs behaviour-based detection — what's the Pyramid of Pain?",
 a:"Indicators of compromise (hashes, IPs, domains) are easy for attackers to change. Detecting tactics, techniques and procedures (behaviour) is harder to evade. The Pyramid of Pain ranks indicators from trivial (hashes) to tough (TTPs).",
 p:["Map detections to MITRE ATT&CK to see coverage gaps"],
 f:"Give a behaviour-based detection for cloud credential theft."},
{c:"Detection & IR",q:"How do you use MITRE ATT&CK?",
 a:"As a shared vocabulary of attacker tactics and techniques: to map detection coverage, plan purple-team tests, structure threat intelligence, and describe incidents. Tactics run from reconnaissance and initial access through persistence, privilege escalation and lateral movement to exfiltration and impact.",
 p:["Cloud and container matrices exist","Don't chase 100% coverage; prioritise by threat relevance"],
 f:"Which ATT&CK techniques matter most for a SaaS company?"},
{c:"Detection & IR",q:"What is the order of volatility in forensics, and why does chain of custody matter?",
 a:"Collect the most volatile evidence first: CPU registers and cache, memory, network state and running processes, temporary files, disk, then remote logs and backups. Chain of custody documents who handled evidence and when, so it stays trustworthy for legal use.",
 p:["In the cloud: snapshot volumes, capture memory before terminating, isolate rather than delete"],
 f:"A compromised EC2 instance: terminate it or isolate it?"},
{c:"Detection & IR",q:"What are canary tokens / honeytokens and why are they useful?",
 a:"Fake credentials, documents or records that no legitimate process should touch. Any use is a high-confidence alert, which is rare in detection.",
 p:["Example: fake AWS key in a config repo; fake admin user in the DB"],
 f:"Where would you place three honeytokens in a SaaS company?"},

// ---------------- Threat modeling
{c:"Threat modeling",q:"Describe your threat modeling process.",
 a:"Four questions: what are we building, what can go wrong, what will we do about it, did we do a good job. I draw a data flow diagram with trust boundaries, apply STRIDE to each element and boundary-crossing flow, rank threats by likelihood and impact, and turn the top ones into tickets with owners and tests.",
 p:["Draw trust boundaries first; threats follow from them","Rank and say which two to fix first","Revisit when the design changes"],
 f:"What do you do when the team says they don't have time for this?"},
{c:"Threat modeling",q:"STRIDE vs PASTA vs DREAD?",
 a:"STRIDE is a coverage checklist of threat types; fast and developer-friendly. PASTA is a seven-stage, business-risk-driven process for high-value systems. DREAD is a scoring model, now rarely used because its scores are subjective.",
 p:["LINDDUN for privacy; attack trees for one high-value goal","MITRE ATT&CK for attacker behaviour"],
 f:"Which would you use in a two-week sprint?"},
{c:"Threat modeling",q:"Threat model a profile picture upload feature (short version).",
 a:"Flows: browser to API, API to storage, storage to CDN, image processing worker. Top threats: stored XSS via SVG or HTML served inline, a public or guessable bucket exposing other users' images, malicious files exploiting the image library, decompression bombs and oversized files, and EXIF metadata leaking location.",
 p:["Fix first: serve from a separate domain with Content-Disposition and re-encode images; private bucket with signed URLs","Sandbox processing and patch the library; size limits and rate limits; strip metadata"],
 f:"What if the image library itself has a vulnerability?"},
{c:"Threat modeling",q:"How do you scale threat modeling across 50 teams?",
 a:"Tier the work: a short questionnaire decides which designs need a full review. Provide templates and a library of pre-modeled patterns, train security champions to run lightweight STRIDE sessions, and track coverage of high-risk features as a metric.",
 p:["Automate parts: generate DFDs from IaC or architecture docs","Use LLMs to draft threat lists, with expert review"],
 f:"How do you know threat modeling is actually reducing bugs?"},
{c:"Threat modeling",q:"Threat model an LLM agent that can issue refunds.",
 a:"Assets: customer data, refund ability, system prompt, tool credentials. Key threats: direct and indirect prompt injection (malicious text in tickets or emails), excessive agency issuing refunds, data leaking across customers through retrieval, and model output rendered unsafely.",
 p:["Controls: tool permissions scoped per user, hard limits and human approval for refunds above a threshold","Per-tenant retrieval filters; treat model output as untrusted","Log prompts and tool calls; evaluate with red-team prompts"],
 f:"The system prompt says 'never refund more than $100'. Is that a control?"},
{c:"Threat modeling",q:"When do you threat model, and what triggers a new review?",
 a:"At design time for high-risk features, before code exists. Triggers: a new internet-facing endpoint, a new authentication or authorization flow, a new data type such as payments or health data, a new third-party integration, or a major architecture change.",
 p:["Keep models next to code and update them in the same PR as design changes"],
 f:"How do you catch designs that never came to you?"},

// ---------------- SDLC & tooling
{c:"SDLC & Tooling",q:"SAST vs DAST vs IAST vs SCA vs RASP?",
 a:"SAST analyses source code early but is noisy and blind to business logic. DAST attacks the running app but misses unreached code. IAST instruments the app during tests for accurate findings. SCA finds known-vulnerable dependencies. RASP blocks attacks inside the running app.",
 p:["None reliably find IDOR or business logic flaws","Combine with threat modeling and manual review"],
 f:"Which would you implement first in a company with nothing?"},
{c:"SDLC & Tooling",q:"Developers ignore the SAST tool because it's noisy. What do you do?",
 a:"Tune before enforcing: disable low-value rules, mark false positives centrally, scan only changed code, and block only new high-confidence criticals. Add custom rules from real bugs. Measure false-positive rate and time to fix.",
 p:["Every blocking finding must be real, or trust is gone","Show findings in the PR, not a separate portal"],
 f:"How do you measure whether tuning worked?"},
{c:"SDLC & Tooling",q:"Design a secure CI/CD pipeline.",
 a:"Pre-commit secret scanning; on PR, SAST, SCA and IaC scans with results as comments; at build, container scanning, SBOM and signing; DAST in staging; admission control verifying signatures at deploy; and runtime monitoring in production.",
 p:["Secure the pipeline itself: OIDC to cloud, pinned actions, protected branches, no secrets in untrusted PR builds","Only the pipeline can deploy to production"],
 f:"Why is pull_request_target dangerous in GitHub Actions?"},
{c:"SDLC & Tooling",q:"How do you validate a SAST finding manually?",
 a:"Trace it: is the source really user-controlled, does the data reach the sink, is there sanitisation or framework protection in between, and is the code reachable in production? Then confirm exploitability safely if needed, and record the reasoning either way.",
 p:["False positive: mark with a reason so it doesn't return","True positive: give the exact fix and a test"],
 f:"Walk me through it for a SQL injection finding."},
{c:"SDLC & Tooling",q:"What is reachability analysis in SCA?",
 a:"Checking whether your code actually calls the vulnerable function in a dependency, under the conditions that trigger the bug, with attacker-controlled input. It turns thousands of CVE alerts into the few that matter.",
 p:["Check: loaded at runtime, called directly or via a framework, input reachable, trigger conditions met","Tools: Snyk, Endor Labs, Semgrep Supply Chain","If you can't prove unreachable, treat it as reachable"],
 f:"Why can static reachability give false negatives?"},
{c:"SDLC & Tooling",q:"A critical CVE with no patch affects 40 services. What do you do?",
 a:"Find every affected service using the SBOM, assess reachability and exposure, then contain: disable the vulnerable feature, add a WAF virtual patch, restrict egress and permissions. Hunt logs for exploitation, brief stakeholders, record a time-bound risk acceptance, and upgrade everywhere when the fix ships.",
 p:["Prioritise with EPSS and CISA KEV","Log4Shell is the reference example"],
 f:"How do you know you found every affected service?"},
{c:"SDLC & Tooling",q:"How do you measure an AppSec programme?",
 a:"Mean time to remediate by severity and SLA adherence; trend of open critical and high findings; coverage (repos scanned, high-risk features threat modeled); escape rate (bugs found in production or bug bounty versus before release); and adoption of paved roads.",
 p:["Different dashboards for executives and teams","Prefer metrics that change decisions over raw vulnerability counts"],
 f:"Which single metric would you show the CEO?"},
{c:"SDLC & Tooling",q:"How would you build a security champions programme?",
 a:"Recruit one volunteer per team with manager support and time allocated, train them, give them a clear role (first-line reviews, threat model facilitation, triage), meet regularly, and recognise their work.",
 p:["Measure: champion coverage, reviews done, findings fixed in their teams","Give them early access to tools and direct contact with security"],
 f:"How do you keep champions engaged after six months?"},
{c:"SDLC & Tooling",q:"How do you roll out a new security tool across 500 repositories?",
 a:"Pilot with friendly teams, tune rules, integrate into PRs and ticketing, roll out in report-only mode, then enforce a small set of blocking rules. Support teams with docs and office hours, and track adoption and noise.",
 p:["Define success criteria before the proof of concept","Avoid running two tools that do the same thing"],
 f:"How do you decide between building and buying?"},

// ---------------- Supply chain
{c:"Supply chain",q:"What are SBOM and VEX and why do they matter?",
 a:"An SBOM lists every component in a build (CycloneDX or SPDX). VEX states whether a known vulnerability actually affects the product. Together they let you answer 'are we affected?' in minutes when a new CVE appears.",
 p:["Generate per build and store with the artefact","Customers and regulators increasingly ask for SBOMs"],
 f:"How did SBOMs help (or would have helped) during Log4Shell?"},
{c:"Supply chain",q:"What is dependency confusion?",
 a:"An attacker publishes a public package with the same name as an internal one and a higher version, and the build tool pulls the public one.",
 p:["Fix: scoped package names, private registry with upstream rules, pinned versions and lockfiles","Related: typosquatting and malicious maintainers"],
 f:"How would you check if your org is exposed?"},
{c:"Supply chain",q:"What is SLSA and how does signing fit in?",
 a:"SLSA is a framework of levels for build integrity: scripted builds, provenance, hardened isolated build platforms. Signing (Sigstore cosign) plus provenance lets you verify an artefact was built from the expected source by the expected pipeline.",
 p:["Verify signatures at deploy (admission control)"],
 f:"What does provenance protect against that scanning doesn't?"},
{c:"Supply chain",q:"How do you secure GitHub Actions?",
 a:"Use OIDC to the cloud instead of stored keys, pin third-party actions to commit SHAs, set minimal GITHUB_TOKEN permissions, avoid running untrusted PR code with secrets (pull_request_target pitfalls), protect workflow files with CODEOWNERS, and use ephemeral runners.",
 p:["Script injection via ${{ github.event.issue.title }} in run steps","Self-hosted runners on public repos are dangerous"],
 f:"How does script injection in a workflow work?"},
{c:"Supply chain",q:"What did the xz utils backdoor teach the industry?",
 a:"In 2024 a long-running social-engineering campaign got a malicious maintainer into xz and hid a backdoor targeting SSH (CVE-2024-3094). It was caught by chance. Lessons: maintainer trust is an attack surface, release tarballs can differ from the repository, and critical open-source projects need support and review.",
 p:["Also know SolarWinds (build system compromise) and Log4Shell (ubiquitous dependency)"],
 f:"What controls would have helped you detect it?"},

// ---------------- Mobile
{c:"Mobile",q:"What is your mobile application testing methodology?",
 a:"Static: decompile (jadx, apktool, class-dump), review the manifest or plist, hard-coded secrets, exported components, deep links. Dynamic: proxy traffic with Burp, bypass pinning with Frida or objection, test local storage, WebViews and IPC. Then test the backend API like any other API.",
 p:["Map findings to OWASP MASVS","The API is usually where the real impact is"],
 f:"How do you bypass certificate pinning in a test?"},
{c:"Mobile",q:"How should secrets and tokens be stored on mobile?",
 a:"In the iOS Keychain and in Android Keystore-backed storage (EncryptedSharedPreferences). Never in plain SharedPreferences, NSUserDefaults, files or the app binary.",
 p:["API keys in the binary are public; protect the backend instead","Clear sensitive data on logout"],
 f:"An API key is hard-coded in the app. How bad is it?"},
{c:"Mobile",q:"What are the risks of deep links and WebView JavaScript bridges?",
 a:"Deep links can be invoked by any app or website, so unvalidated parameters can open arbitrary URLs in a WebView. If that WebView exposes a JavaScript bridge (addJavascriptInterface), attacker pages can call native functions.",
 p:["Use verified App Links / Universal Links; validate hosts strictly","Disable JavaScript and file access when not needed"],
 f:"Chain a deep link and a WebView bridge into account takeover."},
{c:"Mobile",q:"Should every app use certificate pinning, root detection and app attestation?",
 a:"They raise the cost for attackers but are bypassable on devices the attacker controls. Use them for high-risk apps (banking), combine with server-side attestation (Play Integrity, App Attest), and never rely on them instead of server-side controls.",
 p:["Pinning needs a rotation plan"],
 f:"What does app attestation actually prove?"},

// ---------------- AI
{c:"AI & LLM",q:"Name the key OWASP Top 10 for LLM Applications risks.",
 a:"Prompt injection, sensitive information disclosure, supply chain, data and model poisoning, improper output handling, excessive agency, system prompt leakage, vector and embedding weaknesses, misinformation, and unbounded consumption (2025 version).",
 p:["Most real incidents come from prompt injection combined with excessive agency"],
 f:"Which two would you test first in a customer support bot?"},
{c:"AI & LLM",q:"Direct vs indirect prompt injection, and how do you defend against it?",
 a:"Direct: the user types instructions to override the system prompt. Indirect: malicious instructions hide in content the model reads (web pages, emails, documents, tool results). There is no complete fix, so you limit impact: least-privilege tools, human approval for sensitive actions, separating trusted and untrusted content, and output filtering.",
 p:["Treat every model output as untrusted input to the next system","Don't put secrets in the system prompt"],
 f:"An agent summarises emails and can send email. What can go wrong?"},
{c:"AI & LLM",q:"How do you secure RAG in a multi-tenant product?",
 a:"Enforce authorization at retrieval: filter documents by the user's tenant and permissions before they reach the model, keep per-tenant indexes or metadata filters, and never rely on the model to withhold data.",
 p:["Sanitise ingested documents; watch for poisoned content","Log what was retrieved for each answer"],
 f:"Why can't the system prompt enforce tenant isolation?"},
{c:"AI & LLM",q:"How do you use LLMs in AppSec work responsibly?",
 a:"For triage, drafting threat models, code review assistance and report writing, with a human verifying every finding before it is reported. Keep client or proprietary code within approved tools, and measure false positives.",
 p:["LLMs are good at breadth and summarising, weak at confirming exploitability","Use them to scale, not to replace judgement"],
 f:"How do you stop an LLM from producing confident false findings?"},
{c:"AI & LLM",q:"What are the security risks of MCP servers and agent tools?",
 a:"Tools run with real permissions, so risks include over-broad credentials, tool descriptions or results carrying prompt injection, malicious or compromised servers, and data leaking between tools.",
 p:["Least-privilege tokens per tool, allow-lists of servers, confirmation for destructive actions, logging of tool calls"],
 f:"How would you review a new MCP server a team wants to use?"},

// ---------------- Programme
{c:"Programme",q:"How would you build an AppSec programme from scratch for 500 engineers?",
 a:"First 90 days: inventory apps and data, quick wins (secret scanning, SCA, cloud basics), one intake and SLA process, and threat model the riskiest project. Year one: scanners on all repos with tuned gates, champions, standards, VDP or bug bounty, metrics. After that: paved roads and policy as code that remove bug classes, maturity tracked with SAMM.",
 p:["Earn trust with fast, accurate help before enforcing gates","Tie each step to a risk or a business need (audits, enterprise customers)"],
 f:"What do you NOT do in the first 90 days?"},
{c:"Programme",q:"Everything is 'critical'. How do you prioritise?",
 a:"Re-score with context: exploitability (public exploit, KEV, EPSS), exposure (internet-facing, authentication needed), data and business impact, and existing controls. Fix the few that combine high likelihood and high impact first, and defend the order with data.",
 p:["Interviewers penalise calling everything critical","Offer what makes a launch safe enough to ship"],
 f:"How would you explain the order to an angry engineering director?"},
{c:"Programme",q:"How does a risk acceptance process work?",
 a:"When a finding can't be fixed in its SLA, the owning business leader formally accepts the residual risk, with a description, compensating controls, an expiry date and a review. Security advises; the business owns the decision.",
 p:["Track acceptances as a metric; expired acceptances escalate"],
 f:"Who should be allowed to accept a critical risk?"},
{c:"Programme",q:"How would you set up and run a bug bounty programme?",
 a:"Start with a VDP and safe harbour, then a private bounty with a tight scope and clear rules on a platform, a payout table, and triage SLAs. Make sure internal teams can fix things quickly before inviting more researchers; then expand scope and go public.",
 p:["Bounty data shows what your SDLC misses","Respect researchers: fast responses, fair severity"],
 f:"What should be out of scope?"},
{c:"Programme",q:"What does AppSec contribute to SOC 2, ISO 27001 or PCI DSS?",
 a:"Evidence that secure development controls operate: SDLC policy, threat models, scan results over the audit period, remediation within SLA, pentests and retests, change management and access reviews. For PCI DSS v4.0 also protection of public web apps (6.4.2) and payment page script integrity (6.4.3).",
 p:["Design processes that produce evidence automatically"],
 f:"An auditor asks how you know developers fix vulnerabilities on time. What do you show?"},
{c:"Programme",q:"How do you set vulnerability SLAs?",
 a:"By severity and context, agreed with engineering leadership, achievable for teams and aligned with compliance needs. A common starting point: critical 7 days, high 30, medium 90, low as capacity allows, with tighter targets for internet-facing or KEV-listed issues.",
 p:["Measure adherence, not just MTTR","Have an exception path"],
 f:"Teams miss SLAs constantly. What do you change?"},
{c:"Programme",q:"What are paved roads, and why do senior engineers focus on them?",
 a:"Pre-built secure defaults teams adopt because they are easier than rolling their own: service templates, authorization libraries, hardened base images, golden Terraform modules. They remove whole classes of bugs for every team at once.",
 p:["Measure adoption","Pair with guardrails for teams that leave the road"],
 f:"Give an example of a paved road that kills a vulnerability class."},
{c:"Programme",q:"How do you balance security and delivery speed?",
 a:"Use risk-based gates that only block exploitable, serious issues; automate everything else into tickets; review designs early when changes are cheap; offer secure defaults; and give options instead of a veto. Measure that security is not the bottleneck.",
 p:["Phrase it as 'what makes this safe enough to ship this week'"],
 f:"Tell me about a time you let something ship with a known issue."},

// ---------------- Coding
{c:"Coding",q:"What are the time complexities of common operations, and why do they matter in security tooling?",
 a:"Hash table lookup is O(1) average, list search O(n), sorting O(n log n), binary search O(log n). In log analysis over millions of lines, using a dictionary to count instead of repeated list scans is the difference between seconds and hours.",
 p:["Stream large files line by line with generators instead of loading them into memory"],
 f:"How would you find the top 10 IPs in a 50 GB log file?"},
{c:"Coding",q:"What is ReDoS and how do you avoid it?",
 a:"Regular Expression Denial of Service: patterns with nested quantifiers like (a+)+ can take exponential time on crafted input in backtracking engines.",
 p:["Avoid nested quantifiers; use linear-time engines (RE2); set input length limits and timeouts"],
 f:"Spot the risky part of ^(\\w+\\s?)*$."},
{c:"Coding",q:"How would you write a script to detect brute-force logins in auth logs?",
 a:"Stream the log line by line, parse timestamp, result and IP with a regex, count failures per IP in a time window using a dictionary (or a deque for sliding windows), and output IPs above the threshold, ideally also flagging a success after many failures.",
 p:["Handle malformed lines; make thresholds configurable","Practise this in the Coding lab"],
 f:"How would you change it to detect low-and-slow attacks across many IPs?"},
{c:"Coding",q:"Python generators and comprehensions — why use them in security scripts?",
 a:"Comprehensions build lists and dicts concisely; generators yield items lazily, so you can process huge logs or API pages without loading everything into memory.",
 p:["yield, itertools, and with-open for safe file handling"],
 f:"Write a generator that yields parsed log events."}
];
