// Reference data reused from the Atlas and SaaS map pages
window.PILLARS=[
 {k:"f",name:"Foundations",sub:"how systems break, and the technology you must read fluently"},
 {k:"b",name:"Build-time",sub:"stopping vulnerabilities before release (shift left)"},
 {k:"r",name:"Run-time",sub:"finding and fixing what reached production (shift right)"},
 {k:"p",name:"Programme",sub:"running security as a business function"}
];
window.DOM=[
// ---------- Foundations
{c:"WEB",p:"f",n:"Web & API vulnerabilities",
 s:"The vulnerability classes you must explain by root cause, exploit and class-level fix.",
 know:["OWASP Top 10 (2021, and what changed in the 2025 list) and the OWASP API Top 10: BOLA, broken function-level and property-level authorization","Injection: SQL, NoSQL, OS command, LDAP, SSTI, XXE; why parameterisation fixes the class","XSS (reflected, stored, DOM), CSP, output encoding by context","CSRF and SameSite; CORS vs Same-Origin Policy and misconfigurations","SSRF and cloud metadata; deserialization; path traversal; open redirect","Race conditions, business logic flaws, request smuggling, cache poisoning"],
 doing:["Explain each class to developers with their own code","Write the secure coding standard for the stack","Review fixes and confirm the whole class is closed"],
 tools:["Burp Suite","OWASP ZAP","Postman","Nuclei"],out:["Secure coding standard","Vulnerability knowledge base"],
 sr:"I explain a bug by its root cause and the control that kills the class, not by the payload."},
{c:"IAM",p:"f",n:"Identity, authentication & authorization",
 s:"Who the user is, what they may do, and how services prove who they are.",
 know:["OAuth 2.0 flows: authorization code with PKCE, client credentials, device flow; why implicit is deprecated","OIDC tokens, SAML assertions and signature wrapping, JWT pitfalls (alg none, key confusion, missing aud)","Sessions vs tokens, cookie attributes, BFF pattern, refresh token rotation","MFA, passkeys/WebAuthn, account recovery as an attack path","Authorization models: RBAC, ABAC, ReBAC (Zanzibar), policy engines (OPA, Cedar), multi-tenancy","Service identity: mTLS, SPIFFE, workload identity; SSO and SCIM provisioning"],
 doing:["Review login, token and permission designs","Define the company-wide authorization pattern and library","Test authZ with two users and two tenants"],
 tools:["Okta / Entra ID","Auth0 / Cognito / Keycloak","OPA / Cedar"],out:["Auth reference architecture","AuthZ library or policy service"],
 sr:"The authorization model is the most important security decision in a product; I want it centralised and deny-by-default."},
{c:"CRY",p:"f",n:"Cryptography & PKI",
 s:"Enough cryptography to choose correctly and spot misuse. Never to invent it.",
 know:["Encoding vs hashing vs encryption vs signing; symmetric (AES-GCM) vs asymmetric (RSA, ECDSA, Ed25519)","Password hashing: Argon2id, bcrypt, scrypt; HMAC; secure randomness","TLS 1.2/1.3 handshake, certificate chains, revocation, pinning trade-offs","Envelope encryption with KMS, key rotation, separation of key admin and key use","Post-quantum migration awareness (ML-KEM, ML-DSA) and crypto inventory"],
 doing:["Review crypto choices in designs and code","Define approved algorithms and libraries","Own the key management standard with the platform team"],
 tools:["AWS KMS / CloudHSM","ACM / cert-manager","Tink / libsodium"],out:["Cryptography standard","Key management policy"],
 sr:"My first questions are where the keys live, who can use them, and how they rotate."},
{c:"NET",p:"f",n:"Network & protocols",
 s:"The plumbing under every application and every trust boundary.",
 know:["TCP/IP, DNS (and subdomain takeover), HTTP/1.1 vs 2 vs 3","VPCs, subnets, security groups, NACLs, private endpoints","Segmentation, egress control, zero trust networking","WAF, IDS/IPS, load balancers and proxies; common ports and services"],
 doing:["Read network diagrams and spot unintended paths","Review ingress and egress for new services"],
 tools:["nmap","Wireshark","VPC Flow Logs"],out:["Network security baseline"],
 sr:"I think in trust boundaries and paths: what can reach what, and with whose identity."},
{c:"CODE",p:"f",n:"Secure code review",
 s:"Reading real code in several languages and finding flaws tools miss.",
 know:["Read Java, JavaScript/TypeScript, Python, Go, C#; memory-safety basics for C/C++","Source-to-sink tracing and framework idioms (Spring, Express, Django, .NET, React)","Dangerous APIs per language; where authZ, input handling and crypto live","Validating SAST findings by hand: true vs false positive with reasoning"],
 doing:["Review high-risk changes: auth, payments, file handling, parsers","Turn repeated bugs into custom SAST rules","Pair with developers on fixes"],
 tools:["Semgrep","CodeQL","IDE + grep"],out:["Review checklists per language","Custom rules"],
 sr:"I review auth and trust-boundary code first, and every real bug I find becomes a rule so it can't come back."},
{c:"MOB",p:"f",n:"Mobile security",
 s:"Android and iOS clients, and the APIs they expose.",
 know:["OWASP MASVS and MASTG","Android: exported components, intents, deep links, WebView bridges, Keystore","iOS: ATS, Keychain, URL schemes, entitlements","Certificate pinning, root/jailbreak detection, app attestation (Play Integrity, App Attest)","Reverse engineering with jadx, Frida, objection; secrets in binaries"],
 doing:["Set the mobile security baseline","Test releases and review SDKs added to the apps"],
 tools:["MobSF","Frida / objection","jadx"],out:["Mobile baseline (MASVS level)"],
 sr:"The API behind the app is the real target; client-side controls only slow attackers down."},
{c:"CLD",p:"f",n:"Cloud security",
 s:"AWS first, with working knowledge of Azure and GCP equivalents.",
 know:["Shared responsibility model; multi-account landing zone (Organizations, Control Tower)","IAM policy evaluation, SCPs, permission boundaries, privilege escalation paths","CloudTrail, GuardDuty, Security Hub, Inspector, KMS, Secrets Manager","S3 policies and Block Public Access; IMDSv2; VPC endpoints","Azure (Entra ID, Defender for Cloud) and GCP (Org Policy, SCC) mappings"],
 doing:["Review cloud designs and IaC for new services","Define guardrails with the platform team","Triage cloud findings for app teams"],
 tools:["AWS native services","Prowler","PMapper"],out:["Cloud security baseline","Guardrail set"],
 sr:"In the cloud, identity is the perimeter. Most breaches are a mis-scoped role, not a missing firewall rule."},
{c:"K8S",p:"f",n:"Containers & Kubernetes",
 s:"How most modern services actually run.",
 know:["Image hardening, minimal bases, non-root, read-only filesystems","Kubernetes RBAC, service accounts, Pod Security Standards","NetworkPolicy (Cilium, Calico), admission control (Kyverno, Gatekeeper)","Secrets handling, IRSA / Pod Identity on EKS, node hardening, CIS benchmarks","Runtime security: Falco, KubeArmor, Cilium Tetragon, GuardDuty runtime"],
 doing:["Set cluster and workload baselines","Review Helm charts and manifests","Respond to runtime alerts with the platform team"],
 tools:["Trivy","kube-bench","Kyverno","KubeArmor / Falco"],out:["Kubernetes baseline","Admission policies"],
 sr:"I design so a compromised pod can reach only what that one service needs."},
{c:"AI",p:"f",n:"AI & LLM security",
 s:"Securing AI features, and using AI to scale security work.",
 know:["OWASP Top 10 for LLM Applications: prompt injection, sensitive data disclosure, excessive agency, insecure output handling","Indirect prompt injection through documents, web pages and tool results","Agent and MCP tool permissions, human approval for destructive actions","RAG data isolation per tenant; model and dataset supply chain","Governance: NIST AI RMF, ISO 42001, EU AI Act awareness"],
 doing:["Threat model AI features","Red-team prompts and agent flows","Use LLMs for triage and code review with human verification"],
 tools:["Garak / PyRIT","Guardrail frameworks","LLM-assisted review"],out:["AI security standard","AI feature review checklist"],
 sr:"I treat model output as untrusted input and limit what an agent can do, not just what it is told."},
// ---------- Build
{c:"REQ",p:"b",n:"Security requirements",
 s:"Turning risk into requirements engineers can build and test.",
 know:["OWASP ASVS levels 1-3 and MASVS","Data classification and risk tiering of features","Abuse cases next to user stories","Privacy by design: data minimisation, retention, consent (GDPR, DPDP)"],
 doing:["Publish requirement sets per risk tier","Write security acceptance criteria into stories","Answer 'what do I need to do?' for product teams"],
 tools:["ASVS","Jira templates"],out:["Requirement templates","Data classification policy"],
 sr:"A requirement only counts if it has a test, so I write it as acceptance criteria."},
{c:"TM",p:"b",n:"Threat modeling & design review",
 s:"Finding design flaws while they are still cheap to fix.",
 know:["STRIDE, PASTA, LINDDUN (privacy), attack trees","Data flow diagrams and trust boundaries","Risk rating and the four responses: mitigate, eliminate, transfer, accept","Review intake and tiering so only high-risk designs get a full review","Pattern library of pre-approved designs"],
 doing:["Run design reviews and STRIDE sessions","Turn threats into tickets with owners","Train champions to run lightweight models"],
 tools:["OWASP Threat Dragon","IriusRisk","draw.io"],out:["Threat models","Design review records","Pattern library"],
 sr:"I walk one request hop by hop, mark the trust boundaries, and every threat leaves with an owner and a test."},
{c:"SDL",p:"b",n:"Secure SDLC & champions",
 s:"The operating model that puts security into every phase.",
 know:["Security activities and gates per phase","Definition of Done with security items","Security champions programme design","NIST SSDF and OWASP SAMM practices"],
 doing:["Write and maintain the SDLC security policy","Run the champions network and office hours","Embed in planning for high-risk work"],
 tools:["Confluence","Jira","Slack channels"],out:["SDLC policy","Champions programme"],
 sr:"Security is an input and an exit check at every phase, not a pentest at the end."},
{c:"CI",p:"b",n:"Pipeline security scanning",
 s:"Automated checks that run on every change.",
 know:["SAST, SCA, secret scanning, IaC scanning, container scanning, DAST in CI","Diff-aware scanning and quality gates on new findings only","Tuning, false-positive suppression, PR comments","Application security posture management (ASPM) to aggregate and dedupe"],
 doing:["Roll out scanners across hundreds of repos","Tune rules until findings are trusted","Measure coverage and noise"],
 tools:["Semgrep / CodeQL / Checkmarx","Snyk / Dependabot","gitleaks","Trivy","ArmorCode / Apiiro"],out:["Scanning standard","Coverage dashboard"],
 sr:"I block only on new, high-confidence, high-severity issues; everything else becomes a ticket."},
{c:"SUP",p:"b",n:"Software supply chain",
 s:"Protecting what you build from and how you build it.",
 know:["SBOMs (CycloneDX, SPDX) and VEX","Dependency confusion, typosquatting, malicious packages","Lockfiles, pinning, private registries","Signing (Sigstore cosign) and provenance (SLSA levels)","CI hardening: OIDC to cloud, pinned actions, protected branches"],
 doing:["Generate SBOMs per build","Harden CI/CD and review workflow changes","Lead response to a compromised dependency"],
 tools:["Syft","cosign","Socket","GitHub/GitLab security"],out:["Supply chain standard","SBOM inventory"],
 sr:"The CI system holds deploy credentials, so I secure it like production."},
{c:"PAV",p:"b",n:"Paved roads & secure defaults",
 s:"Making the secure way the easiest way.",
 know:["Secure service templates with auth, logging and validation built in","Shared libraries for authZ, crypto, output encoding","Hardened base images and golden Terraform modules","Framework defaults: CSP, security headers, CSRF protection"],
 doing:["Build or sponsor platform features that remove bug classes","Measure adoption of the paved road"],
 tools:["Backstage templates","Internal libraries"],out:["Templates","Golden modules"],
 sr:"My highest-leverage work removes a whole class of bugs for every team at once."},
{c:"IAC",p:"b",n:"IaC & policy as code",
 s:"Security standards as code that runs before infrastructure exists.",
 know:["Terraform, CloudFormation, Helm","Checkov, tfsec, cfn-nag","OPA/Rego with Conftest, Sentinel","Preventive (SCPs, admission) vs detective (Config rules, CSPM) guardrails","Drift detection"],
 doing:["Write policies for the company baseline","Roll them out in soft-fail, then enforce"],
 tools:["Checkov","OPA / Conftest","AWS Config"],out:["Policy library"],
 sr:"Every standard I write should exist as a policy check, or it won't be followed at scale."},
// ---------- Run
{c:"PT",p:"r",n:"Pentest & DAST",
 s:"Testing the running system as an attacker would.",
 know:["DAST tools and authenticated scanning","Manual pentest scoping, rules of engagement, retests","Managing external pentest vendors","Pentest vs red team vs purple team","Customer-facing attestation letters"],
 doing:["Pentest high-risk releases","Coordinate annual third-party tests","Triage and track pentest findings"],
 tools:["Burp Suite Enterprise","OWASP ZAP","Nuclei"],out:["Pentest reports","Retest evidence"],
 sr:"A pentest validates the controls; the threat model and pipeline should have caught most issues already."},
{c:"BB",p:"r",n:"Bug bounty & VDP",
 s:"Letting external researchers find what you missed.",
 know:["VDP vs paid bounty; private vs public programmes","Scope, rules, safe harbour, security.txt","Triage, duplicates, severity and payout tables","Researcher communication and disclosure"],
 doing:["Run or co-run the programme with a platform","Validate reports and drive fixes","Feed recurring bugs back into training and rules"],
 tools:["HackerOne","Bugcrowd","Intigriti"],out:["Programme policy","Payout table"],
 sr:"Each bounty payout is data on what our SDLC misses."},
{c:"VM",p:"r",n:"Vulnerability management",
 s:"One process for every finding, whatever its source.",
 know:["CVSS v3.1 and v4.0, EPSS, CISA KEV","Context: exposure, reachability, data sensitivity, compensating controls","SLAs by severity and exception process","Deduplication and ownership mapping to teams","Verification before closure"],
 doing:["Triage and prioritise findings","Track SLAs and escalate","Report MTTR and backlog to leadership"],
 tools:["ASPM","Jira","DefectDojo"],out:["VM policy and SLAs","Exec dashboard"],
 sr:"I prioritise on exploitability and exposure, not the CVSS number alone."},
{c:"EDGE",p:"r",n:"Edge & runtime protection",
 s:"Controls in front of and around the running application.",
 know:["WAF managed and custom rules, rate limiting, bot management","DDoS protection, API gateways, CDN security","Security headers, RASP","Virtual patching while a fix is in progress"],
 doing:["Set the WAF baseline","Deploy virtual patches for urgent issues"],
 tools:["AWS WAF / Cloudflare","Shield","API Gateway"],out:["Edge baseline"],
 sr:"The WAF buys time; it never replaces the fix."},
{c:"CSPM",p:"r",n:"Cloud posture (CSPM / CNAPP)",
 s:"Continuous view of cloud misconfiguration and risk.",
 know:["CSPM, CWPP, CIEM, attack path analysis","Toxic combinations: public + vulnerable + over-privileged","Mapping findings to owners and IaC"],
 doing:["Triage posture findings","Push fixes into IaC, not the console"],
 tools:["Wiz","Prisma Cloud","Defender for Cloud","Security Hub"],out:["Posture dashboard"],
 sr:"I fix posture issues in the IaC module so they don't return on the next deploy."},
{c:"SEC",p:"r",n:"Secrets & key management",
 s:"Credentials kept out of code, rotated, and replaced by identity where possible.",
 know:["Secrets managers and rotation","Secret detection in repos, logs and images","Leaked secret response: rotate first, then investigate","Workload identity (IAM roles, OIDC) instead of static secrets"],
 doing:["Set the secrets standard","Run leaked-secret response","Push teams to remove secrets entirely"],
 tools:["Secrets Manager / Vault","gitleaks / TruffleHog"],out:["Secrets standard","Leak runbook"],
 sr:"The best secret is the one that doesn't exist because the workload uses its own identity."},
{c:"DET",p:"r",n:"Logging, detection & response",
 s:"Seeing attacks and handling application-layer incidents.",
 know:["What an application must log (auth events, authZ denials, admin actions) and must not (tokens, PII)","CloudTrail, SIEM, SOAR basics","NIST 800-61 incident lifecycle; runbooks","Breach notification obligations"],
 doing:["Define app logging requirements","Write detections for app abuse with the SOC","Lead app-layer incidents and post-mortems"],
 tools:["Splunk / Elastic / Sentinel","GuardDuty","PagerDuty"],out:["Logging standard","Runbooks","Post-mortems"],
 sr:"Detection is how we catch what got past every other control, so apps must log the right events."},
// ---------- Programme
{c:"RISK",p:"p",n:"Risk management & exceptions",
 s:"Making risk decisions explicit, owned and time-bound.",
 know:["Risk register; likelihood × impact","Risk acceptance with a named owner, compensating controls and expiry","Risk appetite; FAIR for quantifying in money","Security debt tracking"],
 doing:["Run the exception process","Present top risks to leadership"],
 tools:["GRC platform","Risk register"],out:["Exception process","Top risks report"],
 sr:"I don't own the risk decision; I make sure the person who does understands it and signs it."},
{c:"GRC",p:"p",n:"Compliance & audits",
 s:"Proving controls work to auditors and customers.",
 know:["SOC 2 (Type I and II), ISO 27001 Annex A","PCI DSS v4.0, HIPAA, FedRAMP (NIST 800-53)","GDPR and India's DPDP Act","Mapping SDLC controls to frameworks; continuous evidence"],
 doing:["Provide SDLC and vulnerability evidence","Answer auditor questions on AppSec controls"],
 tools:["Vanta / Drata","AWS Audit Manager"],out:["Control mappings","Evidence packages"],
 sr:"I design processes that produce evidence as a by-product, so audits don't become projects."},
{c:"MET",p:"p",n:"Metrics & reporting",
 s:"Numbers that show risk going down and drive decisions.",
 know:["MTTR by severity, SLA adherence, open critical/high trend","Coverage: repos scanned, high-risk features threat modelled","Escape rate: bugs found in production or bounty vs pre-release","Leading vs lagging indicators; exec vs team dashboards"],
 doing:["Build dashboards per team and for leadership","Use data to choose next quarter's priorities"],
 tools:["ASPM dashboards","Looker / Grafana"],out:["Monthly security report"],
 sr:"I report a few metrics that change decisions, not a wall of vulnerability counts."},
{c:"MAT",p:"p",n:"Strategy & maturity",
 s:"Where the programme is today and where it goes next.",
 know:["OWASP SAMM and BSIMM assessments","NIST SSDF; CISA Secure by Design","Roadmaps, OKRs, budget and headcount ratios"],
 doing:["Assess maturity yearly","Write the AppSec roadmap and business case"],
 tools:["SAMM toolbox"],out:["Maturity baseline","12-month roadmap"],
 sr:"I tie every roadmap item to a risk reduction or a business outcome."},
{c:"TPR",p:"p",n:"Third parties, customers & M&A",
 s:"Risk that comes from outside the codebase.",
 know:["Vendor and SaaS integration reviews; OAuth app permissions","Open source intake","Acquisition due diligence and integration","Customer questionnaires (SIG, CAIQ), trust centre, pentest letters"],
 doing:["Review high-risk vendors","Answer enterprise customer security questions","Assess acquired products"],
 tools:["Questionnaire tools","Trust centre"],out:["Vendor review process","Standard answers library"],
 sr:"Security is part of how we win and keep enterprise customers, not only a cost."},
{c:"CUL",p:"p",n:"Training & culture",
 s:"Raising the security skill of every engineer.",
 know:["Role- and stack-specific secure coding training","Hands-on labs, CTFs, hack days","Blameless post-mortems"],
 doing:["Run training built from the company's own bugs","Recognise teams that fix classes of bugs"],
 tools:["Secure Code Warrior","Internal labs"],out:["Training curriculum"],
 sr:"Training built from our own real bugs changes behaviour far more than generic slides."},
{c:"COM",p:"p",n:"Communication & influence",
 s:"Getting things done without authority.",
 know:["Writing findings for developers and for executives","Risk narratives in business terms","Negotiating timelines and offering options instead of 'no'","Design docs, RFCs and decision records"],
 doing:["Brief leadership and customers","Resolve disagreements with data"],
 tools:["Docs","Slides"],out:["Risk briefs","Decision records"],
 sr:"I bring options with trade-offs, not a veto."},
{c:"TOOL",p:"p",n:"Tooling & automation",
 s:"Choosing tools and writing the glue that makes the programme scale.",
 know:["Build vs buy; proof-of-concept criteria","Tool rationalisation and integration with Jira and Slack","Python or Go automation against tool APIs","LLM-assisted triage with human review"],
 doing:["Run tool evaluations","Automate repetitive triage and reporting"],
 tools:["Python / Go","Tool APIs","Claude / LLMs"],out:["Tool evaluation reports","Automation scripts"],
 sr:"If I do something by hand three times, I automate it."}
];
window.LSTAGES=[
 ["Plan",["REQ","RISK","GRC"],"What data, what risk tier, which requirements?"],
 ["Design",["TM","IAM","CRY","AI"],"Is the design safe before code exists?"],
 ["Code",["CODE","PAV","CUL","WEB"],"Do developers write it securely by default?"],
 ["Build",["CI","SUP","IAC","SEC"],"Do automated checks catch what slipped?"],
 ["Test",["PT","MOB"],"Does it hold up against a real attacker?"],
 ["Deploy",["K8S","CLD","NET","EDGE"],"Is it running in a hardened place?"],
 ["Operate",["VM","CSPM","DET","BB"],"Do we see and fix issues fast?"],
 ["Improve",["MET","MAT","TPR","TOOL"],"Is the programme getting better?"]
];
window.MATRIX={
 cols:[["Phase 0 · Day 1","nothing exists"],["Phase 1 · First 90 days","visibility and quick wins"],["Phase 2 · Year 1","scale with automation"],["Phase 3 · Year 2+","mature and measured"]],
 rows:[
  ["f","Foundations",[
    ["Inventory apps, repos, cloud accounts and data","Meet engineering leads; learn the stack"],
    ["Secure coding standard for top 2 stacks","Auth and cloud baselines written"],
    ["Standards for mobile, containers, AI features","Authorization pattern agreed"],
    ["Standards maintained as code and templates","Internal expertise per domain"]]],
  ["b","Build-time",[
    ["Secret scanning and SCA on the main repos","Design review for the riskiest project"],
    ["SAST and IaC scanning in report-only mode","Threat model intake questionnaire","First security champions"],
    ["Scanners on all repos with tuned quality gates","SBOM per build, signed images","ASVS requirements in stories"],
    ["Paved-road templates remove bug classes","Policy as code for every standard","Champions run most threat models"]]],
  ["r","Run-time",[
    ["Turn on GuardDuty, Security Hub, WAF basics","Check for public buckets and exposed admin panels"],
    ["One vulnerability intake and SLA policy","VDP with security.txt","Annual external pentest"],
    ["Paid bug bounty","CSPM/CNAPP with owner mapping","App logging standard and detections"],
    ["Risk-based prioritisation with EPSS and reachability","Automated virtual patching","Purple-team exercises"]]],
  ["p","Programme",[
    ["Agree risk owner and escalation path","Know the compliance obligations"],
    ["SDLC policy; exception process","First metrics: open criticals, MTTR"],
    ["SAMM baseline and roadmap","Monthly report to leadership","Compliance evidence automated"],
    ["Metrics drive the roadmap","Security as a sales asset (trust centre)","Yearly maturity reassessment"]]]
 ]
};
window.CAD=[
 ["Daily",["Triage new findings from scanners, bounty and pentests","Answer developer questions in the security channel","Review high-risk pull requests"]],
 ["Weekly",["Design reviews and threat modeling sessions","Champions office hours","SLA check and escalations"]],
 ["Monthly",["Metrics report to engineering leadership","Tune scanner rules and suppressions","Training session from recent real bugs"]],
 ["Quarterly",["Roadmap and OKR review","Tool evaluation or rollout","Tabletop incident exercise"]],
 ["Yearly",["SAMM or BSIMM maturity assessment","Third-party pentests and audits (SOC 2, ISO, PCI)","Budget, headcount and strategy"]]
];
window.PEOPLE=[
 ["Developers","Clear, actionable fixes; few false positives; fast answers","Fixing code; attending reviews; feedback on tools"],
 ["Engineering managers","Predictable work, no surprise release blockers","Time in the sprint for security work; owners for findings"],
 ["Platform / DevOps / SRE","Pipelines that stay fast; guardrails as code","Scanner integration; IAM, network and cluster changes"],
 ["Product managers","Security that doesn't delay launches; customer trust","Early heads-up on risky features; prioritisation"],
 ["SOC / incident response","Good app logs and detections; app expertise in incidents","Alerts and escalation; investigation support"],
 ["GRC / compliance","Evidence that SDLC controls operate","Framework requirements; audit timelines"],
 ["Legal & privacy","Data handling done right; breach decisions","Regulatory interpretation; disclosure decisions"],
 ["Sales & customer success","Answers to security questionnaires and customer calls","Customer requirements that shape the roadmap"],
 ["Leadership / CISO","Risk in business terms; progress over time","Budget, headcount and backing for hard calls"],
 ["External researchers","Fast, respectful triage and fair payouts","Findings you didn't catch"]
];
window.SENIOR=[
 ["Scope","Tests one app or one finding","Owns the system that stops a class of findings across all teams"],
 ["Answers","Lists the payload and the fix","States the root cause, the class-level control, the owner and how it's verified"],
 ["Tools","Runs the scanner","Chooses, tunes and integrates tools; measures noise and coverage"],
 ["Risk","Uses the CVSS score","Combines exploitability, exposure, data and business impact; documents acceptance"],
 ["Developers","Files tickets","Changes the default so the bug can't be written; teaches with their own code"],
 ["Disagreements","Escalates or gives in","Brings options with trade-offs and data; makes sure the right person decides"],
 ["Impact","Number of bugs found","MTTR down, escape rate down, coverage up, audits passed without fire drills"],
 ["Stories","'We found X'","'I built Y, which cut Z by N%, and here's what I'd do differently'"]
];


window.MW=150;window.MH=56;
window.MN={
 users:{x:20,y:60,z:"ext",t:"Customers",s:"browser · mobile app"},
 partner:{x:20,y:210,z:"ext",t:"Partner systems",s:"B2B API clients"},
 attacker:{x:20,y:340,z:"threat",t:"Attacker",s:"anyone on the internet"},
 cdn:{x:200,y:60,z:"edge",t:"CloudFront + WAF",s:"edge · TLS · DDoS"},
 alb:{x:200,y:210,z:"edge",t:"Load balancer",s:"ALB · public subnet"},
 idp:{x:380,y:60,z:"id",t:"Identity provider",s:"Cognito / Okta · OIDC"},
 api:{x:380,y:210,z:"id",t:"API gateway / BFF",s:"token check · throttling"},
 pg:{x:560,y:60,z:"ext",t:"Payment provider",s:"third party"},
 orders:{x:560,y:180,z:"svc",t:"Orders service",s:"EKS pod · own IAM role"},
 payments:{x:560,y:265,z:"svc",t:"Payments service",s:"mTLS · PCI scope"},
 workers:{x:560,y:350,z:"svc",t:"Background workers",s:"queue consumers"},
 s3:{x:790,y:60,z:"data",t:"File storage",s:"S3 · private · KMS"},
 db:{x:790,y:180,z:"data",t:"Database",s:"RDS · KMS · IAM auth"},
 cache:{x:790,y:265,z:"data",t:"Cache / sessions",s:"ElastiCache Redis"},
 queue:{x:790,y:350,z:"data",t:"Message queue",s:"SQS · EventBridge"},
 foundation:{x:20,y:478,w:296,h:62,z:"base",t:"Cloud foundation",s:"accounts · IAM · KMS · secrets · VPC"},
 delivery:{x:332,y:478,w:296,h:62,z:"base",t:"Delivery pipeline",s:"Git · CI/CD · IaC · scanners"},
 detect:{x:644,y:478,w:296,h:62,z:"base",t:"Detect and respond",s:"CloudTrail · GuardDuty · SIEM"}
};
window.ME=[
 ["e1","users","cdn","HTTPS"],["e2","users","idp","login","dash"],["e3","partner","cdn","OAuth client"],
 ["e4","cdn","alb",""],["e5","attacker","alb","direct hit blocked","block"],["e6","alb","api",""],
 ["e7","api","idp","JWKS keys","dash"],["e8","api","orders",""],["e9","orders","payments","mTLS"],
 ["e10","payments","pg","card token"],["e11","orders","db","SQL/TLS"],["e12","orders","cache",""],
 ["e13","orders","queue","event"],["e14","queue","workers",""],["e15","orders","s3","signed URL"]
];
window.MZONE={ext:"var(--z-ext)",edge:"var(--z-edge)",id:"var(--z-id)",svc:"var(--z-svc)",data:"var(--z-data)",base:"var(--z-base)",threat:"var(--signal-soft)"};
window.MZNAME={ext:"Outside party",edge:"Edge",id:"Identity",svc:"Service",data:"Data",base:"Foundation",threat:"Threat actor"};

window.MD={
users:{does:"Real people using the web app and mobile app. They never talk to services directly; everything goes through the edge.",
 threats:[["S","Account takeover through credential stuffing or phishing"],["I","Tokens stolen from the browser by XSS or a malicious script"],["T","Tampered mobile app or intercepted traffic"]],
 controls:["Login only through the identity provider, with MFA available","Tokens kept out of JavaScript: BFF plus HttpOnly, Secure, SameSite cookie","Content Security Policy and output encoding against XSS","Mobile: tokens in Keychain or Keystore, certificate validation"],
 tools:["Cognito / Okta","CSP","Keychain / Keystore"],
 say:"The browser is untrusted. My goal is that a script running in it can't steal a long-lived credential."},
partner:{does:"Other companies' systems calling the public API for automation, such as bulk order upload.",
 threats:[["S","Leaked static API key used by someone else"],["E","Partner reaching endpoints or tenants outside its contract"],["D","Bulk calls overwhelming the API"]],
 controls:["OAuth 2.0 client credentials or mTLS instead of static keys","Scopes per partner and per tenant","Per-client rate limits and quotas","Key rotation and IP allow-lists where possible"],
 tools:["OAuth client credentials","API Gateway usage plans"],
 say:"Machine clients get their own identity and narrow scopes, the same as human users get roles."},
attacker:{does:"Anyone on the internet. Assume they can reach every public IP and read your JavaScript bundle.",
 threats:[["S","Credential stuffing and token forgery"],["E","Bypassing the WAF by hitting the load balancer directly"],["D","Volumetric DDoS and application-layer floods"],["I","Scraping, enumeration and IDOR"]],
 controls:["Only one way in: CloudFront, with the ALB locked to CloudFront","WAF managed rules, rate limits and bot control","Authorization checked in every service, not only at the edge","Logging and alerting so attacks are seen, not just blocked"],
 tools:["AWS WAF","Shield","GuardDuty"],
 say:"I design assuming the attacker already knows the architecture. Security can't depend on them not finding an endpoint."},
cdn:{does:"The front door. Terminates TLS close to the user, caches static content and filters malicious traffic before it reaches the VPC.",
 threats:[["D","DDoS and request floods"],["T","Injection payloads (SQLi, XSS) in requests"],["S","Bots and credential stuffing on login"]],
 controls:["TLS 1.2+ with ACM certificates, HSTS","AWS WAF: Core rule set, Known Bad Inputs, SQLi, IP reputation","Rate-based rules on login and expensive endpoints","Shield Standard always on; Shield Advanced for critical apps","Adds a secret header so the origin knows traffic came through here"],
 tools:["CloudFront","AWS WAF","Shield","ACM"],
 say:"The edge filters the noise and absorbs DDoS. It is defense in depth, not a fix for IDOR or broken auth."},
alb:{does:"Spreads traffic across app instances. Sits in a public subnet; everything behind it is private.",
 threats:[["E","Attacker skips CloudFront and WAF by calling the ALB directly"],["T","HTTP request smuggling and malformed headers"],["I","Plain HTTP or weak TLS"]],
 controls:["Security group allows only the CloudFront managed prefix list","Listener rule rejects requests without the CloudFront secret header","HTTPS listener only, HTTP redirects; modern TLS policy","drop_invalid_header_fields and desync mitigation mode on","Access logs to S3, alarms on 4xx/5xx spikes"],
 tools:["ALB","Security groups","ACM"],
 say:"The ALB accepts traffic only from CloudFront, so there is no path around the WAF."},
idp:{does:"Proves who the user is. Runs login, MFA and password reset, and issues signed tokens (ID token, access token, refresh token).",
 threats:[["S","Phishing, password spraying, MFA fatigue"],["T","Forged tokens if signing keys leak"],["E","Weak redirect URI validation leading to token theft"]],
 controls:["OIDC authorization code flow with PKCE","MFA, enforced for admins and sensitive actions","Exact-match redirect URIs","Short-lived access tokens, rotating refresh tokens with reuse detection","Signing keys held by the IdP or in KMS, published via JWKS"],
 tools:["Cognito","Okta / Entra ID","KMS"],
 say:"We never build login ourselves. A dedicated IdP issues tokens and the services only verify them."},
api:{does:"The single entry for API calls. For the web app it is a backend-for-frontend (BFF) that holds tokens server side.",
 threats:[["S","Forged, expired or wrong-audience JWT"],["T","Malformed or oversized requests, mass assignment"],["D","Abuse of expensive endpoints"]],
 controls:["Validate signature, algorithm, iss, aud, exp on every request","Request schema validation from the OpenAPI spec","Per-user and per-client throttling","BFF keeps tokens off the browser; browser gets only a session cookie","Strips client-sent identity headers before forwarding"],
 tools:["API Gateway","JWT authorizer","Lambda / BFF"],
 say:"Token checks happen here first, but services still validate again. The gateway is not the only lock."},
pg:{does:"External provider (Stripe, Adyen) that handles card data so the company never stores card numbers.",
 threats:[["S","Fake 'payment succeeded' webhook"],["I","Card data leaking into our logs or database"],["T","Tampered amount or currency in the payment request"]],
 controls:["Tokenization: only provider tokens touch our systems","Verify webhook signatures and timestamps","Re-query payment status before fulfilling an order","Server-side calculation of amounts","Egress to the provider only, over TLS"],
 tools:["Stripe / Adyen","Webhook HMAC","Network Firewall"],
 say:"Tokenization moves most of PCI scope to the provider, which is the biggest single risk reduction for payments."},
orders:{does:"Business logic for orders. Runs as pods on EKS with its own IAM role and its own database.",
 threats:[["E","IDOR: user A reads or edits user B's order"],["T","Mass assignment of price, status or role"],["I","SQL injection exposing all customers"],["E","SSRF or RCE used to call AWS APIs with the pod's role"]],
 controls:["Object-level authorization on every query, tenant from the token","Request DTOs with allow-listed fields; prices recalculated server side","Parameterized queries only","Per-service IAM role (IRSA), metadata service blocked for pods","Non-root, read-only filesystem, default-deny NetworkPolicy"],
 tools:["EKS","IRSA / Pod Identity","Kyverno","KubeArmor / Falco"],
 say:"Authorization lives in the service, close to the data, and the tenant always comes from the verified token."},
payments:{does:"Talks to the payment provider. Higher risk, so it is isolated and only Orders may call it.",
 threats:[["S","Another compromised pod calling Payments directly"],["T","Amount changed between services"],["R","No proof of who triggered a refund"]],
 controls:["mTLS with workload identity; policy allows only Orders","NetworkPolicy restricting ingress and egress","Idempotency keys and server-side amounts","Audit log of every charge and refund with user and request ID","Separate namespace or account for PCI scope"],
 tools:["Service mesh mTLS","Cilium / NetworkPolicy","CloudTrail"],
 say:"Inside the cluster is not trusted. Every service call carries a verifiable service identity."},
workers:{does:"Run slow jobs from the queue: emails, exports, invoices, webhooks to customers.",
 threats:[["T","Malicious or malformed message triggering bad behavior"],["E","Deserialization bugs in message handling"],["I","Exports containing another tenant's data"]],
 controls:["Validate every message against a schema","No native object deserialization; JSON with strict types","Tenant ID carried in the message and re-checked","Dead-letter queue and alarms","Own IAM role, scoped to its own resources"],
 tools:["SQS","Lambda / EKS jobs","JSON Schema"],
 say:"Messages are input. Workers validate them like any request from the internet."},
s3:{does:"Stores uploads and exports. Users get time-limited pre-signed URLs, never the bucket itself.",
 threats:[["I","Public bucket or overly broad bucket policy"],["T","Malware or HTML uploads served from our domain"],["I","Pre-signed URLs that live too long or cover the wrong object"]],
 controls:["Block Public Access at account level, enforced by SCP","Bucket policy limited to service roles and VPC endpoint","SSE-KMS encryption, versioning","Short-lived pre-signed URLs per object; Content-Disposition: attachment","File type checks and malware scanning on upload"],
 tools:["S3","KMS","VPC endpoint","Config rules"],
 say:"Files are served through short-lived signed URLs, and public access is blocked at the account level so nobody can open it by mistake."},
db:{does:"The system of record. One database per service, in private subnets.",
 threats:[["I","SQL injection or stolen credentials dumping PII"],["T","Data altered by an over-privileged app user"],["I","Unencrypted snapshots shared or made public"]],
 controls:["Private subnet; security group allows only the service","IAM database auth or rotated secrets from Secrets Manager","App user without DDL; migrations run by a separate role","KMS encryption at rest, forced TLS in transit","Audit logs, GuardDuty RDS protection, cross-account encrypted backups"],
 tools:["RDS / Aurora","KMS","Secrets Manager","AWS Backup"],
 say:"The database is reachable only from its own service, with short-lived credentials and least privilege."},
cache:{does:"Holds sessions for the BFF and cached data for speed.",
 threats:[["I","Session data readable by anything in the VPC"],["S","Session fixation or predictable session IDs"],["T","Cache poisoning across tenants"]],
 controls:["Encryption in transit and at rest; AUTH or IAM auth","Security group limited to the services that use it","Random 128-bit session IDs, regenerated at login","Cache keys always include the tenant","Idle and absolute session timeouts"],
 tools:["ElastiCache Redis","KMS"],
 say:"Sessions are server side with random IDs, so logout and revocation really work."},
queue:{does:"Decouples services. Orders publishes an event; workers pick it up later.",
 threats:[["S","Any service or attacker sending fake messages"],["I","Sensitive data in messages readable by too many consumers"],["D","Queue flooding"]],
 controls:["Queue policy: only the Orders role can send, only workers can receive","KMS encryption","Minimal data in messages, IDs rather than full records","Dead-letter queue and depth alarms"],
 tools:["SQS","SNS","EventBridge"],
 say:"Queues get resource policies just like buckets. Who can publish is a security decision."},
foundation:{does:"The base everything runs on: separate AWS accounts, identity for people and workloads, keys, secrets and networks.",
 threats:[["E","One compromised account reaching production"],["E","IAM privilege escalation paths"],["I","Secrets in code, images or environment files"]],
 controls:["AWS Organizations: prod, non-prod, security and log-archive accounts","SCP guardrails (no disabling CloudTrail, approved regions only)","SSO for humans, no long-lived IAM users","Least-privilege roles per workload, permission boundaries","Secrets Manager with rotation; KMS customer-managed keys"],
 tools:["Organizations","IAM Identity Center","SCPs","KMS","Secrets Manager"],
 say:"Account separation and SCPs mean a mistake in a dev account can't touch production data."},
delivery:{does:"How code reaches production. Every change goes through Git and the pipeline; nobody edits production by hand.",
 threats:[["T","Malicious or vulnerable code or dependency shipped"],["E","Stolen CI credentials used to deploy anything"],["T","Unreviewed infrastructure change opening access"]],
 controls:["PR review, branch protection, signed commits where possible","SAST, SCA, secret scanning, IaC scanning, image scanning","OIDC federation from CI to AWS, no stored keys","Signed images, admission control in EKS","Only the pipeline role can write to production"],
 tools:["GitHub Actions","Semgrep / SonarQube","Snyk","Checkov","Trivy / Inspector"],
 say:"The pipeline is the only way to production, so it is where security checks become automatic."},
detect:{does:"Collects logs from every layer, raises alerts and drives incident response.",
 threats:[["R","Attacks happen with no record"],["T","Attacker deletes logs to hide"],["D","Too many alerts, real ones missed"]],
 controls:["Organization CloudTrail to a locked log-archive account","GuardDuty, Inspector and Security Hub in every account","App logs with user, tenant and request ID; no tokens or PII","Alerts mapped to runbooks with owners","Automated responses for safe actions (quarantine a public bucket)"],
 tools:["CloudTrail","GuardDuty","Security Hub","SIEM"],
 say:"Every hop logs who did what. Detection is how we find the attack that got past the controls."}
};

window.MSTEPS=[
 {t:"Sign in",n:["users","idp"],e:["e2"],why:"The user signs in at the identity provider using the authorization code flow with PKCE and MFA. The BFF receives the tokens and keeps them server side.",check:["Redirect URI matches exactly","MFA for risky logins","Browser gets only an HttpOnly, Secure, SameSite cookie"]},
 {t:"Reach the edge",n:["users","cdn"],e:["e1"],why:"The app sends an HTTPS request. CloudFront terminates TLS and the WAF inspects it before anything reaches the VPC.",check:["TLS 1.2+ and HSTS","WAF managed rules and rate limits","Bot control on login"]},
 {t:"Pass the load balancer",n:["cdn","alb","attacker"],e:["e4","e5"],why:"CloudFront forwards to the ALB with a secret header. A direct request from the attacker is dropped by the security group.",check:["ALB SG allows only the CloudFront prefix list","Invalid headers dropped","Access logs on"]},
 {t:"Check the token",n:["alb","api","idp"],e:["e6","e7"],why:"The gateway or BFF validates the access token against the IdP's public keys and checks the request against the API schema.",check:["Signature, alg, iss, aud, exp","Schema validation, size limits","Per-user throttling"]},
 {t:"Authorize in the service",n:["api","orders"],e:["e8"],why:"The Orders service receives the user and tenant from the verified token and checks that this user may act on this specific order.",check:["Object-level check on every query","Tenant never taken from the request body","Allow-listed fields only"]},
 {t:"Call another service",n:["orders","payments","pg"],e:["e9","e10"],why:"Orders calls Payments over mTLS. Payments sends only a card token and server-calculated amount to the provider.",check:["mTLS service identity","Only Orders may call Payments","Webhook signatures verified on the way back"]},
 {t:"Read and write data",n:["orders","db","cache","s3"],e:["e11","e12","e15"],why:"Orders queries its own database with parameterized SQL over TLS, using short-lived credentials. Files go through pre-signed URLs.",check:["IAM DB auth or rotated secret","Least-privilege DB user","KMS encryption at rest"]},
 {t:"Finish the work later",n:["orders","queue","workers"],e:["e13","e14"],why:"Orders publishes an event. A worker validates the message and sends the confirmation email.",check:["Queue policy restricts senders","Schema validation in the worker","Dead-letter queue and alarms"]},
 {t:"Leave a trail",n:["detect","foundation","delivery"],e:[],why:"Every hop wrote logs with the same request ID. CloudTrail recorded API calls, and GuardDuty watches for anything unusual.",check:["Request ID across all logs","Logs in a separate locked account","Alerts linked to runbooks"]}
];


window.SDLC=[
 {t:"Plan",items:["Classify the data the feature touches","Risk questionnaire: internet-facing? PII? payments? new auth?","Pull requirements from OWASP ASVS into user stories","Write abuse cases next to use cases"],who:"Product · AppSec",gate:"Security acceptance criteria on the story"},
 {t:"Design",items:["Design review for high-risk features","Data flow diagram with trust boundaries","STRIDE threat model, threats become tickets","Choose approved patterns for auth, secrets, crypto"],who:"Architect · AppSec",gate:"Threat model signed off; Critical/High mitigations planned"},
 {t:"Code",items:["Secure service template (auth, logging, validation built in)","IDE linting and pre-commit secret scanning","Shared libraries for authZ and crypto","Champion review for sensitive changes"],who:"Developers · Champions",gate:"PR review approved"},
 {t:"Build",items:["SAST (Semgrep, SonarQube) on changed code","SCA for dependencies, SBOM generated","IaC scan (Checkov) on the Terraform plan","Container image scan and signing"],who:"CI · Platform",gate:"No new Critical/High findings"},
 {t:"Test",items:["DAST against staging with test users","Authorization tests: two users, two tenants","Manual tests of threat-model items","Pentest for major releases"],who:"QA · AppSec",gate:"Security tests pass, findings triaged"},
 {t:"Release",items:["Release-blocking tickets closed","Risk acceptance recorded for anything open","Admission control verifies image signatures","Deploy through pipeline role only"],who:"Release manager · AppSec",gate:"Security sign-off with documented exceptions"},
 {t:"Run",items:["WAF, GuardDuty, Inspector, Security Hub","Vulnerability SLAs: Critical 7 days, High 30","Bug bounty and external reports triaged","Runbooks and on-call"],who:"SRE · SOC · AppSec",gate:"SLA breaches escalated"},
 {t:"Learn",items:["Post-incident and pentest reviews","New SAST rules from real bugs","Update standards and templates","Metrics: MTTR, coverage, escaped bugs"],who:"AppSec · Engineering leads",gate:"Fixes for the class, not just the instance"}
];

window.ROLES=["Developers","Platform / DevOps","AppSec","SOC","GRC / Compliance"];
window.OWN=[
 ["Fix code vulnerabilities","O","","H","",""],
 ["Threat models and design reviews","H","H","O","",""],
 ["Security tooling in CI/CD","","O","H","",""],
 ["IAM, network and cloud guardrails","","O","H","","H"],
 ["Secrets and key management","H","O","H","",""],
 ["Vulnerability triage and SLAs","H","H","O","","H"],
 ["Alerting and incident response","H","H","H","O",""],
 ["Audit evidence (SOC 2, ISO 27001, PCI)","","H","H","","O"],
 ["Security training and champions","H","","O","",""]
];

window.IRT=[
 ["Detect","02:10","A WAF block-count alarm and a spike in failed logins in app logs page the on-call SOC analyst."],
 ["Triage","02:20","Confirm the pattern: many IPs, many usernames, a few successful logins. Severity set to High, AppSec pulled in."],
 ["Contain","02:35","Tighten WAF rate limits on /login, turn on bot control challenges, force MFA for risky sessions."],
 ["Investigate","03:00","List accounts that logged in successfully from attack IPs and check what they did after login."],
 ["Recover","04:00","Revoke sessions and refresh tokens for affected users, force password resets, notify per policy."],
 ["Learn","Next week","Post-incident review: breached-password checks at signup, MFA by default, better login anomaly alerts."]
];
