// ===================== v2 additions =====================

// ---------- AI at every layer ----------
window.AILAYERS = [
{id:"req",stage:"Plan",title:"Security requirements from a spec",
 uses:["Read a PRD or design doc and list data types, entry points, roles and third parties","Map them to OWASP ASVS requirements and write security acceptance criteria","Suggest the risk tier (needs full review or checklist only)"],
 flow:["PRD lands in Jira/Confluence","LLM extracts assets, entry points, data classes","Maps to ASVS items for the risk tier","Posts draft acceptance criteria on the story","Champion or AppSec edits and approves"],
 guard:["A human approves every requirement set; the model drafts","Use an approved enterprise LLM; design docs can be confidential","Keep a fixed requirement library so output stays consistent"],
 metric:"% of high-risk features with security requirements before sprint start; intake turnaround",
 say:"I use an LLM to turn a PRD into a first draft of ASVS-mapped acceptance criteria in minutes, and a champion signs off. It moves security into planning without adding a meeting."},
{id:"tm",stage:"Design",title:"First-pass threat models",
 uses:["Draft a data flow diagram and trust boundaries from an architecture doc, IaC or OpenAPI spec","Generate a STRIDE threat list per flow with suggested controls","Turn accepted threats into tickets with test cases"],
 flow:["Architecture doc + IaC","LLM drafts DFD and STRIDE list","AppSec runs a 30-minute review with the team","Accepted threats become tickets with tests","Model stored next to the code and refreshed on change"],
 guard:["Models miss business context and invent components; always review with the team","Never let it rank risk alone; ranking needs business impact","Track how many accepted threats came from the draft vs humans"],
 metric:"Threat model coverage of high-risk features; review turnaround (days to hours)",
 say:"An LLM gets me a 70% first draft of a threat model in ten minutes. My time goes into the 30% that needs judgement: business impact, abuse cases and ranking."},
{id:"code",stage:"Code",title:"AI coding assistants, secured",
 uses:["Give assistants secure-coding rules files (approved libraries, auth patterns, no string-built SQL)","Generate secure code examples for remediation","Explain a finding in the developer's own code"],
 flow:["Org rules file for assistants","Developer writes code with the assistant","Same SAST/SCA/secret gates as human code","Findings explained inline with a fix"],
 guard:["AI code gets exactly the same review and gates","Package allow-lists stop 'slopsquatting' (installing hallucinated package names attackers registered)","Block assistants from reading secrets and .env files","Approved tools only; no pasting customer data or secrets into public chatbots"],
 metric:"Vulnerability density in AI-assisted code vs baseline; recurrence by class",
 say:"AI assistants raise output, so I treat them as a new developer: secure defaults through rules files, the same gates, and a package allow-list for hallucinated dependencies."},
{id:"pr",stage:"Code",title:"AI-assisted PR security review",
 uses:["Review every PR for auth, injection, secrets and dangerous APIs with repo context","Route only risky PRs (auth, payments, crypto, IaC) to a human security reviewer","Comment with the exact fix"],
 flow:["PR opened","Diff + surrounding code to reviewer model","Risk score + comments","High risk: human AppSec review requested","Developer fixes; bot re-checks"],
 guard:["PR text and code are untrusted input: prompt injection can try to make the bot approve","The bot gets no secrets and no merge rights","Measure precision against human reviews before relying on it"],
 metric:"% high-risk PRs reviewed by a human; escape rate; reviewer time per PR",
 say:"I use AI to decide where a human reviewer is needed, not to replace the review. The bot has no merge rights, because a PR can carry prompt injection too."},
{id:"triage",stage:"Build",title:"SAST/SCA triage and autofix",
 uses:["Read the finding plus source-to-sink code context and propose true or false positive with reasoning","Check reachability and existing sanitisers","Open an autofix PR with a test (GitHub Copilot Autofix, Semgrep Assistant and similar)"],
 flow:["Scanner finding","Enrich: code context, reachability, owner, exposure","LLM verdict + confidence + fix","Low confidence or Critical: human confirms","Ticket or autofix PR; rescan verifies"],
 guard:["Auto-suppress only after a human confirms, or for patterns with measured high accuracy","Log every AI verdict for audit","Track agreement rate with human triage (precision and recall)"],
 metric:"False-positive rate, triage time per finding, MTTR",
 say:"AI triage is where I see the biggest MTTR win: it removes the hours a developer spends deciding if a finding is real. I measure its agreement with human triage before trusting it."},
{id:"sca",stage:"Build",title:"Dependency upgrades",
 uses:["Summarise breaking changes in an upgrade and fix the code that breaks","Rank CVEs with EPSS, CISA KEV and reachability","Explain whether a CVE matters for this service"],
 flow:["New CVE","SBOM lookup: affected services","Reachability + EPSS/KEV ranking","Upgrade PR with AI-fixed breaking changes","Tests pass; auto-merge for low-risk bumps"],
 guard:["Tests must pass; no blind auto-merge of major versions","Verify the model's 'not reachable' claims for Critical/KEV issues"],
 metric:"MTTR for vulnerable dependencies; % upgrades merged without human effort",
 say:"Most dependency MTTR is upgrade friction, not detection. AI that fixes the breaking changes in the upgrade PR is what moves it."},
{id:"test",stage:"Test",title:"DAST and pentest acceleration",
 uses:["Generate authorization test matrices (roles × endpoints) from an OpenAPI spec","Write Nuclei templates or Burp extensions for a new CVE","Agent-assisted testing through Burp or MCP tools under human control"],
 flow:["OpenAPI spec + roles","LLM builds role × endpoint test matrix","Automated two-user tests in CI","Human tests the business logic","Findings verified by hand before reporting"],
 guard:["Strict scope and rate limits; no destructive actions in production","Every finding is reproduced by a human before it is reported","Keep client data inside approved tools"],
 metric:"% endpoints with authorization tests; pentest findings that automation already caught",
 say:"I use AI to generate the boring coverage, such as a role-by-endpoint authZ matrix, so manual time goes to business logic. Nothing gets reported until I've reproduced it."},
{id:"cloud",stage:"Deploy",title:"Cloud posture and IaC",
 uses:["Explain a CNAPP attack path in plain language for the owning team","Write the Terraform fix PR for a misconfiguration","Turn a written standard into Checkov or Rego policies"],
 flow:["CSPM finding","Map resource to IaC file and owner","LLM writes the IaC fix PR","Plan + policy checks","Merge; posture rescan closes it"],
 guard:["Fix in IaC, never with console changes","Policy tests for generated Rego; review least-privilege suggestions carefully"],
 metric:"Posture finding MTTR; % standards enforced as policy as code",
 say:"The win isn't finding misconfigurations; tools do that. It's generating the IaC fix PR for the right owner, which turns a dashboard into closed tickets."},
{id:"det",stage:"Operate",title:"Detection and incident response",
 uses:["Summarise and enrich alerts (who, what, related events)","Write detection queries from plain-language hypotheses","Draft incident timelines, stakeholder updates and post-mortems"],
 flow:["Alert","AI enrichment and summary","Analyst decides","Pre-approved automated containment for known patterns","AI drafts timeline and comms; human sends"],
 guard:["No autonomous containment beyond pre-approved playbooks","Logs contain personal data: approved tools and retention","Analysts verify AI-written queries before deploying"],
 metric:"MTTD, MTTA, analyst minutes per alert, false-positive rate per rule",
 say:"AI reduces time-to-understand for an alert. Containment stays in pre-approved playbooks, because a wrong automated action in production is its own incident."},
{id:"vm",stage:"Operate",title:"Vulnerability management at scale",
 uses:["Deduplicate the same issue reported by several tools","Map findings to owners from CODEOWNERS, service catalogue and git history","Write tickets with PoC, exact fix and SLA; nudge before SLA breach"],
 flow:["Findings from all tools","Dedupe and correlate","Owner mapping","Ticket with fix guidance + SLA","Verification rescan; metrics update"],
 guard:["Wrong owner mapping wastes days; let teams correct it and learn from corrections","Severity changes by AI need human approval"],
 metric:"Time to assign, MTTR by severity, SLA compliance",
 say:"Most MTTR is waiting, not fixing: waiting for triage, for an owner, for priority. I use automation and AI to remove each wait."},
{id:"bb",stage:"Operate",title:"Bug bounty and external reports",
 uses:["Detect duplicates and known issues","Extract clean reproduction steps and suggest a severity","Draft polite, specific replies to researchers"],
 flow:["Report arrives","Duplicate check + summary","Human reproduces","Severity and payout decided by a person","Reply drafted, edited, sent"],
 guard:["Payouts and severity are human decisions","Reports can contain prompt injection aimed at the triage bot"],
 metric:"Time to first response, time to triage, researcher satisfaction",
 say:"AI makes triage faster and replies kinder, but a human reproduces every bug and decides severity."},
{id:"grc",stage:"Improve",title:"Compliance and customer questionnaires",
 uses:["Answer security questionnaires from an approved knowledge base (RAG)","Map controls to evidence across SOC 2, ISO 27001 and PCI","Draft policies and control narratives"],
 flow:["Questionnaire uploaded","RAG answers from approved answers only","Owner reviews flagged answers","Sent to customer","New answers added to the library"],
 guard:["Never claim a control that isn't in place; answers come only from approved sources","Customer documents stay in approved tools"],
 metric:"Questionnaire turnaround; audit prep hours",
 say:"Questionnaires go from days to hours with retrieval over approved answers, and the rule is strict: if it isn't in the library, a human answers it."},
{id:"learn",stage:"Improve",title:"Training from your own bugs",
 uses:["Turn last quarter's real findings into short labs","Explain a vulnerability in the PR where it appears","Personalise training by stack and recurring mistakes"],
 flow:["Recurring finding class","Generate a lab from an anonymised real example","Push to the teams that hit it","Track recurrence afterwards"],
 guard:["Anonymise code and customer data","Validate generated labs actually work"],
 metric:"Recurrence rate by class after training",
 say:"Training built from our own bugs, delivered where developers already are, changes recurrence rates. Generic slides don't."}
];
window.AIRISKS = [
 ["Vulnerable AI-generated code","Assistants reproduce insecure patterns at scale","Same gates, secure rules files, tests"],
 ["Slopsquatting","Assistants suggest package names that don't exist; attackers register them","Private registry, allow-lists, SCA on install"],
 ["Data leakage","Code, secrets or customer data pasted into unapproved tools","Approved enterprise tools, DLP, clear policy"],
 ["Prompt injection into security tools","Repo content, PR text or bug reports manipulate the AI reviewer or triage bot","Treat inputs as untrusted; no secrets or merge rights for bots; human approval"],
 ["Automation bias","People stop checking AI verdicts","Measure precision/recall; spot-check; human sign-off for Critical"],
 ["Agent over-permission","Agents with broad tokens run destructive actions","Least-privilege tools, sandboxing, approvals, logging"],
 ["Model and vendor supply chain","Model or plugin compromise; data retention by vendors","Vendor review, data processing terms, pinned versions"]
];

// ---------- Metrics ----------
window.METRICS = [
 ["MTTR by severity","median(verified close − discovered), per severity","Is remediation working?","Use median and p90, not only the mean; 'closed' means verified by rescan or retest"],
 ["SLA compliance","findings closed within SLA ÷ findings due in the period","Is the process operating?","Also report open findings already past SLA, or old debt hides"],
 ["Escape rate","issues found after release (pentest, bounty, prod) that pre-release controls should catch ÷ all issues","Is shift-left working?","Define 'should have caught' per tool, or the number is arguable"],
 ["Recurrence rate","same class reappearing in the same codebase after a fix","Was the root cause fixed?","High recurrence means fix the class: library, template, rule"],
 ["MTTD / MTTA","time to detect / time to acknowledge an alert or incident","Is detection working?","Measure from first malicious event when known, not from alert time"],
 ["Coverage","% repos with SAST/SCA/secrets; % high-risk features threat modeled; % services on paved road","Where are the blind spots?","Coverage without tuned rules is vanity"],
 ["Tool false-positive rate","false positives ÷ triaged findings, per rule","Will developers trust the tool?","Track per rule; disable or tune rules above a threshold"],
 ["Exception health","open risk acceptances, their age and expiry","Is risk being parked?","Expired exceptions should escalate automatically"],
 ["Developer adoption","% findings fixed without security chasing","Is security self-serve?","The best leading indicator of culture change"]
];
window.MTTR_STAGES = [
 ["detect","Introduced → found",20,"Exposure before anyone knows"],
 ["triage","Found → triaged",5,"Is it real? How bad?"],
 ["assign","Triaged → owner",4,"Who owns this code?"],
 ["wait","Owner → work starts",12,"Sitting in the backlog"],
 ["fix","Work → fix merged",3,"Understanding and coding the fix"],
 ["verify","Merged → verified",3,"Rescan or retest"],
 ["deploy","Verified → in production",2,"Release cadence"]
];
window.MTTR_LEVERS = [
 ["shift","Scanners in every PR (shift left)",{detect:.8},"Finds issues at commit time instead of at the next pentest"],
 ["aitri","Tuned rules + AI-assisted triage",{triage:.6},"Removes the hours spent deciding whether a finding is real"],
 ["owner","Automatic owner routing (CODEOWNERS, service catalogue)",{assign:.75},"Tickets land with the right team immediately"],
 ["prio","Risk-based priority + SLAs inside sprint planning",{wait:.5},"Critical work stops losing to easy work"],
 ["poc","PoC + exact fix diff / autofix PR in every ticket",{fix:.4,wait:.2},"Developers spend minutes, not hours, understanding the fix"],
 ["champ","Security champions in each team",{triage:.15,wait:.15},"Questions answered inside the team"],
 ["reverify","Automatic verification by rescan in CI",{verify:.7},"No manual retest queue for most findings"],
 ["cd","Continuous deployment",{deploy:.6},"Fixes reach production the same day"],
 ["vpatch","Virtual patch (WAF/config) for Critical while fixing",{},"Doesn't change MTTR; shrinks the exposure window. Say this distinction in interviews"]
];
window.SAMPLE_FINDINGS = [
 ["F-101","Critical",3,9],["F-102","Critical",20,31],["F-103","High",5,22],["F-104","High",12,60],["F-105","High",30,48],["F-106","High",41,""],
 ["F-107","Medium",2,70],["F-108","Medium",15,85],["F-109","Medium",33,""],["F-110","Low",1,120],["F-111","Critical",88,""],["F-112","High",60,79]
];
window.SLA_DAYS = {Critical:7,High:30,Medium:90,Low:180};

// ---------- Architecture deep dives ----------
window.DESIGNS = [
{id:"authz",title:"Authorization for a multi-tenant B2B SaaS",
 prompt:"Design authorization for a B2B SaaS with 5,000 tenant companies, roles inside each tenant, sharing of documents between users, and admin support staff who sometimes need access.",
 clarify:["How many services need authorization decisions, and what latency budget?","Are permissions role-based only, or do users share individual objects?","Can tenants define custom roles?","What are the rules for support staff access (consent, time-limited, audited)?"],
 comps:["IdP issuing tokens with user and tenant","Policy decision point (OPA, Cedar, or OpenFGA/SpiceDB for relationships)","Policy enforcement in each service (library or sidecar)","Tenant-scoped data layer with database backstop (row-level security)","Audit log of decisions for sensitive actions","Break-glass flow for support"],
 answer:["Identity: tenant ID and user ID come only from the verified token, never from the request body or URL.","Model: RBAC inside a tenant for coarse permissions, ReBAC (Zanzibar-style relations) for sharing individual documents.","Decision: a central policy engine answers 'can user U do action A on resource R?'; services call it through a shared library with caching.","Enforcement: every data access goes through a tenant-scoped repository, with PostgreSQL row-level security as a second lock.","Support access: just-in-time, ticket-linked, time-boxed elevation with customer-visible audit, ideally with customer consent.","Testing: an authorization test suite in CI with two tenants and several roles per endpoint; deny-by-default for new endpoints.","Migration: shadow mode first (log decisions without enforcing), compare with current behaviour, then enforce."],
 trade:[["Central policy service","One source of truth, auditable, consistent","Network hop and availability dependency; needs caching"],["Library in each service","Fast, no extra hop","Policy drift between services and languages"],["Database row-level security","Strong backstop even if app code is wrong","Harder to debug; needs per-request tenant context"]],
 fail:["Policy service down: fail closed for writes; cached decisions for reads with short TTL","Cache staleness after role removal: short TTL plus event-driven invalidation","Tenant ID taken from a header by a new service: lint rule plus tests"],
 ai:"Use AI to generate the role × endpoint test matrix from the OpenAPI spec and flag endpoints with no policy call.",
 fu:["How do you handle a user in two tenants?","How do you migrate a monolith with scattered checks?","How do you prove to an auditor that support access is controlled?"],
 check:["Tenant from token only","Named an engine or pattern (OPA/Cedar/Zanzibar)","Defence in depth at the data layer","Support/break-glass design","Testing strategy","Failure mode and migration plan"]},
{id:"secrets",title:"Secrets management for 300 microservices",
 prompt:"Engineering has secrets in env files, CI variables and a few hard-coded configs across 300 services on EKS and Lambda. Design the target state and the migration.",
 clarify:["Which secret types: DB credentials, third-party API keys, signing keys, certificates?","Single cloud or multi-cloud?","What rotation is required by compliance?","Who owns the platform?"],
 comps:["Central secrets store (AWS Secrets Manager or HashiCorp Vault)","Workload identity (IRSA/Pod Identity, Lambda roles)","Secrets Store CSI driver / SDK fetch with caching","Rotation Lambdas or Vault dynamic secrets","Secret scanning in pre-commit, CI and history","KMS keys with separate admin and usage roles"],
 answer:["Remove secrets where possible: IAM database auth, OIDC federation for CI, workload identity for AWS APIs.","For the rest: one store, paths per service and environment, access granted to the service's own role only.","Delivery: mounted files via CSI driver or fetched at runtime with caching; never baked into images or plain env files.","Rotation: automatic for databases (or dynamic short-lived credentials with Vault); scheduled for third-party keys with overlap windows.","Detection: secret scanning with push protection; alert on secret access from unexpected roles (CloudTrail).","Migration: inventory with scanners, prioritise production and internet-facing, migrate per team with a template, then block new plaintext secrets in CI.","Incident path: leaked-secret runbook with rotation first, then usage review."],
 trade:[["AWS Secrets Manager","Managed, IAM-native, rotation built in","Per-secret cost; AWS-only"],["HashiCorp Vault","Dynamic secrets, multi-cloud, rich policies","Operational burden; must be highly available"],["Env variables","Easy","Leak through logs, crash dumps, /proc; avoid for sensitive values"]],
 fail:["Secrets store outage: cache with TTL; startup must not depend on a single call","Rotation breaks a service: dual-credential overlap and canary rotation","Over-broad access policies: per-service paths and automated policy linting"],
 ai:"Use AI to classify scanner hits (real secret vs test fixture) and to draft migration PRs per service.",
 fu:["How do you rotate a secret used by 40 services without downtime?","How do you handle a leaked secret in git history?","Where do signing keys live?"],
 check:["Eliminate secrets first","Workload identity","Delivery method","Rotation with overlap","Detection and push protection","Migration plan"]},
{id:"supply",title:"Secure CI/CD and software supply chain",
 prompt:"Design a CI/CD and supply chain security programme for 800 repositories on GitHub deploying to AWS.",
 clarify:["GitHub Actions only, or other CI too?","Public open-source repos as well?","How are deployments approved today?","Regulatory drivers (SOC 2, FedRAMP, customer SBOM requests)?"],
 comps:["Org-level GitHub rulesets: branch protection, required reviews, CODEOWNERS","Reusable, pinned workflow templates","OIDC federation to AWS roles scoped per repo and branch","Scanners: SAST, SCA, secrets, IaC, containers","SBOM + signing (Syft, cosign) and provenance (SLSA)","Admission control verifying signatures in EKS","Private package registry with upstream rules"],
 answer:["Source: rulesets enforce reviews and protected branches; CODEOWNERS on workflows and IaC.","Build: hardened reusable workflows teams import, third-party actions pinned to SHAs, minimal GITHUB_TOKEN, no secrets for untrusted PRs.","Identity: OIDC to AWS with trust policies bound to repo and branch; no long-lived cloud keys.","Dependencies: private registry proxy, lockfiles, dependency confusion protection, SCA with reachability.","Artefacts: SBOM per build, signed images, provenance attestation.","Deploy: only signed images from our registry admitted; production deploys only via the pipeline role.","Monitor: alerts on workflow changes, new self-hosted runners and unusual token use."],
 trade:[["Central reusable workflows","Consistency, one place to fix","Teams feel constrained; needs good docs"],["Per-team pipelines","Flexibility","Drift and gaps"],["Blocking gates everywhere","Strong control","Friction; start report-only and enforce the few that matter"]],
 fail:["Compromised maintainer token: required reviews plus signed commits for release branches","Malicious action update: SHA pinning and Dependabot for actions","Runner compromise: ephemeral runners, no persistent credentials"],
 ai:"AI reviews workflow changes for injection patterns and summarises dependency diffs on upgrades.",
 fu:["How does pull_request_target get abused?","What does SLSA level 3 require?","How would you have detected xz-style backdoors?"],
 check:["Source protections","Pipeline hardening","OIDC instead of keys","Dependency controls","Signing and admission","Monitoring of the pipeline itself"]},
{id:"aspm",title:"A vulnerability management platform to cut MTTR",
 prompt:"Findings come from 7 tools into 4 places. Critical MTTR is 45 days. Design the platform and process to get it under 10.",
 clarify:["Which tools and how many findings per month?","Is there a service catalogue or CODEOWNERS?","What ticketing system and sprint cadence?","What SLAs exist, and who approves exceptions?"],
 comps:["Ingestion and normalisation (ASPM such as ArmorCode/Apiiro, or DefectDojo)","Deduplication and correlation","Ownership mapping","Risk scoring: severity × exploitability (EPSS/KEV) × exposure × data","Ticketing integration with SLA dates","Verification by rescan","Dashboards and exception workflow"],
 answer:["Measure first: break the 45 days into stages (triage, assign, wait, fix, verify, deploy) to find where time goes.","Normalise every tool into one schema; dedupe so one root cause = one ticket.","Route to owners automatically from CODEOWNERS and the service catalogue.","Score risk with context, so the queue is ordered by real risk; Critical tickets get PoC and exact fix.","Integrate SLAs into sprint planning; nudge before breach; escalate after.","Verify automatically with rescans; close only on verification.","Report median and p90 MTTR by severity, SLA compliance and exceptions monthly."],
 trade:[["Buy an ASPM","Fast, many integrations","Cost; still needs process and ownership data"],["Build on DefectDojo + scripts","Cheap, flexible","Maintenance burden"],["Ticket everything","Visibility","Noise; ticket only above a risk threshold, batch the rest"]],
 fail:["Wrong owner mapping: let teams reassign and learn from it","Ticket floods: thresholds and grouping","Gaming the metric: measure verified closure and recurrence"],
 ai:"AI triage for true/false positives, autofix PRs, duplicate detection and owner suggestions; measure its accuracy.",
 fu:["How do you stop teams closing tickets that aren't fixed?","What if a team never meets SLA?","How do you report this to the board?"],
 check:["Measured stage breakdown first","Normalise and dedupe","Owner routing","Context-based risk","Verification before close","Metrics with median/p90"]},
{id:"zt",title:"Zero-trust service-to-service communication",
 prompt:"200 services across 3 AWS accounts and 2 regions talk over HTTP inside VPCs with no authentication. Design zero trust between them.",
 clarify:["EKS only, or also ECS, Lambda, EC2?","Is a service mesh acceptable?","Latency constraints?","Do calls need the end user's identity?"],
 comps:["Workload identity (SPIFFE IDs or IAM roles)","mTLS via service mesh (Istio, Linkerd, Cilium) or VPC Lattice with IAM auth","Authorization policies per service and method","User context propagation (token exchange or signed internal token)","Certificate authority with automatic rotation","Central telemetry of service calls"],
 answer:["Give every workload an identity it can prove, issued automatically.","Encrypt and authenticate every hop with mTLS; across accounts use PrivateLink or VPC Lattice.","Authorize at the destination: allow-list of calling services and methods, default deny.","Carry the user's identity separately: short-lived, audience-scoped tokens; the service checks both caller and user.","Roll out in permissive mode, observe the real call graph, then enforce per namespace.","Keep NetworkPolicies as a second layer and restrict egress."],
 trade:[["Service mesh mTLS","Transparent to apps, strong identity, telemetry","Operational complexity, sidecar or eBPF overhead"],["App-level signed tokens","No mesh needed","Every team must implement it correctly"],["VPC Lattice / IAM SigV4","AWS-native across accounts","AWS-specific; ties to IAM"]],
 fail:["CA outage: long enough cert lifetimes with alerts; HA CA","Policy too strict breaks calls: permissive-mode observation first","User token replay between services: audience-scoped tokens"],
 ai:"AI can turn observed traffic into a draft allow-list policy for review.",
 fu:["How do you handle Lambda or third-party callers?","How do you prevent a compromised service impersonating users?"],
 check:["Workload identity","mTLS","Destination authorization","User context propagation","Rollout via observe-then-enforce","Network layer as backup"]},
{id:"keys",title:"Encryption and key management (with customer-managed keys)",
 prompt:"Enterprise customers want data encrypted with keys they control (BYOK/HYOK) and the ability to revoke access. Design it.",
 clarify:["Which data: databases, files, backups, search indexes?","Do customers need to hold keys outside AWS (HYOK) or in our KMS (BYOK)?","Latency and cost constraints?","Regulatory requirements per region?"],
 comps:["KMS with per-tenant customer-managed keys (or external key store)","Envelope encryption with per-object data keys","Key policies granting our service roles use, customer controls the key","Caching of data keys with short TTL","Audit via CloudTrail shared with customer","Crypto-shredding for deletion"],
 answer:["Use envelope encryption: data keys per object or tenant, wrapped by the tenant's KMS key.","BYOK: the customer's key in their account with a grant to our role; revoking the grant stops new decrypts.","Cache data keys briefly to keep KMS calls and latency manageable; revocation takes effect when caches expire.","Cover every copy: backups, search indexes, analytics exports, logs, caches.","Give customers CloudTrail evidence of key use.","Deletion: crypto-shredding by destroying the tenant key."],
 trade:[["Per-tenant keys","Isolation, customer control","Cost, KMS limits, complexity"],["Shared platform key","Simple","No customer control or isolation"],["External key store (HYOK)","Maximum customer control","Availability depends on the customer"]],
 fail:["Customer revokes key: service fails closed for that tenant with clear errors","KMS throttling: data key caching, request limits","Plaintext copies in indexes/logs: data inventory and controls"],
 ai:"Use AI to inventory where tenant data is copied (from code and IaC), the usual gap in BYOK designs.",
 fu:["How long until a revocation takes effect?","How do you rotate keys without re-encrypting everything?"],
 check:["Envelope encryption","BYOK grant model and revocation","Caching trade-off","All data copies covered","Audit for customers","Fail-closed behaviour"]},
{id:"llmgw",title:"A secure enterprise LLM gateway",
 prompt:"The company wants every team to use LLMs (internal apps and agents) through one platform with guardrails, access control and RAG over internal data. Design it.",
 clarify:["Which model providers and where is data processed?","What data classes may go to which models?","Do agents need write actions on internal systems?","Who are the users: employees, customers, both?"],
 comps:["Gateway: authentication (SSO), per-team API keys, rate and cost limits","Policy layer: data classification, PII/secret redaction, allowed models per data class","RAG service with permission-aware retrieval","Tool/agent framework with scoped credentials and approvals","Logging of prompts, retrievals and tool calls (with retention rules)","Evaluation and red-team pipeline"],
 answer:["Single entry point: every call authenticated to a user or service; quotas and cost budgets per team.","Data controls: classify requests; redact secrets and PII; route sensitive data only to approved models or regions.","Retrieval enforces the caller's permissions at query time; never trust the model to hide data.","Agents: tools run with the end user's scoped permissions, destructive actions need human approval, outputs treated as untrusted.","Observability: full trace per request; alerts on abuse patterns and injection attempts.","Assurance: evaluation suites for prompt injection and data leakage before each release; vendor and data-processing review."],
 trade:[["Central gateway","Consistent controls, visibility, cost management","Bottleneck risk; must be fast and reliable"],["Teams call providers directly","Speed","No consistent controls or audit"],["Strict redaction","Lower leakage","Can break legitimate use; tune by data class"]],
 fail:["Indirect prompt injection via retrieved docs: content tagging, tool approvals","Gateway outage: graceful degradation","Logs become a sensitive data store: access control and retention"],
 ai:"This is an AI system itself: the security work is the OWASP LLM Top 10 applied at platform level.",
 fu:["How do you stop a user retrieving documents they can't open in the source system?","How do you evaluate a new model before allowing it?"],
 check:["Authn and quotas","Data classification and redaction","Permission-aware retrieval","Agent tool scoping and approvals","Logging with retention controls","Evaluation/red-teaming"]},
{id:"detect",title:"Application security logging and detection pipeline",
 prompt:"Design how 150 services produce security events and how the company detects application-layer attacks (account takeover, IDOR enumeration, abuse).",
 clarify:["Existing SIEM?","Volume per day?","Who responds: SOC, AppSec, both?","Privacy requirements for logs?"],
 comps:["Logging standard and shared library (structured JSON, fixed security event types)","Collection pipeline (Fluent Bit/Firehose) to SIEM and cheap storage","Enrichment: user, tenant, geo, device","Detections as code with tests","SOAR playbooks for safe automated actions","Dashboards and metrics (MTTD, FP rate)"],
 answer:["Define security events every service must emit: auth success/failure, authZ denial, admin action, sensitive data export, config change.","Ship through a shared library so the format is consistent, with redaction of secrets and PII.","Route high-value events to the SIEM, everything to low-cost storage for investigations.","Write detections as code: stuffing patterns, enumeration (one user, many object IDs), impossible travel, privilege changes.","Automate safe responses (rate-limit, step-up auth); humans decide account locks for VIPs.","Measure MTTD and per-rule false-positive rate; review rules monthly."],
 trade:[["Everything into SIEM","Simple search","Very expensive"],["Tiered storage","Cheaper","Two places to query"],["Auto-response","Speed","Risk of blocking real users; start with challenges, not blocks"]],
 fail:["Logging library not adopted: make it the default in templates","Logs leaking secrets: redaction tests in CI","Alert fatigue: per-rule FP tracking"],
 ai:"AI summarises alerts and writes queries from hypotheses; analysts verify before deploying.",
 fu:["How would you detect IDOR enumeration?","What would you never log?"],
 check:["Event standard","Shared library + redaction","Storage tiering","Detections as code","Safe automation","Metrics"]},
{id:"api",title:"Security for a public API platform",
 prompt:"You're launching a public API used by thousands of developers and partner integrations. Design authentication, authorization, abuse prevention and lifecycle.",
 clarify:["Server-to-server, user-delegated, or both?","Webhooks too?","Pricing tiers and quotas?","Sensitive operations (payments, data export)?"],
 comps:["API gateway","OAuth 2.0: client credentials and authorization code + PKCE; scoped tokens","API keys only for low-risk public data, with prefixes for secret scanning","Rate limits and quotas per client and per user","Schema validation and versioning","Webhooks signed with HMAC","Developer portal with key rotation and audit logs"],
 answer:["Authentication: OAuth with fine-grained scopes; keys are identifiable (prefixes) so leaks can be detected by secret scanners.","Authorization: object-level checks in every endpoint, scopes checked at gateway and service.","Abuse: rate limits per client, user and IP; quotas; anomaly detection; bot controls on signup.","Input: schema validation from the OpenAPI spec; request size limits; pagination caps.","Lifecycle: versioning, deprecation, inventory of every endpoint (no shadow APIs).","Customer trust: audit logs, key rotation, IP allow-lists for enterprise customers."],
 trade:[["API keys","Simple for developers","Long-lived, no user context; need rotation and scanning"],["OAuth","Scoped, revocable, user-delegated","More complex for developers"],["mTLS for partners","Strong client authentication","Certificate management burden"]],
 fail:["Leaked key on GitHub: secret scanning partner programme, automatic revocation","Credential stuffing on token endpoint: rate limits, MFA for console","Mass data export: anomaly alerts, per-scope limits"],
 ai:"AI generates authZ test matrices from the spec and detects anomalous usage patterns.",
 fu:["How do you find shadow or zombie APIs?","How would you design API key formats?"],
 check:["OAuth scopes vs keys","Object-level authZ","Rate limits and quotas","Schema validation","Inventory/versioning","Webhook signing"]},
{id:"mna",title:"Securing an acquired product",
 prompt:"Your company acquires a startup with a SaaS product and 40 engineers. Design the security integration for the first six months.",
 clarify:["Will the product be merged or run separately?","What customer data does it hold?","Compliance commitments to existing customers?","Timeline for integrating identity and networks?"],
 comps:["Due diligence findings","Rapid assessment: external attack surface, cloud posture, code scanning, secrets","Identity integration (SSO, offboarding)","Network isolation until assessed","Vulnerability backlog with SLAs","Roadmap to company baseline"],
 answer:["Day 0: inventory assets and external surface; rotate shared credentials; enforce MFA and SSO.","Keep networks isolated from the parent until assessed; connect through controlled points.","First 30 days: CSPM, secret scanning, SCA and SAST across repos; pentest the main product.","Prioritise criticals with the acquired team's leads; agree SLAs and a joint backlog.","Days 30-180: bring them onto the paved road and pipeline templates, run threat models for key features, train champions.","Report progress against the company baseline to leadership monthly."],
 trade:[["Fast full integration","Consistency quickly","Risk of importing their exposure into the parent"],["Long isolation","Contains risk","Slows business integration and creates duplicate tooling"]],
 fail:["Unknown shadow assets: external attack surface scanning","Key people leaving: document access and ownership early"],
 ai:"AI helps summarise an unfamiliar codebase and map data flows quickly.",
 fu:["What would you check before the deal closes?","How do you handle their open customer commitments?"],
 check:["Immediate identity and credential actions","Isolation","Rapid scanning and pentest","Joint backlog with SLAs","Path to baseline","Leadership reporting"]}
];

// ---------- Story bank (from the user's own PDFs) ----------
window.STORYBANK = [
{id:"prog",title:"Built and owned a security programme from scratch",q:"Have you built a programme, not just executed tasks?",src:"ProductSec Transition Stories · Story 1",
 s:"Embedded security owner for a product company. Security was reactive: annual third-party pentest, no SAST, default cloud alerts only, no vulnerability SLA, no developer training.",
 t:"Design and build a continuous programme across the SDLC that prevents issues at source and measures improvement.",
 a:"Three layers. Shift-left: Semgrep with custom rules and OWASP Dependency-Check in CI with severity gates (CVSS 9.0+ blocks; 7-8.9 gets a 48-hour SLA), gitleaks on every commit. Detection: Graylog/Wazuh rules for the app's attack patterns, auto-block after 10 failures. Measurement: dashboard for escape rate, MTTR by severity and recurrence; monthly to engineering lead, quarterly to CISO.",
 r:"Over two quarters escape rate dropped ~40%, MTTR trended down, SOC 2 Type II passed with zero security findings. Metrics became engineering OKRs.",
 nums:["~40% escape-rate reduction","SOC 2 Type II, zero security findings"]},
{id:"sast",title:"SAST from noise to signal",q:"How do you get developers to act on findings without friction?",src:"Transition Stories · Story 2",
 s:"After integrating Semgrep and SonarQube, the false-positive rate was ~38%. Two engineering leads asked to remove the gate within three weeks.",
 t:"Cut false positives enough that developers trust the tool, without removing the gate.",
 a:"Two-week tuning sprint: triaged a month of findings into true positive and FP causes (custom sanitiser, framework protection, dead code). Disabled rules above 15% FP on this codebase, added suppressions for known-safe wrappers, linked every CI failure to a runbook, and ran fortnightly 15-minute SAST office hours.",
 r:"FP rate ~38% to ~8% in three weeks. Escalations went from daily to near zero; the gate has run 12+ months without push-back. Developers began self-correcting injection patterns.",
 nums:["38% → 8% FP"]},
{id:"siem",title:"SIEM ownership: alerts into decisions",q:"How do you run detection and response at a product company?",src:"Transition Stories · Story 3",
 s:"Graylog and Wazuh deployed but unused: ~200 alerts/day, ~85% noise. The queue was ignored.",
 t:"Make the SIEM an operational detection layer.",
 a:"Two weeks categorising alerts; suppressed the top 10 noise sources. Wrote rules for the threat model: enumeration, distributed credential stuffing, API abuse (one user hitting >500 endpoints in 5 minutes). Wazuh FIM on configs and secrets store. Five-step runbook per alert. Auto-block after 10 failed logins in 60 seconds. Tracked MTTD and FP per rule.",
 r:"~200 → ~35 alerts/day; <12% FP on custom rules. Auto-block stopped 3 brute-force attempts in month one. Found a credential-stuffing campaign running undetected for 6 weeks; MTTD for that class went to under 4 minutes.",
 nums:["~200 → ~35 alerts/day","<12% FP on custom rules","6-week stuffing campaign found"]},
{id:"soc2",title:"Owned SOC 2 application security controls",q:"Did you own compliance or just tick boxes?",src:"Transition Stories · Story 4 / Behavioral PDF R5",
 s:"First SOC 2 Type II. The AppSec controls section (CC6, CC7) had no processes, evidence, SLA policy or vulnerability workflow. Audit in six months.",
 t:"Design controls that operate continuously for a Type II audit.",
 a:"Gap analysis found 7 control gaps. Wrote the vulnerability SLA policy (Critical 7, High 30, Medium 90 days) with CISO-signed exceptions, the testing procedure and quarterly access reviews. Built Graylog dashboards as CC7 evidence and automated SAST coverage reports per release. Pre-audit walkthrough closed two access-review gaps 8 weeks early.",
 r:"Passed with zero security findings; the auditor noted the SLA policy and automated SAST evidence. The exception process was used three times, proving it operated.",
 nums:["7 control gaps closed","0 security findings"]},
{id:"vm",title:"Ran the vulnerability management programme",q:"How do you prioritise and govern vulnerabilities at scale?",src:"Transition Stories · Story 5 / HQ1",
 s:"80+ open findings; high-severity items open 60+ days while easy low-severity ones got closed.",
 t:"Fix the right findings in the right order with SLAs and governed exceptions.",
 a:"Priority = CVSS × reachability × business impact (a CVSS 7 IDOR on payments beats a CVSS 9 XSS on an admin debug page). Three-question triage: reachable from untrusted input? what's exposed? compensating control? SLA policy, formal exceptions with CISO sign-off and auto re-escalation after 30 days. Monthly leadership report.",
 r:"High/critical SLA compliance from unmeasured to 87% in a quarter; critical MTTR ~9 days vs 60+ before; 4 governed exceptions.",
 nums:["87% SLA compliance","critical MTTR ~9 days"]},
{id:"mttr",title:"How you actually measured MTTR",q:"How exactly did you measure that? What was the before number?",src:"Transition Stories · Part 5B",
 s:"No systematic tracking: findings lived in PDF reports and email; no single owner of the lifecycle.",
 t:"Make remediation time measurable and bring it down.",
 a:"Built an internal tracking dashboard (discovery date, severity, owner, status, verified closure). Reconstructed a rough before-baseline from two quarters of reports. Changed three things: CVSS × reachability priority, PoC + exact fix diff in every finding, SLAs tracked in the tool. 'Closed' meant retest-verified.",
 r:"High-severity findings went from routinely 6-10 weeks open to closing inside the 7-day critical SLA at ~87-91% compliance. You don't quote a precise percentage because the baseline was reconstructed, which shows measurement maturity.",
 nums:["6-10 weeks → within 7-day SLA","87-91% compliance"]},
{id:"tm7",title:"Threat model that killed a bug before code existed",q:"How do you embed security in design?",src:"Transition Stories · Story 7 / Behavioral PDF R3",
 s:"New file-sharing feature: user-supplied filename resolved against a shared S3 bucket. No security checkpoint in design review.",
 t:"Remove the risk before development.",
 a:"Used the 30-minute design-review checkpoint you introduced; ran STRIDE on the data flow; drew the traversal path (filename=../../other-user/doc.pdf) live. Recommended pre-signed URLs with server-generated object keys.",
 r:"Design changed before sprint planning; zero vulnerable code written; you became a standing invitee to design reviews.",
 nums:["~3 sprints of refactoring avoided (estimate)"]},
{id:"cve",title:"CVE-2023-2240 root cause and disclosure",q:"Walk me through your CVE.",src:"Behavioral PDF · Sq5 / R4",
 s:"Assessing Microweber CMS RBAC through code review and black-box testing.",
 t:"Find whether server-side role checks matched the UI.",
 a:"Mapped subscriber-accessible endpoints; replayed admin API calls with a subscriber token. Found role checks only in front-end routing; the role-update controller accepted role:'admin' without re-checking the caller (BFLA, OWASP API5). Reported privately via GitHub advisory with PoC and a 90-day window.",
 r:"Patched within the window; CVE assigned. Senior close: what would have prevented it is authorization enforced in the controller layer plus role-matrix tests.",
 nums:["CVE-2023-2240","CVE-2023-2014"]},
{id:"kube",title:"Runtime least privilege with KubeArmor and Cilium",q:"What did you actually enforce at AccuKnox?",src:"Behavioral PDF · R1",
 s:"Customer Kubernetes workloads had no runtime controls; one compromised container could reach any service.",
 t:"Contain blast radius even if a container is fully compromised.",
 a:"KubeArmor policies limiting each workload's processes, file paths and network; Cilium identity-based policies (for example the payment service could reach only the database on 5432).",
 r:"Microsegmentation in place so a container compromise had minimal lateral movement; K8s CVE analysis fed policy updates. Add a number here only if you have a real one.",
 nums:[]}
];
window.CONFLICTS = [
 ["MTTR reduction","Behavioral PDF (Sq2) says '~35% MTTR reduction', and high-sev MTTR '45-60 days → ~30-35 days'.","Transition Stories (Part 5B) says not to quote a percentage because the baseline was reconstructed, and that critical findings now close inside the 7-day SLA. Story 5 says critical MTTR ~9 days.","Pick one version. The Part 5B framing is the safest under probing."],
 ["SIEM false-positive numbers","Story 3: ~85% noise, <12% FP on custom rules.","Behavioral PDF R2: FP rate ~80% → ~25%.","These may be different clients; if so, say which. Otherwise choose one."],
 ["Scale of the work","Behavioral PDF Sq1: '50+ client applications' and 'client delivery practice'.","Transition Stories: one long-term embedded client as the security owner.","Both can be true; be explicit about which story is portfolio-wide and which is the embedded client."],
 ["SOC 2 company type","Behavioral PDF R5: an e-commerce client.","Transition Stories Story 4: '[financial services / SaaS / healthcare]' placeholder.","Use the real industry consistently."]
];
window.LANG = [
 ["I was the external security provider for a client.","I was the embedded security owner for a product company, responsible for its end-to-end security across the SDLC, CI/CD, detection and compliance."],
 ["I delivered a pen test report.","I ran assessments inside a continuous programme I owned; findings went straight into the sprint backlog I co-managed with the engineering lead."],
 ["The client used Semgrep and SonarQube.","I designed and maintained the SAST pipeline: Semgrep custom rules plus SonarQube, with severity gates I defined."],
 ["I supported their SOC 2 audit.","I owned the application security controls for SOC 2 Type II: I designed the evidence, wrote the SLA policy, and the audit passed with zero security findings."],
 ["I found vulnerabilities in their systems.","I tracked vulnerability trends over time (escape rate, MTTR, recurrence) and drove the changes that moved them."],
 ["I gave them recommendations.","I owned the remediation pipeline: co-triaged with engineering, set SLAs, tracked closure and reported KPIs monthly."],
 ["We improved their security posture.","I built a tracking tool that made remediation time measurable, then changed prioritisation, fix guidance and SLAs; closure times came down quarter over quarter."]
];
window.FRAMEWORK = ["Scale and context: how many apps, users, findings; what was at risk (numbers first)","Architecture end to end: how data and work flowed, components, trade-offs you weighed","Outcome: the measurable result, how you measured it, and what you'd do differently"];

// ---------- extra question bank entries ----------
window.QB2 = [
{c:"Web",q:"What is the CIA triad, and how does it map to STRIDE?",a:"Confidentiality, Integrity, Availability: the three properties security protects. STRIDE threats each violate a property: information disclosure breaks confidentiality, tampering breaks integrity, denial of service breaks availability; spoofing, repudiation and elevation of privilege map to authentication, non-repudiation and authorization.",p:["Some add authenticity and non-repudiation (Parkerian hexad)"],f:"Give one control for each of C, I and A in a payments API."},
{c:"Web",q:"What is HTTP Parameter Pollution?",a:"Sending the same parameter more than once (id=1&id=2) so different components (WAF, framework, backend) pick different values, which can bypass validation or authorization checks.",p:["Frameworks differ: first, last, or array","Fix: reject duplicate parameters for security-relevant fields; parse once at the edge"],f:"How could HPP bypass a WAF?"},
{c:"Web",q:"Explain CRLF injection.",a:"Injecting carriage-return/line-feed characters into values placed in HTTP headers or logs, letting an attacker add headers (Set-Cookie), split the response, or forge log lines.",p:["Fix: reject or encode CR/LF in header values; modern frameworks block it","Log injection: encode newlines in log fields"],f:"How can CRLF lead to session fixation?"},
{c:"Web",q:"What is prototype pollution in JavaScript?",a:"Merging attacker-controlled JSON into objects lets them set __proto__ or constructor.prototype properties, which then appear on every object, changing app logic or leading to XSS or RCE through gadgets.",p:["Common in deep-merge, set-by-path and query parsers","Fix: block __proto__/constructor/prototype keys, use Object.create(null) or Map, freeze prototypes, patched libraries"],f:"How could it bypass an isAdmin check?"},
{c:"Web",q:"LFI vs RFI vs directory traversal?",a:"Directory traversal reads files outside the intended folder (../). Local file inclusion makes the app include and often execute a local file. Remote file inclusion includes a file from an attacker-controlled URL, usually leading to RCE.",p:["LFI can become RCE via log poisoning or upload","Fix: never pass user input to include/require; map IDs to files; canonicalise paths"],f:"How does LFI become RCE?"},
{c:"Web",q:"How can CSRF protection be bypassed even with a token present?",a:"When the token isn't validated on every method, isn't tied to the session, is accepted if missing, can be leaked (Referer, logs), or when method override or Lax SameSite top-level GETs perform state changes. Subdomain takeover or XSS also defeat it.",p:["Double-submit cookie pattern fails if an attacker can set cookies from a subdomain","Check Origin/Referer as an extra layer"],f:"What is the double-submit cookie pattern and its weakness?"},
{c:"Web",q:"Which HTTP methods matter for security?",a:"GET should be safe; POST/PUT/PATCH/DELETE change state and need CSRF protection and authorization. OPTIONS reveals allowed methods and is used for CORS preflight. TRACE enabled can echo headers (historic cross-site tracing). Unexpected PUT/DELETE on static servers can allow file upload or deletion.",p:["Method override headers (X-HTTP-Method-Override) can bypass controls","Authorization must be per method, not per path"],f:"How can a method override bypass a WAF rule?"},
{c:"Web",q:"How do you send many requests at the same instant to test a race condition?",a:"Use the single-packet attack: queue multiple HTTP/2 requests and release their final bytes together so they arrive within a millisecond (Burp Repeater group send or Turbo Intruder). Over HTTP/1.1, last-byte synchronisation does something similar.",p:["Test coupons, transfers, limits, invitations, OTP checks"],f:"How do you fix the race you found?"},
{c:"Web",q:"Horizontal vs vertical privilege escalation?",a:"Horizontal: acting on another user's data at the same level (IDOR/BOLA). Vertical: gaining a higher role's functions, such as a user calling admin APIs (broken function-level authorization).",p:["Test both with a role × endpoint matrix and two users per role"],f:"Which did your CVE-2023-2240 demonstrate?"},
{c:"Web",q:"REST vs SOAP vs GraphQL: security differences?",a:"REST relies on HTTP semantics, tokens and per-endpoint authorization. SOAP uses XML and WS-Security, so XXE and XML signature issues apply. GraphQL has one endpoint, so authorization must be per field and resolver, and query depth, cost and batching need limits.",p:["All three need object-level authorization"],f:"What extra testing does a SOAP service need?"},
{c:"Web",q:"Can HttpOnly be bypassed?",a:"The cookie value can't be read by script, but XSS can still make authenticated requests from the victim's browser, so impact remains. Values can also leak through debug pages that echo headers, TRACE (historic), or server-side reflection.",p:["Fix the XSS; HttpOnly limits theft, not abuse"],f:"What does an attacker do with XSS if they can't steal the cookie?"},
{c:"Networking",q:"Which port numbers should a security engineer know?",a:"21 FTP, 22 SSH, 23 Telnet, 25 SMTP, 53 DNS, 80/443 HTTP/S, 110/143 POP3/IMAP, 389/636 LDAP/LDAPS, 445 SMB, 1433 MSSQL, 1521 Oracle, 3306 MySQL, 3389 RDP, 5432 PostgreSQL, 6379 Redis, 9200 Elasticsearch, 27017 MongoDB, 2375/2376 Docker API, 6443 Kubernetes API, 10250 kubelet.",p:["Exposed Redis, Elasticsearch, Docker API and kubelet are classic breach causes"],f:"Which of these should never face the internet, and why?"},
{c:"Networking",q:"DNS vs DHCP?",a:"DNS resolves names to addresses (UDP/TCP 53). DHCP assigns IP configuration to hosts (UDP 67/68) through discover, offer, request, acknowledge.",p:["Rogue DHCP servers can redirect traffic by handing out a malicious gateway or DNS server"],f:"How does a rogue DHCP server enable MITM?"},
{c:"Networking",q:"Which nmap options do you use and why?",a:"-sS SYN scan, -sV service versions, -sC default scripts, -O OS detection, -p- all ports, -Pn skip host discovery, -T timing, -oA save output. Scripts (NSE) for specific checks.",p:["Scan only in scope and with permission; rate-limit in production"],f:"How would you scan a large cloud range efficiently?"},
{c:"Networking",q:"Lateral movement vs pivoting?",a:"Lateral movement is moving between systems using credentials or trust (pass-the-hash, stolen tokens, SSH keys). Pivoting is routing your traffic through a compromised host to reach networks you can't reach directly (SOCKS proxies, tunnels).",p:["In cloud: role assumption chains and SSM are lateral movement"],f:"How do segmentation and identity controls limit each?"},
{c:"Mobile",q:"What are the Android components and their security risks?",a:"Activities, Services, Broadcast Receivers and Content Providers. If exported without permissions, other apps can launch screens, start services, send broadcasts or read and write provider data, and intents can carry malicious input.",p:["Check android:exported and permissions in the manifest","Test with adb am start / drozer; validate intent extras","Pending intents and deep links are common sources of bugs"],f:"How would you exploit an exported activity that skips the login screen?"},
{c:"Mobile",q:"What does a jailbroken iOS device let a tester do?",a:"Inspect the app sandbox and Keychain, hook functions at runtime with Frida, bypass pinning and jailbreak detection, and decrypt the app binary for static analysis.",p:["Many tests now use rootless jailbreaks or Frida gadget injection on non-jailbroken devices"],f:"What should never be stored even in the Keychain?"},
{c:"Mobile",q:"How do you test a thick (desktop) client?",a:"Map its traffic (proxy, or hook TLS), find local storage of credentials and configs, check DLL or library hijacking and update mechanisms, reverse engineer binaries or Electron app.asar bundles, and test the backend APIs directly.",p:["Electron: nodeIntegration, contextIsolation, unsafe preload bridges","Auto-update without signature checks is a frequent critical"],f:"What makes Electron apps risky?"},
{c:"Detection & IR",q:"Describe a SIEM architecture.",a:"Collectors/agents and log shippers send events to a parsing and normalisation layer, then indexing and storage; a correlation engine runs rules and analytics; alerts go to case management or SOAR; dashboards and reports sit on top.",p:["QRadar, Splunk, Elastic and Sentinel follow this pattern","Cost and retention design matter as much as rules"],f:"How do you decide which logs go to the SIEM?"},
{c:"Detection & IR",q:"EDR vs XDR vs SIEM?",a:"EDR watches endpoints for malicious behaviour and can isolate hosts (CrowdStrike, Defender). XDR correlates across endpoints, identity, email and cloud in one vendor platform. A SIEM collects logs from everything for correlation, search and compliance.",p:["AppSec mostly cares about app and cloud telemetry feeding these"],f:"Where does an application security event fit?"},
{c:"Cloud",q:"What do secret vaults like HashiCorp Vault or CyberArk Conjur add over a simple secrets store?",a:"Dynamic short-lived credentials generated on demand (for databases or cloud), fine-grained policies, leasing and revocation, identity-based access for workloads, and audit trails.",p:["Dynamic secrets remove long-lived passwords entirely","Operational burden: must be highly available"],f:"When would you choose Vault over AWS Secrets Manager?"},
{c:"Vuln management",q:"CVE vs CWE vs CVSS vs EPSS vs KEV?",a:"A CVE identifies a specific vulnerability in a product. A CWE is the weakness class (CWE-89 SQL injection). CVSS scores technical severity. EPSS estimates the probability of exploitation in the next 30 days. CISA KEV lists vulnerabilities known to be exploited.",p:["Prioritise: KEV first, then high EPSS with exposure, then CVSS"],f:"A CVSS 9.8 has EPSS 0.1% and is internal-only. Priority?"},
{c:"Vuln management",q:"What changed in CVSS v4.0?",a:"v4.0 adds Attack Requirements, splits impact into vulnerable-system and subsequent-system impacts (replacing Scope), refines User Interaction (passive/active), and encourages Threat and Environmental metrics so scores reflect real context (named CVSS-B, CVSS-BT, CVSS-BE, CVSS-BTE).",p:["Many tools and programmes still use 3.1; know both"],f:"Why was Scope removed?"},
{c:"Vuln management",q:"How do you score a finding with CVSS without over-inflating it?",a:"Score the vulnerability as it actually exists: attack vector and privileges as an attacker would really need them, scope change only when impact crosses a security authority, and impact on what's actually reachable. Then adjust priority with context separately from the base score.",p:["Common inflation: marking Scope Changed for every XSS, assuming High confidentiality without evidence"],f:"Score a stored XSS in an admin-only page."},
{c:"AI for security",q:"How would you use AI to reduce MTTR?",a:"Break MTTR into stages and apply AI where time is lost: triage (true/false positive with code context), ownership routing, ticket quality (PoC and exact fix), autofix PRs, and dependency upgrade PRs that fix breaking changes. Measure each stage before and after, and keep humans approving Critical decisions.",p:["Most MTTR is waiting, not fixing","Track AI precision against human labels"],f:"Which stage would you start with and why?"},
{c:"AI for security",q:"How do you evaluate an AI triage or AI code review tool before trusting it?",a:"Build a labelled set from your own past findings, measure precision and recall against human verdicts, check behaviour on your frameworks and custom sanitisers, test it against prompt injection in code and PR text, and review data handling. Start in advisory mode and track agreement over time.",p:["Measure per vulnerability class, not one overall number"],f:"What precision would you require before auto-suppressing findings?"},
{c:"AI for security",q:"What new risks do AI coding assistants bring to the SDLC?",a:"More code with familiar insecure patterns, hallucinated or typosquatted packages (slopsquatting), secrets or proprietary code sent to external services, over-trust in generated code, and assistants with tool access acting on untrusted repo content.",p:["Controls: same gates, package allow-lists, approved tools, rules files with secure patterns"],f:"How would you write a policy for AI coding assistants?"},
{c:"AI for security",q:"Can a malicious repository attack your AI security tools?",a:"Yes. Comments, READMEs, PR descriptions or bug reports can contain prompt injection telling an AI reviewer to approve code or leak data. Treat all repository content as untrusted input, give bots no secrets or merge rights, and require human approval for decisions.",p:["Same lesson as indirect prompt injection in any agent"],f:"How would you test your AI reviewer for this?"},
{c:"AI for security",q:"How do you use AI agents for pentesting safely?",a:"Keep a human in control: strict scope lists, rate limits, no destructive actions, tools with least privilege, full logging, and manual reproduction of every finding before reporting. Use agents for breadth (enumeration, test matrices) and humans for business logic.",p:["Example: Burp MCP with an LLM for traffic analysis, with the tester approving actions"],f:"What would you never let an agent do on a client engagement?"},
{c:"Metrics",q:"How do you calculate MTTR correctly?",a:"Per severity, from discovery to verified closure. Report the median and p90, not only the mean, because a few very old findings distort averages. Exclude or separately report risk-accepted items, and show open findings past SLA alongside.",p:["Define 'discovered' per source (scan date, report date)","Define 'closed' as verified, not 'developer said fixed'"],f:"Why can MTTR improve while risk gets worse?"},
{c:"Metrics",q:"Your before-state wasn't measured. How do you talk about improvement honestly?",a:"Say so. Explain that measuring it was part of the problem, describe the tool you built, how you reconstructed a rough baseline, and the after-state you can show (for example SLA compliance). Avoid precise percentages based on reconstructed data.",p:["This shows measurement maturity, which is a senior signal"],f:"What exactly did your tracking tool record?"},
{c:"Metrics",q:"What's the difference between MTTR and SLA compliance, and why report both?",a:"MTTR shows typical speed; SLA compliance shows whether commitments are met. MTTR can look good while a few criticals sit open for months; SLA compliance plus 'open past SLA' exposes that.",p:["Add exception counts so parked risk is visible"],f:"Which would you show a CISO first?"},
{c:"Metrics",q:"Leading vs lagging security indicators?",a:"Lagging indicators show outcomes after the fact: incidents, escape rate, pentest findings. Leading indicators predict them: coverage of scanning and threat modeling, paved-road adoption, champion coverage, time to triage.",p:["Manage with leading indicators; prove value with lagging ones"],f:"Give two leading indicators for an AppSec programme."},
{c:"Programme",q:"What would you do in your first 30/60/90 days?",a:"Days 1-30: listen and map (tools, real alert volumes, last pentests, developer pain), no big changes, write a current-state assessment. Days 31-60: quick wins that build trust (tune noisy SAST, fix templates for top recurring classes, SLA policy). Days 61-90: programme structure (gates, threat model checkpoint, monthly metrics) and a 12-month roadmap to leadership.",p:["Earn trust before enforcing"],f:"What would you NOT change in the first month?"},
{c:"Programme",q:"You worked as an external provider. Why should we believe you can own product security?",a:"Explain that you were the embedded security owner of a client's programme: you designed the pipeline, SIEM rules and SLA policy, owned remediation with engineering and reported KPIs to leadership. Acknowledge what you didn't see (internal politics, budgets), then point out that driving change with no authority is the core product-security skill.",p:["Use product-owner language, not consultant language"],f:"How did you influence engineers you couldn't escalate to?"},
{c:"Architecture",q:"How do you review an architecture you've never seen in 45 minutes?",a:"Ask for one request walked end to end; draw it with trust boundaries; find where identity is established and checked at each hop; identify sensitive data stores and who can reach them; look at third parties and admin paths; then list the top three risks with controls, and what you'd verify later.",p:["Breadth first, depth where risk is highest","Say your assumptions out loud"],f:"What are the first three questions you ask?"},
{c:"Architecture",q:"How do you design for data residency in a multi-region SaaS?",a:"Keep each region's customer data and backups in-region, route users to their home region, keep keys per region, restrict cross-region replication and admin access, and make logs, analytics and support tools respect the same boundaries.",p:["The usual leaks are logs, analytics pipelines, search indexes and support tooling"],f:"How do support engineers in another country access data legally?"},
{c:"Architecture",q:"How would you design break-glass access to production?",a:"Just-in-time elevation through an access tool, tied to an incident or ticket, time-limited, with MFA, session recording, automatic alerts to security and a post-use review. Emergency accounts stored offline with monitoring for any use.",p:["Regular drills so it works under pressure"],f:"How do you stop break-glass becoming the normal path?"}
];
