// ===================== v4: every remaining question from the user's PDFs + coverage index =====================
window.QB3 = [
{c:"Cryptography",src:"Q&A PDF Q1",q:"What is cryptography in cybersecurity, and what does it give you?",a:"Mathematical techniques that provide confidentiality (encryption), integrity (hashes and MACs), authentication (signatures, MACs) and non-repudiation (signatures). Symmetric ciphers (AES) protect bulk data, asymmetric algorithms (RSA, ECC) handle key exchange and signatures, hash functions (SHA-256) check integrity. TLS, SSH and JWT are all built from these primitives.",p:["Use vetted libraries; never design your own algorithms","MD5 and SHA-1 are broken for collision resistance; don't use them for signatures"],f:"Which property does a digital signature give that a MAC doesn't?"},
{c:"Mobile",src:"Q&A PDF Q5",q:"How should TLS be handled in mobile apps?",a:"Enforce TLS 1.2+ and block cleartext traffic (Android network_security_config, iOS App Transport Security). For high-risk apps add certificate or public-key pinning (OkHttp CertificatePinner, URLSession delegate) with backup pins and a rotation plan. Testers bypass pinning with Frida or objection, so the backend must not rely on it.",p:["Pin public keys, not leaf certificates, to survive renewals","Never ship a debug 'trust all certificates' setting"],f:"How do you rotate pins without breaking old app versions?"},
{c:"Web",src:"Q&A PDF Q8",q:"List the OWASP Top 10 (2021) categories.",a:"A01 Broken Access Control, A02 Cryptographic Failures, A03 Injection (including XSS), A04 Insecure Design, A05 Security Misconfiguration (including XXE), A06 Vulnerable and Outdated Components, A07 Identification and Authentication Failures, A08 Software and Data Integrity Failures (including insecure deserialisation), A09 Security Logging and Monitoring Failures, A10 SSRF.",p:["Know the 2025 edition's changes too: more weight on software supply chain and on mishandling exceptional conditions","For each: root cause, one real example, the class-level fix"],f:"Pick one and tell me about a real finding you made in it."},
{c:"Web",src:"Q&A PDF Q16",q:"Explain the double-submit cookie pattern for CSRF.",a:"The server sets a random value in a cookie and requires the same value in a header or form field; the request is valid only if they match. An attacker on another site can't read the cookie, so can't copy it into the request.",p:["Weakness: if an attacker can set cookies (subdomain takeover, cookie injection), they can set both values","Stronger: sign the token or bind it to the session (signed double-submit), plus SameSite cookies"],f:"Why is the synchroniser token pattern considered stronger?"},
{c:"Web",src:"Q&A PDF Q18",q:"What is Content Security Policy and what are its common pitfalls?",a:"A response header that tells the browser which sources of script, style, frames and connections are allowed, limiting the impact of XSS. Key directives: default-src, script-src, object-src, frame-ancestors, connect-src.",p:["Pitfalls: 'unsafe-inline', 'unsafe-eval', wildcards, allow-listing CDNs that host JSONP or old Angular (bypassable)","Prefer nonce- or hash-based policies with 'strict-dynamic'","Roll out with Content-Security-Policy-Report-Only first"],f:"How would you deploy CSP on a large legacy app?"},
{c:"Web",src:"Q&A PDF Q20",q:"SSRF vs CORS vs SOP: how do they relate?",a:"SOP and CORS are browser rules about what script can read across origins. SSRF happens on the server: the server itself sends the request, so browser policies don't apply at all. That's why SSRF can reach internal services and cloud metadata that no browser could.",p:["CORS misconfigurations leak data to attacker websites; SSRF lets attackers pivot into your network"],f:"Can a strict CORS policy prevent SSRF?"},
{c:"Web",src:"Q&A PDF Q29",q:"How does ' OR '1'='1 work in SQL injection?",a:"If input is concatenated into WHERE username='INPUT', the payload closes the string and adds a condition that is always true, so the query returns every row (or bypasses a login check). Variants like admin'-- comment out the rest of the query.",p:["Understanding the query context (quotes, numeric fields, ORDER BY) decides the payload","Parameterised queries make this impossible"],f:"Why doesn't escaping single quotes fully solve it?"},
{c:"AuthN & AuthZ",src:"Q&A PDF Q30",q:"How does session hijacking work and how do you prevent it?",a:"An attacker obtains a valid session ID through XSS, sniffing unencrypted traffic, predictable IDs, session fixation, or leaks in URLs and logs, then uses it as the victim. Prevent with HttpOnly and Secure cookies, HTTPS everywhere with HSTS, random IDs regenerated at login, short idle timeouts, and anomaly detection.",p:["Binding sessions to IP breaks mobile users; use it as a risk signal, not a hard rule","Step-up auth for sensitive actions limits damage"],f:"How would you detect a hijacked session?"},
{c:"AuthN & AuthZ",src:"Q&A PDF Q31",q:"Explain each cookie attribute.",a:"HttpOnly: not readable by JavaScript. Secure: sent only over HTTPS. SameSite: controls cross-site sending (Strict, Lax, None). Domain: which hosts receive it (omit to keep it host-only). Path: URL scope. Expires/Max-Age: makes it persistent. __Host- prefix: forces Secure, Path=/ and no Domain. __Secure- prefix: forces Secure.",p:["Auth cookies: __Host-, HttpOnly, Secure, SameSite=Lax or Strict, short lifetime"],f:"Why is setting Domain=.example.com risky?"},
{c:"AuthN & AuthZ",src:"Q&A PDF Q80",q:"SameSite=Strict vs Lax vs None — what's sent when?",a:"Strict: never sent on cross-site requests, even link clicks. Lax: sent on top-level GET navigations (clicking a link) but not on cross-site subrequests or POSTs. None: sent on all requests and must be Secure. Without the attribute, Chromium treats cookies as Lax by default; behaviour differs across browsers.",p:["Lax still allows CSRF via state-changing GET endpoints","'Same-site' means same registrable domain, so sibling subdomains count as same-site"],f:"Does SameSite=Lax fully stop CSRF?"},
{c:"AuthN & AuthZ",src:"Q&A PDF Q33",q:"Token-based vs session-based authentication?",a:"Session-based: the server keeps state and the client holds a random ID in a cookie; easy to revoke. Token-based (JWT): the client holds a signed token and servers verify it statelessly; scales well across services but is hard to revoke before expiry.",p:["Common hybrid: session cookie to a BFF, JWT access tokens between backend services","Store tokens in HttpOnly cookies or server side, not localStorage"],f:"When would you choose sessions over JWTs?"},
{c:"AuthN & AuthZ",src:"Q&A PDF Q34",q:"A JWT leaks. What's the impact and mitigation?",a:"Whoever holds it can act as the user until it expires: full account access for its scopes. Limit impact with short lifetimes, refresh token rotation with reuse detection, audience-scoped tokens, and the ability to revoke (jti deny-list or session revocation at the IdP). Find and fix the leak source: localStorage + XSS, URLs and logs, Referer headers.",p:["Sender-constrained tokens (DPoP, mTLS-bound) make stolen tokens useless elsewhere"],f:"How would you revoke all tokens for one user immediately?"},
{c:"AuthN & AuthZ",src:"Q&A PDF Q42",q:"Persistent vs session cookies?",a:"A session cookie has no Expires or Max-Age and disappears when the browser closes. A persistent cookie has an expiry and survives restarts, which widens the window if it's stolen. Auth cookies should be short-lived and always Secure and HttpOnly.",p:["'Remember me' should use a separate long-lived token that can only create a new session, with re-auth for sensitive actions"],f:"How would you design 'remember me' securely?"},
{c:"SDLC & Tooling",src:"Q&A PDF Q44",q:"What is a secure SDLC?",a:"Security built into every phase: requirements (security requirements, abuse cases), design (threat modeling, architecture review), development (secure coding standards, IDE checks, code review), testing (SAST, SCA, DAST, pentest), deployment (hardening, secrets management, signed artefacts), and operations (monitoring, vulnerability management, disclosure). Shift-left means catching issues earlier, where fixes are cheaper.",p:["Frameworks: NIST SSDF, OWASP SAMM, Microsoft SDL"],f:"Which phase gives the most value per hour of security effort?"},
{c:"SDLC & Tooling",src:"Q&A PDF Q46 / Q69",q:"What is SCA and how would you roll it out across a company?",a:"Software Composition Analysis inventories open-source dependencies and flags known vulnerabilities and licence issues. Rollout: scan every repo in CI (Snyk, Dependabot, OWASP Dependency-Check), generate SBOMs (CycloneDX/SPDX) into Dependency-Track, alert on Critical/High with reachability and EPSS/KEV context, auto-open upgrade PRs (Renovate/Dependabot), and track licence policy (for example GPL in distributed products).",p:["Without reachability and priority context, SCA floods teams with noise"],f:"How do you stop SCA alert fatigue?"},
{c:"SDLC & Tooling",src:"Q&A PDF Q49",q:"Name tools for each security testing category.",a:"SAST: Semgrep, CodeQL, SonarQube, Checkmarx. SCA: Snyk, Dependabot, Dependency-Check, Mend. DAST: OWASP ZAP, Burp Suite Enterprise, Invicti. Secrets: gitleaks, TruffleHog, GitGuardian. IaC: Checkov, tfsec, KICS. Containers: Trivy, Grype. Kubernetes: kube-bench, Kyverno, Falco. Cloud posture: Prowler, Wiz, Prisma Cloud.",p:["Senior point: tool choice matters less than tuning, integration and ownership"],f:"How would you choose between two SAST tools?"},
{c:"Detection & IR",src:"Q&A PDF Q52",q:"What is pattern recognition / anomaly detection in security?",a:"Finding deviations from normal behaviour in logs, traffic or code. Techniques: baselines and thresholds, correlation rules, UEBA (user and entity behaviour analytics), ML anomaly detection, YARA for files. Example: impossible travel, a user suddenly accessing hundreds of records, or a service account used interactively.",p:["Anomaly detection needs good baselines and feedback, or it becomes noise"],f:"Give an anomaly rule for detecting IDOR enumeration."},
{c:"Web",src:"Q&A PDF Q57",q:"Name some interesting real-world vulnerabilities and what they teach.",a:"Log4Shell (2021): JNDI lookups in logged strings led to RCE; lesson: ubiquitous dependencies and SBOMs. Heartbleed (2014): OpenSSL over-read leaked memory and keys; lesson: memory safety. Shellshock: Bash environment parsing to RCE. SolarWinds SUNBURST: build-system compromise. xz utils (2024): maintainer social engineering. Dependency confusion (2021): public packages shadowing internal names.",p:["Always explain root cause, impact, fix, and what control would have caught it"],f:"Which of these would your programme have caught first, and how?"},
{c:"Web",src:"Q&A PDF Q58",q:"Which JavaScript functions cause DOM XSS, and what should you use instead?",a:"Dangerous sinks: innerHTML, outerHTML, insertAdjacentHTML, document.write, eval, setTimeout/setInterval with strings, new Function, location or href assignment with user input, jQuery .html(). Use textContent, setAttribute for safe attributes, createElement + appendChild, URL validation for links, DOMPurify when HTML is required, and Trusted Types to enforce it.",p:["Sources to watch: location.hash/search, document.referrer, postMessage data, localStorage"],f:"How does Trusted Types prevent DOM XSS at scale?"},
{c:"Containers & K8s",src:"Q&A PDF Q59",q:"How do you pentest Kubernetes and Docker environments?",a:"Check exposed API server, kubelet (10250) and etcd; RBAC and default service account permissions; privileged pods, hostPath and hostPID; mounted service account tokens; docker.sock mounts; secrets in environment variables or images; network policies; and known runtime escapes such as CVE-2019-5736 (runc). Tools: kube-hunter, kube-bench, Trivy, peirates, deepce.",p:["Test from inside a pod too: what can a compromised workload reach?"],f:"You have shell in a pod. What do you check first?"},
{c:"Cryptography",src:"Q&A PDF Q61",q:"How are TLS certificates attacked or abused?",a:"Users clicking through warnings for self-signed or expired certificates, mis-issuance by a compromised or careless CA (DigiNotar), certificates issued after subdomain or BGP hijacks, stolen private keys (especially wildcard keys), and weak validation in clients. Defences: Certificate Transparency monitoring (crt.sh), CAA records, short-lived certificates, protected keys, strict client validation.",p:["Wildcard certificate keys copied to many servers widen the blast radius"],f:"How would you detect a certificate issued for your domain that you didn't request?"},
{c:"Web",src:"Q&A PDF Q64",q:"Map common vulnerabilities to OWASP Top 10 (2021) categories.",a:"IDOR and privilege escalation → A01. Weak crypto, cleartext secrets → A02. SQLi, XSS, command injection → A03. Missing threat modeling and business logic flaws → A04. XXE, verbose errors, default configs → A05. Vulnerable libraries → A06. Weak login, session issues, credential stuffing → A07. Insecure deserialisation, unsigned updates, CI/CD integrity → A08. Missing logging and alerting → A09. SSRF → A10.",p:["Note: XXE sits in A05 in the 2021 list, not A03"],f:"Where would a race condition in payments fit?"},
{c:"SDLC & Tooling",src:"Q&A PDF Q65",q:"What is your source code review methodology?",a:"Understand the stack and architecture; map entry points (routes, parameters, headers, uploads, queues); review authentication and authorization code first; trace data from sources to sinks; check crypto, secrets, deserialisation, file and URL handling; use SAST and grep/Semgrep for leads; then confirm exploitability and write the fix and a regression rule.",p:["Time-box: breadth across entry points first, depth on the riskiest flows"],f:"You have one day on a 300k-line codebase. What do you do?"},
{c:"Web",src:"Q&A PDF Q66",q:"What are sqlmap's key features and how do you use it responsibly?",a:"It detects and exploits SQL injection: -p to target a parameter, --level/--risk for depth, --batch for non-interactive runs, --dbs/--tables/--dump to enumerate, --tamper scripts for WAF evasion, --os-shell or --file-read where stacked queries allow, and cookies/headers for authenticated testing.",p:["Only with written permission; avoid --dump of real data in production; use it to confirm, then stop"],f:"When would you prefer manual exploitation over sqlmap?"},
{c:"SDLC & Tooling",src:"Q&A PDF Q68 / Q81",q:"What security work have you automated, and how?",a:"Typical wins: CI/CD gates (SAST, SCA, secrets, IaC), nightly authenticated DAST against staging (ZAP in GitHub Actions with Playwright login), recon pipelines (subfinder, httpx, nuclei), SOAR playbooks (enrich, block, notify), finding-to-ticket automation with owners and SLAs, and LLM-assisted triage with human review. Measure time saved and false-positive rates.",p:["Rule of thumb: automate anything done by hand three times"],f:"What did automation break, and how did you fix it?"},
{c:"Coding",src:"Q&A PDF Q70",q:"Which programming skills matter for a security engineer?",a:"Python for automation, PoCs, tool APIs and log parsing (requests, regex, pandas, boto3); Bash for glue; JavaScript/TypeScript for web and Node.js review; reading Java, Go and C# for code review; SQL for injection and detection queries; regex for rules. Senior roles also expect writing small services or integrations, not only scripts.",p:["Be ready for a live practical coding round"],f:"Show me how you'd parse 10 GB of logs efficiently."},
{c:"OS & Systems",src:"Q&A PDF Q73",q:"What are the security risks of thin clients and VDI?",a:"Unencrypted or weakly authenticated RDP/VNC/ICA sessions, session hijacking, clipboard and drive redirection leaking data, USB redirection, default credentials on management consoles, and a shared back-end where one compromise affects many users. Harden with TLS, MFA, disabling unneeded redirection, segmentation and patching.",p:[],f:"How would you stop data leaving a VDI session?"},
{c:"Networking",src:"Q&A PDF Q75",q:"How do Certificate Transparency and subdomain takeover connect?",a:"CT logs (crt.sh) reveal every certificate issued for your domains, which attackers use to enumerate subdomains. Subdomains with dangling CNAMEs to deprovisioned services (S3, GitHub Pages, Heroku) can be claimed; the attacker then serves content and can even get a valid certificate for that subdomain. Defend by monitoring CT, removing dangling records, and scoping cookies to hosts.",p:["Tools: subjack, subzy, nuclei takeover templates"],f:"What's the impact if session cookies are scoped to the parent domain?"},
{c:"Networking",src:"Q&A PDF Q77",q:"What do you test on port 53 (DNS)?",a:"Zone transfer (dig axfr), open recursion (amplification abuse), cache poisoning resistance, DNSSEC validation and zone walking (NSEC), subdomain brute force, version disclosure, DNS tunnelling paths, and split-horizon leaks of internal names.",p:["Most real findings: zone transfers and internal hostnames exposed"],f:"Why is an open resolver a problem for the internet, not just you?"},
{c:"Programme",src:"Q&A PDF Q78",q:"What vulnerabilities would you look for in a supermarket POS system?",a:"Flat networks connecting POS terminals to corporate systems, RAM-scraping malware reading card data before encryption (the Target 2013 breach pattern), weak or missing point-to-point encryption, default credentials, unpatched embedded Windows, exposed remote access for vendors, physical tampering and skimmers, and insecure Wi-Fi.",p:["PCI DSS: segmentation, P2PE, patching, logging, vendor remote-access controls"],f:"How would you test segmentation between POS and corporate networks?"},
{c:"Web",src:"Q&A PDF Q79",q:"How can you send multiple payloads without sending multiple requests?",a:"HTTP/2 multiplexing (many streams on one connection), HTTP/1.1 pipelining, batch APIs and GraphQL batching or aliases, arrays of values in JSON or XML bodies, WebSocket messages, stacked SQL queries where supported, and multi-command gopher:// payloads in SSRF.",p:["GraphQL aliases are a common way to bypass per-request rate limits on login or OTP"],f:"How would you rate-limit GraphQL properly?"},
{c:"Web",src:"Q&A PDF QD1",q:"HTTP/2 vs HTTP/1.1 from a security perspective?",a:"HTTP/2 is binary, multiplexed and uses header compression (HPACK). Benefits: no CL/TE ambiguity end to end. Risks: request smuggling when proxies downgrade HTTP/2 to HTTP/1.1, stream-based DoS (Rapid Reset, CVE-2023-44487), and single-packet attacks making race conditions easier to exploit.",p:["Run HTTP/2 end to end where possible; patch proxies for Rapid Reset"],f:"What was the HTTP/2 Rapid Reset attack?"},
{c:"Web",src:"Q&A PDF QD3",q:"What are business logic vulnerabilities and how do you find them?",a:"Flaws in how the application's rules are enforced rather than in input handling: skipping steps in a workflow, negative quantities or prices, reusing coupons, changing currency, bypassing approval limits, abusing refunds. Find them by understanding the business process, mapping state transitions and assumptions, then testing each with out-of-order, repeated, parallel and boundary inputs.",p:["Scanners can't find these; this is where manual testing pays off","Fix with server-side state machines and invariant checks"],f:"Give an example you found and how it was fixed."},
{c:"Cloud",src:"Q&A PDF QD7",q:"What are the top cloud misconfigurations you look for?",a:"Public storage buckets and snapshots, over-permissive IAM (wildcards, PassRole, unused admin users with old keys), security groups open to 0.0.0.0/0 on SSH, RDP or databases, IMDSv1 on instances, disabled or unprotected logging, unencrypted data stores, exposed management interfaces (Kubernetes API, Elasticsearch), secrets in environment variables or user data, and missing MFA on root and console users.",p:["Prioritise by toxic combinations: public + vulnerable + over-privileged"],f:"Which would you fix first in a new account?"},
{c:"Cloud",src:"Q&A PDF QD8",q:"How do you secure infrastructure as code?",a:"Scan Terraform, CloudFormation and Helm in pull requests (Checkov, tfsec, KICS), enforce org standards with policy as code (OPA/Conftest, Sentinel), run checks on the plan output, keep state files encrypted and access-controlled, use reviewed reusable modules, detect drift, and back it with preventive guardrails (SCPs) and detective rules (AWS Config).",p:["Fix posture issues in the module, not the console, so they don't return"],f:"How do you handle a team that needs an exception to a policy?"},
{c:"Programme",src:"Q&A PDF QD12",q:"Which certifications matter for AppSec and product security roles?",a:"Hands-on certifications carry the most weight: OSWE (web exploitation and code review), OSCP, Burp Suite Certified Practitioner, and AWS Security Specialty for cloud-heavy roles. CSSLP and CISSP help for programme and leadership roles. At senior level, CVEs, bug bounty results and shipped programmes usually matter more than certificates.",p:["Mention what you're working towards and why it fits the role"],f:"Why aren't you OSCP or OSWE certified yet?"},
{c:"Programme",src:"Q&A PDF QD13",q:"How do you stay current in security?",a:"Name a concrete routine: specific newsletters or feeds (for example tl;dr sec, PortSwigger research, Project Zero), hands-on labs, reading new CVE writeups and patch diffs, conference talks, and your own research or bug bounty work. Then give a recent example of something you learned and applied.",p:["Specific and recent beats a long list"],f:"What's something you learned last month and used at work?"},
{c:"Web",src:"Behavioral PDF Sq3",q:"Which vulnerability classes do scanners consistently miss? Give examples.",a:"Business-logic authorization (IDOR/BOLA across tenants or accounts), race conditions (parallel coupon or balance abuse), second-order injection (stored safely, executed unsafely later), multi-step workflow bypasses, and chained issues. Scanners don't know your role model or business state, and they test sequentially.",p:["Your examples: trading platform IDOR via account B replaying account A's portfolio IDs; 20 parallel coupon requests applying 14 times; admin'-- username triggering SQLi in an admin report"],f:"How would you make these testable automatically?"}
];

window.BEH2 = [
{id:"strengths",q:"What are your strengths as a security engineer?",tests:"Self-awareness backed by evidence.",lp:["Are Right, A Lot"],guide:"Three strengths, each with proof and a number. Generic traits score low.",outline:"(1) Adversarial thinking: 120+ high/critical findings tools missed, by focusing on business logic and authorization. (2) Developer empathy: findings with PoCs and fix diffs so teams fix fast. (3) Automation-first: CI/CD gates that cut escaped defects (use the number you've settled on)."},
{id:"future",q:"Where do you see yourself in 3–5 years?",tests:"Direction and fit with the company's stage.",lp:[],guide:"Show the move from finding issues to building systems that prevent them; tie it to their stage (scaling vs mature).",outline:"Leading an AppSec programme at a product company: designing the security architecture, building developer enablement, owning the metrics that prove it works, and mentoring engineers. Deepening cloud-native and AI security along the way."},
{id:"improve",q:"What would you improve to be a better security engineer?",tests:"Honest gaps with an active plan.",lp:["Learn and Be Curious"],guide:"Two or three real gaps, each with what you're doing about it and current progress. Only state progress that's true.",outline:"Gaps you named: low-level exploitation (pwn.college, aiming for OSED), cloud-native attack paths (personal Kubernetes lab), and writing developer training. Add a fourth if true: system-design interviews and algorithmic coding."},
{id:"recentproj",q:"Walk me through a recent project: challenges and outcome.",tests:"Scope, decisions, trade-offs, measurable outcome.",lp:["Deliver Results"],guide:"Use Scale → Architecture → Outcome. Name the hardest challenge and the trade-off you made.",outline:"Your PDF version: e-commerce platform preparing for SOC 2 Type II; gap assessment, Semgrep + Dependency-Check in GitHub Actions, SLA policy, two full pentests, Graylog evidence dashboard. Challenge: 38% false positives breaking builds, tuned to 8%. Result: passed with zero security findings."},
{id:"nextco",q:"What are you looking for in your next company?",tests:"Motivation and whether you'll stay.",lp:[],guide:"Three priorities in order, tied to outcomes not titles.",outline:"Hands-on technical depth; an engineering culture where security is embedded (or where you build that); a team that measures outcomes like escape rate and MTTR rather than activity."},
{id:"rce",q:"You find RCE on a public-facing site and developers hesitate to take it down. What do you do?",tests:"Escalation judgement and communication under pressure.",lp:["Have Backbone; Disagree and Commit","Customer Obsession"],guide:"Demonstrate impact safely, offer minimum viable containment (not all-or-nothing), escalate in writing, never exploit beyond the PoC.",outline:"Your story: SSRF-to-RCE on a payment API; ran the chain in staging and retrieved IAM credentials in 90 seconds; proposed disabling the webhook preview feature as a 30-minute containment; sent a written risk statement to the CISO. Feature disabled in 2 hours, full fix the same sprint."},
{id:"surfaces",q:"What are the possible attack surfaces in a given architecture?",tests:"Structured threat thinking, not a list of attack names.",lp:["Dive Deep"],guide:"Walk the layers outside-in: perimeter, identity, application, service-to-service, data, CI/CD, cloud config, people and endpoints. Then name the top three you'd fix.",outline:"Your session: a microservices SaaS on AWS with GitHub Actions. Top findings: no service-to-service auth (internal assumed trusted), PR title injected into shell commands in CI, uploads bucket planned as public instead of pre-signed URLs. All fixed before development."},
{id:"owaspllm",q:"How do OWASP categories, automation and LLMs connect in your workflow?",tests:"Whether your tools form a system.",lp:["Invent and Simplify"],guide:"Three parts: findings mapped to OWASP/CWE automatically, LLM-assisted triage with human sign-off, and benchmarking tool accuracy (OWASP Benchmark).",outline:"Semgrep rules tagged with CWE, a script mapping CWE to OWASP categories per sprint, LLM triage of flagged code (human-validated), OWASP Benchmark to measure each tool's true/false-positive rates. Result: the auditor accepted the automated OWASP coverage dashboard; manual reporting went from days to zero."},
{id:"personal",q:"Tell me about your personal projects.",tests:"Genuine curiosity, with proof.",lp:["Learn and Be Curious"],guide:"What, why, what you learned, public proof. Always have one specific recent thing.",outline:"Hypothesis-driven OSS research on CMS RBAC that produced CVE-2023-2240 and CVE-2023-2014; HackTheBox for AD and binary skills (name a specific recent box); custom Nuclei templates; writeups. Also your Claude-based bug bounty skills and Burp MCP workflow, if you're comfortable discussing them."},
{id:"aisec",q:"What is your role in LLM / AI security, and which risks do you focus on?",tests:"AI security as a discipline, not just AI as a tool.",lp:["Dive Deep"],guide:"Two sides: using AI safely in your own work, and threat modeling AI products. Use the current OWASP LLM Top 10 (2025) names.",outline:"Your fintech chatbot review: indirect prompt injection through a PDF in the knowledge base returned another customer's data; the function-calling tool had no input validation. Fixes: output validation, least-privilege tools, per-customer retrieval, human approval for account changes. Update the risk names to 2025: Prompt Injection (LLM01), Sensitive Information Disclosure (LLM02), Improper Output Handling (LLM05), Excessive Agency (LLM06)."},
{id:"evolve",q:"How has your methodology evolved over 60+ assessments?",tests:"Growth and judgement.",lp:["Learn and Be Curious"],guide:"Three stages with an example at each: tool-driven, adversarial, threat-model-first.",outline:"Early: scanner and checklist. Middle: 'what's the most valuable asset and shortest path to it?' (webhook signature bypass on a payment platform). Now: threat model before the first request, ~20% of time on authorization and business logic, prioritise by exploitability × impact, reports with an attack narrative."},
{id:"owaspfind",q:"Pick one OWASP category and tell me about a real finding you made in it.",tests:"That OWASP is real experience, not a buzzword.",lp:["Dive Deep"],guide:"One category, one finding, root cause, impact, fix, and the class-level follow-up.",outline:"A01 Broken Access Control: trading platform; mapped portfolio IDs as user A, replayed with user B's token, full horizontal access to trades and P&L. Root cause: authenticated but no ownership check. Emergency patch, then a codebase-wide audit that found 12 more endpoints."}
];

window.CONFLICTS2 = [
 ["OWASP LLM Top 10 numbering","Behavioral PDF B18 uses the 2023 v1 numbering: LLM02 Insecure Output Handling, LLM06 Sensitive Information Disclosure, LLM07 Insecure Plugin Design, LLM08 Excessive Agency.","The 2025 list renumbered and renamed these: LLM02 Sensitive Information Disclosure, LLM05 Improper Output Handling, LLM06 Excessive Agency; plugin design was folded into other items.","Use the 2025 names, or say which version you're quoting. Interviewers working on AI security will notice."],
 ["Claims that need to be true today","B10 says pwn.college ~40% complete, a Kubernetes lab with 3 CVE reproductions, a training module in review. B11 mentions 2M+ daily users and 'developer NPS'.","Interviewers often ask to see or hear details of these.","Keep only what you can show or describe in detail."],
 ["OWASP Top 10 mapping in Q&A PDF Q64","Q64 maps XXE to A03 Injection.","In the 2021 list, XXE is part of A05 Security Misconfiguration.","Corrected in the lab's question bank."]
];

// Coverage index: every question in both PDFs → where it lives in the lab
// t: q = question bank (substring of question text), b = behavioral builder id, s = story bank id, m = [hash, label]
window.PDFMAP = [
 ["AppSec Q&A PDF · Technical",[
  ["Q1","What is cryptography?","q","What is cryptography in cybersecurity"],["Q2","Hash vs encryption vs encoding","q","Encoding vs hashing vs encryption"],["Q3","Explain SSL/TLS","q","Walk through the TLS 1.3 handshake"],["Q4","TCP 3-way handshake","q","TCP vs UDP"],["Q5","TLS in mobile apps","q","How should TLS be handled in mobile apps"],["Q6","SAML vs OAuth vs OIDC","q","OAuth 2.0 vs OpenID Connect vs SAML"],
  ["Q7","CIA triad","q","What is the CIA triad"],["Q8","OWASP Top 10 (2021)","q","List the OWASP Top 10 (2021)"],["Q9","DOM vs reflected vs stored XSS","q","Explain the three types of XSS"],["Q10","What is CSRF","q","How does CSRF work"],["Q11","CSRF bypasses with a token","q","How can CSRF protection be bypassed"],["Q12","SSRF exploitation","q","Explain SSRF, its impact"],
  ["Q13","SSRF mitigation","m",["#code-ssrf","SSRF drill"]],["Q14","SQL injection types","q","Types of SQL injection"],["Q15","HTTP parameter pollution","q","HTTP Parameter Pollution"],["Q16","Double-submit cookie","q","double-submit cookie pattern"],["Q17","CORS vs SOP","q","Explain the Same-Origin Policy and CORS"],["Q18","Content Security Policy","q","What is Content Security Policy"],
  ["Q19","CRLF injection","q","Explain CRLF injection"],["Q20","SSRF vs CORS vs SOP","q","SSRF vs CORS vs SOP"],["Q21","Request smuggling","q","HTTP request smuggling"],["Q22","Prototype pollution","q","prototype pollution in JavaScript"],["Q23","XXE / XML injection","q","Explain XXE"],["Q24","Race conditions","q","race conditions in web apps"],
  ["Q25","LFI vs RFI vs traversal","q","LFI vs RFI vs directory traversal"],["Q26","Security headers + XSS remediation","q","Which security headers matter"],["Q27","SSTI","q","server-side template injection"],["Q28","CORS misconfiguration (and SQLi via Origin)","q","Explain the Same-Origin Policy and CORS"],["Q29","' OR 1=1","q","OR '1'='1 work"],["Q30","Session hijacking","q","How does session hijacking work"],
  ["Q31","Cookie attributes","q","Explain each cookie attribute"],["Q32","Session fixation","q","What makes session management secure"],["Q33","Token vs session auth","q","Token-based vs session-based"],["Q34","JWT leak","q","A JWT leaks"],["Q35","CSRF with JWTs","q","How does CSRF work"],["Q36","CyberArk Conjur","q","HashiCorp Vault or CyberArk Conjur"],
  ["Q37","Port numbers","q","Which port numbers"],["Q38","DNS vs DHCP","q","DNS vs DHCP"],["Q39","REST vs SOAP security","q","REST vs SOAP vs GraphQL"],["Q40","Typing a domain in the browser","q","What happens when you type a URL"],["Q41","Nmap commands","q","Which nmap options"],["Q42","Persistent cookie","q","Persistent vs session cookies"],
  ["Q43","SOP vs CORS detailed","m",["#flows-cors","CORS walkthrough"]],["Q44","Secure SDLC","q","What is a secure SDLC"],["Q45","SAST vs DAST","q","SAST vs DAST vs IAST"],["Q46","SCA","q","What is SCA and how would you roll it out"],["Q47","Shift-left in CI/CD","q","Design a secure CI/CD pipeline"],["Q48","Validating SAST vs DAST findings","q","How do you validate a SAST finding"],
  ["Q49","Discovery tools","q","Name tools for each security testing category"],["Q50","CrowdStrike / EDR","q","EDR vs XDR vs SIEM"],["Q51","QRadar architecture","q","Describe a SIEM architecture"],["Q52","Pattern recognition","q","pattern recognition / anomaly detection"],["Q53","Android components","q","What are the Android components"],["Q54","App-to-app redirection, deep links","q","deep links and WebView"],
  ["Q55","Exploiting exported activities","q","What are the Android components"],["Q56","iOS jailbreak","q","jailbroken iOS device"],["Q57","Interesting vulnerabilities","q","interesting real-world vulnerabilities"],["Q58","DOM XSS sinks","q","Which JavaScript functions cause DOM XSS"],["Q59","Kubernetes/Docker pentesting","q","How do you pentest Kubernetes"],["Q60","Prototype pollution in Node.js","q","prototype pollution in JavaScript"],
  ["Q61","Exploiting SSL certificates","q","How are TLS certificates attacked"],["Q62","Lateral movement vs pivoting","q","Lateral movement vs pivoting"],["Q63","CVE vs CWE","q","CVE vs CWE vs CVSS"],["Q64","OWASP category per vulnerability","q","Map common vulnerabilities to OWASP"],["Q65","Source code review methodology","q","What is your source code review methodology"],["Q66","sqlmap","q","sqlmap's key features"],
  ["Q67","LLM-integrated automation","q","How would you use AI to reduce MTTR"],["Q68","Security automation","q","What security work have you automated"],["Q69","SCA in a company","q","What is SCA and how would you roll it out"],["Q70","Programming for security","q","Which programming skills matter"],["Q71","Horizontal vs vertical privesc","q","Horizontal vs vertical privilege escalation"],["Q72","Deserialisation","q","What is insecure deserialisation"],
  ["Q73","Thin client security","q","thin clients and VDI"],["Q74","Race conditions in bug bounty","q","send many requests at the same instant"],["Q75","CT logs + subdomain takeover","q","Certificate Transparency and subdomain takeover"],["Q76","HttpOnly bypass","q","Can HttpOnly be bypassed"],["Q77","Port 53 tests","q","What do you test on port 53"],["Q78","POS system vulnerabilities","q","supermarket POS"],
  ["Q79","Many payloads, one request","q","multiple payloads without sending multiple requests"],["Q80","SameSite values","q","SameSite=Strict vs Lax vs None"],["Q81","Automation (JMeter/Python)","q","What security work have you automated"],["Q82","HTTP security headers","q","Which security headers matter"],["Q83","HTTP methods","q","Which HTTP methods matter"]]],
 ["AppSec Q&A PDF · Behavioral (Part B)",[
  ["QB1","Explaining tech to non-technical people","b","customer"],["QB2","Attack surfaces in an architecture","b","surfaces"],["QB3","Resolving conflict","b","conflict"],["QB4","A failure","b","fail"],["QB5","Tell me about yourself","b","tmay"],["QB6","Why this role/company","b","why"],["QB7","Strengths","b","strengths"],["QB8","Improve as a pentester","b","improve"],
  ["QB9","Next company","b","nextco"],["QB10","3rd-party CVE, no patch","m",["#incident-zero","Zero-day incident sim"]],["QB11","RCE, developers hesitate","b","rce"],["QB12","OWASP + automation + LLM","b","owaspllm"],["QB13","Recent project","b","recentproj"],["QB14","Personal projects","b","personal"],["QB15","Your role in AI security","b","aisec"]]],
 ["AppSec Q&A PDF · Part C and D",[
  ["Part C","Questions to ask your interviewer","m",["#loops","How loops work → Questions to ask"]],["QD1","HTTP/2 vs HTTP/1.1","q","HTTP/2 vs HTTP/1.1"],["QD2","IDOR","q","Why do scanners miss IDOR"],["QD3","Business logic","q","business logic vulnerabilities"],["QD4","GraphQL","q","main GraphQL security issues"],["QD5","OWASP LLM Top 10","q","OWASP Top 10 for LLM"],["QD6","Shared responsibility","q","shared responsibility model"],
  ["QD7","Top cloud misconfigurations","q","top cloud misconfigurations"],["QD8","IaC security","q","How do you secure infrastructure as code"],["QD9","Threat modeling","m",["#threat","Threat model lab"]],["QD10","Incident response","q","incident response lifecycle"],["QD11","Supply chain attacks","q","xz utils backdoor"],["QD12","Certifications","q","Which certifications matter"],["QD13","Staying current","q","How do you stay current"]]],
 ["Senior Behavioral PDF",[
  ["B1","Tell me about yourself","b","tmay"],["B2","Why leaving / why this role","b","why"],["B3","Explaining to non-technical people","b","customer"],["B4","Conflict with engineering","b","conflict"],["B5","Failure","b","fail"],["B6","Convincing a stakeholder","b","influence"],["B7","Strengths","b","strengths"],["B8","3–5 years","b","future"],["B9","Why this company","b","why"],
  ["B10","What you'd improve","b","improve"],["B11","Recent project","b","recentproj"],["B12","Next company","b","nextco"],["B13","3rd-party CVE, no patch","m",["#incident-zero","Zero-day incident sim"]],["B14","RCE, developers hesitate","b","rce"],["B15","Attack surfaces","b","surfaces"],["B16","OWASP + automation + LLM","b","owaspllm"],["B17","Personal projects","b","personal"],["B18","AI/LLM security role","b","aisec"],
  ["Sq1","~40% fewer defects: how measured","s","prog"],["Sq2","MTTR: your contribution","s","mttr"],["Sq3","Classes tools miss","q","scanners consistently miss"],["Sq4","Methodology evolution","b","evolve"],["Sq5","CVE-2023-2240","s","cve"],
  ["Part 3","Validating SAST by code review only","q","How do you validate a SAST finding"],["Part 4","AI tools you use today","m",["#ai-triage","AI at every layer"]],["R1","KubeArmor and Cilium","s","kube"],["R2","Graylog + Wazuh automation","s","siem"],["R3","Threat modeling session","s","tm7"],["R4","Your CVEs and disclosure","s","cve"],["R5","SOC 2 / ISO ownership","s","soc2"],
  ["X1","One OWASP category, real finding","b","owaspfind"],["X2","Hardest part of SAST/DAST rollout","s","sast"],["X3","Vulnerability found at design phase","s","tm7"],["X4","Mobile methodology","q","mobile application testing methodology"],["X5","Reporting a finding to a client","b","customer"]]],
 ["ProductSec Transition Stories PDF",[
  ["Story 1","Built a programme from scratch","s","prog"],["Story 2","SAST noise to signal","s","sast"],["Story 3","SIEM ownership","s","siem"],["Story 4","SOC 2 ownership","s","soc2"],["Story 5","Vulnerability management programme","s","vm"],["Story 6","Influence without authority","b","conflict"],["Story 7","Threat model at design","s","tm7"],
  ["HQ1","Prioritising 200 open vulnerabilities","s","vm"],["HQ2","Programme when security is seen as friction","q","balance security and delivery speed"],["HQ3","Measuring the programme","q","How do you measure an AppSec programme"],["HQ4","30/60/90 days","q","first 30/60/90 days"],["Part 5","'But you were external' pushback","q","You worked as an external provider"],["Part 5B","How you measured MTTR","s","mttr"],["Part 2","Consultant vs owner language","m",["#stories","Story bank → language drill"]]]]
];
